### ISSUE TITLE
Users can't login if upgrading from clipbucket repo.

### ISSUE THREAD

**Issue by pnemuk** [MacWarrior/clipbucket-v5#104]
Users can't login if upgrading to this repo from clipbucket repo.
After few test I see on db that old pass is not updated to new if user tries to log in.
So i think issue is here

// This code is used to update user password hash
if( !$udetails )
{
$oldpass = pass_code_unsecure($password);
$udetails = $this->get_user_with_pass($username, $oldpass);
if( $udetails )
{
$db->update(tbl($this->dbtbl['users']),array('password'),array($pass)," userid='".$uid."'");
}
}

**Comment by MacWarrior** [comment]
Hi,

Thanks for report, will check this asap !

**Comment by pnemuk** [comment]
Okay thanks.

**Comment by MacWarrior** [comment]
Hi,

Can you specify your PHP version ?
Did you correctly apply the SQL : 
- upgrade_5.0.sql
- upgrade_5.1.sql
- upgrade_5.3.sql
OR
- upgrade_from_original.sql _(Latest commit)_
(Don't forget to edit the table prefix before applying)

I still don't know if there is really an upgrade system integrated in CB
I certainly will work on a proper upgrade system.

**Comment by pnemuk** [comment]
We are using PHP 7.3.8

I downloaded new repo tested on test server clean install with CB 4 version DB
but still the same user password is not updating to new hash

We are using official CB repo upgraded to your repo on production server of course we have updated every changed code manually, but first every new codes we are testing on test server.

Okay i'm going to do some test tonight then i have more results for you.
Thanks again for doing so much work for this repo keep it up.

**Comment by MacWarrior** [comment]
Hi,

Glad to see you have good habits !

I have been working on PHP 7.3.X compatibility during this week (And SQL strict mode) and there is still work to do ;)

On your test env, did you applied the SQL I specified earlier ? Without them it can't work correctly and you should have some php errors

I just tested and it update correctly password from old method to new
If you have applied the SQL, the password field must be a varchar **128**
If it's not a 128, the password can't be updated and you should have a related php error 500 in your logs files

It's one of the changes made in the upgrade_5.0.sql file : 
`ALTER TABLE `{tbl_prefix}users` CHANGE `password` `password` VARCHAR(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '';`

**Comment by pnemuk** [comment]
I am still testing this issue
sql_mode = ''
password field varchar(128)

steps I have taken
registered new user
specified new user admin rights from phpmyadmin
logged to admin area with new user
from admin area have updated old user password and password updating to new hash from admin area

**Comment by MacWarrior** [comment]
Hi,

Any news ?

Best regards,
MacWarrior.

**Comment by MacWarrior** [comment]
Hello @pnemuk, 

I've been testing upgrade from CB 4.2 RC1 to CB 5.X and had no issue with login.
I've also made a quick tutorial about this process [here](https://github.com/MacWarrior/clipbucket-v5/wiki/Upgrade-from-Clipbucket-4.2)

Best regards,
MacWarrior.
