### ISSUE TITLE
Fresh installation fails.

### ISSUE THREAD

**Issue by pnemuk** [MacWarrior/clipbucket-v5#120]
Line 840 "cb_install/sql/structure.sql" is not closed properly, you forgot comma, therefore installation will not finish, because user_profile table will not be created.

**Comment by MacWarrior** [comment]
Hi, 

Thanks for report, this has been fixed in commit dc3e47ad1f3c7e56e459e2dfe0cb5f9156a55a87

Will try a clean install asap to make sure everything is OK ! :)

Best regards,
MacWarrior.
