### ISSUE TITLE
user_profile table must be AUTO_INCREMENT

### ISSUE THREAD

**Issue by pnemuk** [MacWarrior/clipbucket-v5#121]
user_profile table must be AUTO_INCREMENT if not new registered user user_profile_id will be the same as the previous registered user, in this case users will not be able to update account information.

**Comment by MacWarrior** [comment]
Hi, 

Thanks for report !
Bug has been fixed in commit e54ae8d6589fa15e86911da4a6463a852d4365be

Best regards,
MacWarrior.
