### ISSUE TITLE
[NOTICE] Double Notice: Undefined offset

### ISSUE THREAD

**Issue by aliggie** [MacWarrior/clipbucket-v5#125]
![bug](https://user-images.githubusercontent.com/56111049/83207085-9eb0d280-a152-11ea-91d8-dbc233da1f65.JPG)

**Comment by MacWarrior** [comment]
Hi,

You might want to use the latest revision and not the latest release ! (Git is your best friend)
This has been fixed since but not yet released 😄
(Cf. 6842247d46dda54af3845e80fa00888629055b70)

Anyway, thanks for report !
Best regards,
MacWarrior.
