### ISSUE TITLE
Error handler bug.

### ISSUE THREAD

**Issue by pnemuk** [MacWarrior/clipbucket-v5#126]
After update error handling found bug with like, subscribe and so on messages.
We get array instead of message.

temporary fix messages.

private function add_error($message=NULL,$secure=true) {
        $this->error_list[] = $message; // this line is for temp fix messages
	$this->error_list[] = array('val' => $message, 'secure' => $secure);
}

private function add_warning($message=NULL,$secure=true) {
        $this->warning_list[] = $message; // this line is for temp fix messages
	$this->warning_list[] = array('val' => $message, 'secure' => $secure);
}

public function add_message($message=NULL,$secure=true) {
        $this->message_list[] = $message; // this line is for temp fix messages
	$this->message_list[] = array('val' => $message, 'secure' => $secure);
}

Can you please check and update.

**Comment by MacWarrior** [comment]
Hi, 

Thanks for report ; working on it...

Best regards,
MacWarrior.

**Comment by MacWarrior** [comment]
Hi, 

Last commit fix subscribe / unsubscribe actions
Thanks again for report !

As I quite fully refactored error handling, there might be some more issues like this one but last commit should fix the most ! 😄 

Best regards,
MacWarrior.

**Comment by pnemuk** [comment]
Okay, it seems everything works except rating.

**Comment by MacWarrior** [comment]
Hi, 

Thanks again for report ; new fix has been pushed

Best regards,
MacWarrior.
