### ISSUE TITLE
Admin area menu bug.

### ISSUE THREAD

**Issue by pnemuk** [MacWarrior/clipbucket-v5#127]
Admin area collection sub menu double display.

**Comment by aliggie** [comment]
Hi,
could you attach a screenshot?

**Comment by MacWarrior** [comment]
Hi, 

This is because there is 2 collections init
Working on a fix to prevent duplicated submenus

**Comment by MacWarrior** [comment]
Hi

Please check last commit for fix 😄
Thanks again for report

Best regards,
MacWarrior.

**Comment by pnemuk** [comment]
New added plugins menu also needs to be updated.
For example add_admin_menu function in global announcement plugin.

**Comment by MacWarrior** [comment]
Hi,

You're right about plugins, 99% of them need a full refactor (and not just about the new menu "system"), but not about global announcement which has been updated ! 😄 

![image](https://user-images.githubusercontent.com/200590/83656941-7a288080-a5c0-11ea-9775-dcf8349f36ee.png)

Best regards,
MacWarrior.
