### ISSUE TITLE
An SQL error occures : Invalid default value for 'date_added'

### ISSUE THREAD

**Issue by spirogg** [MacWarrior/clipbucket-v5#129]
hi I just tried installing CB from my cPanel uploaded the script then added DB info clcik next and I get this error

An SQL error occures : Invalid default value for 'date_added'
Mysql 5.7 now upgrading to MariaDB 10.3 I will update if still same issue 

how to correct this

Centos7

**Comment by spirogg** [comment]
ok now it went ok but it doubles and get be back to same database page in install and then main site wont open
 ERROR  This page isn’t working mywebsite.com redirected you too many times.
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS

not sure what can be the issue now using centos 7 mariadb 10.3 and php7.3
i will try again with php7.2

**Comment by MacWarrior** [comment]
Hi, 

On which sql file did you get the error ?
It must be linked with mariadb 10.3 as strict mode is enabled by default

Once installation is launched, you have to manually delete all tables before trying a new installation (Except if you change of prefix during installation)

Will work on a fix when I'll get your answer and I hope the redirect error will be fixed with a fixed installation 👍

Best regards,
MacWarrior.

**Comment by spirogg** [comment]
Ok redirect was cpanel 
In cpanel you have option to redirect to https and also option to redirect to www or no www or none. I use another script that need redirect https and www  to work 
So this feature was on.
- installing Other script,  if I install with https://www.yourdomain.tld 
And I don't use www redirect example https://yourdomain.tld after installing, I can't login and script doesn't work correctly. 
It will only work with whichever www. Or none www you initially installed script. 
So I use force https:// and redirect http:// to https://www. 
My issue now is gone after turning off this feature and redirect for CB. I have not tried just forcing https and not www. 
This is all within cpanel not via .htaccess 
File of CB 
Do you have a better solution via .htaccess file to redirect to https://www.mydomain.tld 
If I want to make sure anyone who type in mydomain.tld or http://mydomain.tld gets redirected to https://www.mydomain.tld how can I do this for CB without these issues is redirect

**Comment by MacWarrior** [comment]
Hi,

Finally, do you have the same SQL error after updating to mariadb 10.3 ?
From my side, I've just tested full installation with mariadb10.3 and everything seems fine

Thanks by advance,
Best regards,
MacWarrior.

**Comment by spirogg** [comment]
> Hi,
> 
> Finally, do you have the same SQL error after updating to mariadb 10.3 ?
> From my side, I've just tested full installation with mariadb10.3 and everything seems fine
> 
> Thanks by advance,
> Best regards,
> MacWarrior.

Hi @MacWarrior no everything works with MariaDB 10.3 perfect

**Comment by theweeb2000** [comment]
I still have this problem, I made sure everything is up to date

ubuntu 18.04 LTS
PHP 7.4
mysql 14.14
Clipbucket 5.4

**Comment by MacWarrior** [comment]
Hi @theweeb2000,

Can you please open a new issue with a short description of how you produced the SQL error ?
Maybe also with a screenshot ?

Best regards,
MacWarrior.
