### ISSUE TITLE
Really weird emails i got as admin to Join Group 2 of these emails ?

### ISSUE THREAD

**Issue by spirogg** [MacWarrior/clipbucket-v5#130]
@MacWarrior really weird

- I received this email twice in a row "within seconds" below:

Subject: [Clipbucket] has invited you to join group "{group_name}" 
invited you to join the Clipbucket group "{group_name}".

{group_description}

To see more details confirm this group invitation, 
follow the link below:
{group_url}

Thanks,
Clipbucket

- not sure if this was ever redone but bringing this up since I just got this email

- here is the template for this email in admin area

**Email Subject**
`[{website_title}] {sender} has invited you to join group "{group_name}"`

**Email message**
```
{sender} invited you to join the {website_title} group "{group_name}".

{group_description}

To see more details and confirm this group invitation, follow the link below:
<a href="{group_url}">{group_url}</a>

Thanks,
{website_title}
```
UPDATE: READ LAST MESSAGE BELOW

**Comment by spirogg** [comment]
{sender} is not working because sender is **admin** 
for sure group_name , group_description and group_link is not working
{website_title} is **Clipbucket** this is working

**Comment by spirogg** [comment]
OK well, I just noticed there are no groups? 
we only have collections and photos.
- is there a reason why I would get 2 of these emails back to back ? about join group, this seemed like a test email since i am the only user now I have my brain working :) lol 

@MacWarrior could someone get into back end somehow or from who knows the script and run the test email script twice for the Join Group template? 
is this possible ?

something is weird

**Comment by spirogg** [comment]
@MacWarrior just an update on this.

- this happens when you click on (add as friend) then you get the email I mention above..

**Comment by MacWarrior** [comment]
Hello @spirogg,

I've recently made a cleanup of this "group" thing which has never existed, or so partially that it's wasn't usable at all.
This particular email has so been removed.

All emails and entire email management need a refactor to make it simple, clear and professional... Someday !

Best regards,
MacWarrior.
