### ISSUE TITLE
when editing a video the thumbnails show incorrect number

### ISSUE THREAD

**Issue by spirogg** [MacWarrior/clipbucket-v5#132]
- Hi when we add the thumb nail plugin and and in admin area we have it set to 2 thumbnails 
admin area> General Configurations > Website Configurations > Uploading and Conversion Settings >go to bottom and  select > Conversion Settings in the field add 2
- then go see how many thumbnails show when you edit that video and see what the number of thumbs says?

- we log back into admin area and edit that video and we look it shows 10?
- but we only have 2 seems its multiples of 5
- so if we have 2 selected will show 2x5=10

![total thumnails](https://user-images.githubusercontent.com/17736688/83962510-aa437e00-a863-11ea-8bc1-4ded9fdb9312.PNG)

- if we have 5 selected and we get 5 it will show 5x5=25 

![Number of thumbs 5](https://user-images.githubusercontent.com/17736688/83962353-3bb1f080-a862-11ea-94b5-bf6c5ee7a416.PNG)
- and now go to edit videos see it shows 25 thumbs

![thimbnails 5 shows 25](https://user-images.githubusercontent.com/17736688/83962512-b29bb900-a863-11ea-881b-b3681e2f6c01.PNG)

**Comment by spirogg** [comment]
@MacWarrior also when we go to admin area > General Configurations > Reports & Stats

all the way at the bottom it shows 97 thumbnails 
original videos 1 user thumb files 4

I think these numbers don;t make sense either I have 6 videos and total thumbs that show in eidt view are 19 thumbnails? 

- so my question is where can i actually go see how many thumbnails there are to verify ( in what folder) is it generate the thumbs ? 

- I want to make sure its not generating 97 for 6 videos only

Total Files | Sizes
-- | --
Total Files: 13                      Folder Size: 511.1 MB
Total Thumbs: 97                 Folder Size: 1.4 MB
Original Video Files: 1         Folder Size: 15 bytes
User Thumbs Files: 4           Folder Size: 6.5KB
User Background Files: 1     Folder Size: 0 bytes
Category Thumb Files: 1      Folder Size: 4.2KB
DataBase Size: 1.6 MB |        Folder Size: 1.6 MB

**Comment by MacWarrior** [comment]
Note : In fact, it count ALL files in /upload/thumbs/
So default and necessary files are also counted ; I will definitely fix that

**Comment by MacWarrior** [comment]
Hi @spirogg, 

Issue has been fixed a few time ago

Best regards,
MacWarrior.
