### ISSUE TITLE
when adding 1st photo the title saves but then try upload more button and rename title and click save not working

### ISSUE THREAD

**Issue by spirogg** [MacWarrior/clipbucket-v5#134]
- when adding 1st photo the title saves

![upload more photos not working after already upload 1](https://user-images.githubusercontent.com/17736688/83963942-15468200-a86f-11ea-932b-5e7dd46d28b5.PNG)

- but then try upload more button and rename title od 2nd photo and click save its not working
- ![2nd photo uploaded again](https://user-images.githubusercontent.com/17736688/83963966-37d89b00-a86f-11ea-8350-0469de14d7a1.PNG)
- 
![the title skirt again doesnt save after click save details for second photo](https://user-images.githubusercontent.com/17736688/83963973-4030d600-a86f-11ea-9383-4164fc81be88.PNG)

- after Clicking on Save for the second photo it takes me to this page
- 
![takes me to this page after clicking save 2nd photo](https://user-images.githubusercontent.com/17736688/83964011-6ce4ed80-a86f-11ea-856f-74d83d796988.PNG)

- then when i go view photos it did not save the title field

- 
![1st photo savedtitle 2nd photo did not](https://user-images.githubusercontent.com/17736688/83964026-84bc7180-a86f-11ea-9506-1e0b0c071570.PNG)

**Comment by MacWarrior** [comment]
Hello @spirogg, 

Just checked this issue and wasn't able to reproduce.
Upload forms have been updated recently, please try with latests revisions

Best regards,
MacWarrior.
