### ISSUE TITLE
when in admin Area we get error when clicking on update status just fyi

### ISSUE THREAD

**Issue by spirogg** [MacWarrior/clipbucket-v5#139]
see  photo below 

![image](https://user-images.githubusercontent.com/17736688/84346308-4d9ed680-ab75-11ea-8841-9b58d3d1a080.png)

**Comment by MacWarrior** [comment]
Hi,

This seems to be a server configuration issue : it can't download a file from github
Can you check if your PHP configuration `allow_url_include ` is set to ON ?

Best regards,
MacWarrior.

**Comment by spirogg** [comment]
allow_url_fopen | This option enables the URL-aware fopen wrappers that enable accessing URL object like files. Default wrappers are provided for the access of remote files using the ftp or http protocol, some extensions like zlib may register additional wrappers. | Enabled
-- | -- | --
allow_url_include | This option allows the use of URL-aware fopen wrappers with the following functions: include(), include_once(), require(), require_once(). | Enabled

@MacWarrior these both have to be turned on to work in php7.2 and php7.3

thanks

**Comment by MacWarrior** [comment]
Hi,

Thanks for reply ; I'll try to add a specific message when these PHP options aren't set properly

Best regards,
MacWarrior.

**Comment by MacWarrior** [comment]
Hello @spirogg,

I just made a fix about it, please check last revision.

Best regards,
MacWarrior.
