### ISSUE TITLE
-movflags faststart this did work in prior versions of CB i wonder if it will work here ?

### ISSUE THREAD

**Issue by spirogg** [MacWarrior/clipbucket-v5#140]
UPDATE: ANY FFMPEG VERSION 3.X OR 4.X WE NEED TO REMOVE THE +
can you add this to ffmpeg.class.php so we don't have to modify ??

You should alter the file format assignments wherever they occur:
found this at line 
1169 - 1172

BEFORE:
		
```
# file format
		if(isset($p['format']))
			$opt_av .= " -f {$p['format']} ";
```

AFTER:

```
# file format
		if(isset($p['format']))
			$opt_av .= " -movflags faststart -f {$p['format']} ";
```

- this is in /includes/classes/conversion/ffpmeg.class.php

you can change and add
-movflags faststart

not sure if you have tried this to test, It use to work for reg CB
I have not tried it in this version but will experiment just thought I would throw it out here and see what you think

Spiro

**Comment by spirogg** [comment]
this is old file where you would add this 
![Capture](https://user-images.githubusercontent.com/17736688/84348158-e46d9200-ab79-11ea-970f-887d0762f781.PNG)
![Capture1](https://user-images.githubusercontent.com/17736688/84348160-e46d9200-ab79-11ea-9d1e-70b1c6ab4f18.PNG)

**Comment by spirogg** [comment]
new line i found only 1 # File
- 
![Capture](https://user-images.githubusercontent.com/17736688/84350231-8e4f1d80-ab7e-11ea-985f-7e27daf899cb.PNG)

**Comment by spirogg** [comment]
ok no errors seems to work ? what are your thoughts, if this is even still needed ?

**Comment by spirogg** [comment]
faststart for web video
-
You can add -movflags +faststart as an output option if your videos are going to be viewed in a browser. This will move some information to the beginning of your file and allow the video to begin playing before it is completely downloaded by the viewer. It is not required if you are going to use a video service such as YouTube.

EXAMPLE OF CONVERSION BELOW

`645.9kbits/s dup=0 drop=6 speed=0.901x frame= 186 fps= 24 q=28.0 size= 541kB time=00:00:07.17 bitrate= 618.0kbits/s dup=0 drop=6 speed=0.912x [mp4 @ 0x23fd580] `Starting second pass: moving the moov atom to the beginning of the file frame= 194 fps= 23 `q=-1.0 Lsize= 564kB time=00:00:08.30 bitrate= 556.6kbits/s dup=0 drop=7 speed=0.964x video:561kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.533687%`

**Comment by MacWarrior** [comment]
Hi,

After reading a bit of documentation about this flag, I don't see any issue adding it by default for all conversion ; I just don't really know what to expect as a difference before/after adding this flag...
Will do a few testing before pushing it to github 😄

Best regards,
MacWarrior.

**Comment by MacWarrior** [comment]
Hi,

I've been testing on a 720p ~5min video : same conversion time
So there's really no issue by adding this flag

But I'd like to see / understand the difference before/after adding this flag

As I understard, this should be necessary to allow video streaming... but it's already working correclty. So I'm asking if it's still relevant...

Best regards,
MacWarrior.

**Comment by MacWarrior** [comment]
Maybe this action is already done by mp4box and `-inter` command
Some doc to read : 
https://gpac.wp.imt.fr/tag/http-streaming/
https://manpages.debian.org/stretch/gpac/MP4Box.1.en.html

After reading a bit of these, I might think that faststart isn't really needed
Some more testing and reading are necessary

**Comment by spirogg** [comment]
In the latest version of ffmpeg (3.x+ or 4.x+), the correct syntax is -movflags faststart indeed (without the + sign). See: ffmpeg.org/ffmpeg-formats.html#Options-8 – Siu Ching Pong -Asuka Kenji- Dec 23 '18 at 14:59

**Comment by spirogg** [comment]
I just read this. Older ffmpeg was +faststart 
After 3.x and 4.x we need to remove + and just input: -movflags faststart 
Will give you link in 1 sec from where I was reading this.

**Comment by spirogg** [comment]
Here is the link 

https://superuser.com/questions/856025/any-downsides-to-always-using-the-movflags-faststart-parameter

**Comment by MacWarrior** [comment]
Hi,

I read the same link 😉
I'll test without the '+' but I'm questionning about the use of this flag because videos already start streaming very fast (with or without the flag) and this might be linked to the usage of mp4box which (if I correctly understand) split video in little chunks to allow fast streaming start

In all case, using the faststart don't seems to have any bad impact on the usage we have with ClipBucket

Best regards,
MacWarrior

**Comment by spirogg** [comment]
just fyi found this below :https://trac.ffmpeg.org/wiki/Encode/H.264

faststart for web video
You can add -movflags +faststart as an output option if your videos are going to be viewed in a browser. This will move some information to the beginning of your file and allow the video to begin playing before it is completely downloaded by the viewer. It is not required if you are going to use a video service such as YouTube.[ YouTube [​recommends](https://support.google.com/youtube/answer/1722171?hl=en) using faststart, so they can begin re-encoding before uploads complete.

Below are recommended upload encoding settings for your videos on YouTube. 

Container: MP4
No Edit Lists (or the video might not get processed correctly)
moov atom at the front of the file (Fast Start)

so maybe its worth adding ? 

just another area I read

**Comment by MacWarrior** [comment]
Hello @spirogg,

faststart has been added on last revision 😉

Best regards,
MacWarrior.
