### ISSUE TITLE
upload.php get error HTTP ERROR 500

### ISSUE THREAD

**Issue by anhthoai** [MacWarrior/clipbucket-v5#142]
Hello, I have just installed latest version  on fresh centos 7. All are working except upload.php. 
upload.php get error HTTP ERROR 500 but I see upload_photo.php is working well.
I don't see any error log. I share php version on my server. Do you have any idea for this issue?
php --version
PHP 7.3.19 (cli) (built: Jun  9 2020 08:06:30) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.19, Copyright (c) 1998-2018 Zend Technologies

**Comment by raiancollyn** [comment]
I am also facing the same problem, I believe it must be the version, I downloaded the project yesterday to test it, the photo sending part works without any problems, but the video part doesn't work, I just get an error 500

**Comment by MacWarrior** [comment]
Hi,
Thanks for report
Time is a bit hard to find here, but I'll try to check this asap !

Are both of you using CentOS 7 ?
Can you copy/paste the error (from php log files) ?

Best regards,
MacWarrior.

**Comment by MacWarrior** [comment]
Hi,

Finally this error was easy to fix : fixed in last commit

Best regards,
MacWarrior.
