### ISSUE TITLE
when upload photo and select collection after in form to save you have selector again ?

### ISSUE THREAD

**Issue by spirogg** [MacWarrior/clipbucket-v5#15]
When we create a collection or just upload a photo 
- we are asked to select a collection 
- then we upload photo
- then we have form to edit photo name, description, tags, etc 
in that form the drop down to select a collection should not be there - since we already selected a collection to upload photo in. ? 
![collection upload](https://user-images.githubusercontent.com/17736688/40589967-8a0de4c6-61bc-11e8-8697-1206b294a20b.PNG)
![collection upload2](https://user-images.githubusercontent.com/17736688/40589968-8a1b873e-61bc-11e8-8891-38122d0fe42a.PNG)
![collection upload3](https://user-images.githubusercontent.com/17736688/40589969-8a28e44c-61bc-11e8-9239-a6e6bcc970ce.PNG)
![collection upload4](https://user-images.githubusercontent.com/17736688/40589970-8a361658-61bc-11e8-9557-f6c57e6b72dc.PNG)

-
THANKS

**Comment by MacWarrior** [comment]
Hi,
This comportment must be because of a the use of not dedicaced interfaces
It's not perfect ergonomically, but it's not a bug
