### ISSUE TITLE
Cant upload file to ClipBucket "javascript:;"

### ISSUE THREAD

**Issue by Seecomp** [MacWarrior/clipbucket-v5#158]
I cant upload a file to my clipbucket which redirects me to javascript:; which does nothing.

**Comment by spirogg** [comment]
can you give us your server setup?
OS ?
php version?
database ?
how did you install CB was it with this CB V5did you see any errors in your log fil that can help someone help you :)

**Comment by Seecomp** [comment]
I fixed it. It was a cloudflare issue
