### ISSUE TITLE
Proxy setting

### ISSUE THREAD

**Issue by Norco06** [MacWarrior/clipbucket-v5#159]
Hi, 
I use a proxy, how to enter it in clipbucket ?

**Comment by MacWarrior** [comment]
Hi,

Can you give more details ? Because the use of a proxy don't impact ClipBucket 😞

Best regards,
MacWarrior.

**Comment by Norco06** [comment]
my server goes through a proxy for outgoing requests

**Comment by MacWarrior** [comment]
Hello,

Proxy settings have been implemented on last revision.
Until now, they are only use for update checker

Don't forget to apply SQL update for new configs 😄 

Best regards,
MacWarrior.
