### ISSUE TITLE
#1364 - Field "XX" doesn't have a default value

### ISSUE THREAD

**Issue by keisukelin** [MacWarrior/clipbucket-v5#161]
When using MySQL version grater than 5.0.2, could not add video categories and updating avatar,... etc.
I solved this by add 
> **$this->execute("SET @@sql_mode = ''");**

after Line 68 in upload/include/classes/db.class.php

But I am not sure this is safe or not.

**Comment by MacWarrior** [comment]
Hello @keisukelin,

Thanks for report, this is because of SQL strict mode and some errors in SQL structure.
Can you specify whitch field has this error ? I've made lot of fixes for this kind of error, but I may have missed some 😄

Thanks by advance,
Best regards,
MacWarrior.

**Comment by keisukelin** [comment]
Thanks for your reply.
I knew that not safe.
Because it`s too many field without default value when adding new category or other record.
My mysql version is 10.3.17-MariaDB.
It`s usually int and text field.
>video_category.category_thumb
collection_categories.category_order
collection_categories.category_thumb
playlists.description
playlists.tags
playlists.total_comments
playlists.total_items
playlists.rating
playlists.rated_by
playlists.voters
...

**Comment by MacWarrior** [comment]
Hello @keisukelin,

Thanks for reply... Ok, I missed a lot of them... ! But all fields doesn't absolutely requiered default values, it depends of the SQL used to insert datas.
Are you using latest release or latest revision ?

I'll fix this asap... I just really don't know when I'll have the time

Best regards,
MacWarrior.

**Comment by keisukelin** [comment]
Hi @MacWarrior 

Thanks a lot. 
Your Install script really help me a lot. 
I installed clipbuckets on CentOS Linux before.
But it cound not convert video successfully until using your install script on Ubuntu Linux. :)

Cause I use this to manage my  video and photo at my home, the website does not open on the internet.
I can set off strict mode to solve it temporary until you fix them.

Best regards,
Keisukelin.

**Comment by MacWarrior** [comment]
Hello @keisukelin,

I've updates DB tables specified : please check related commit to apply SQL manually (Or reinstall CBv5)

Best regards,
MacWarrior.
