### ISSUE TITLE
install script is buggy 

### ISSUE THREAD

**Issue by jdqw210** [MacWarrior/clipbucket-v5#163]
page_redir(); if( !$userquery->perm_check('view_videos',false, false, true) && !userid() ) { template_files('signup_or_login.html'); } else { template_files('index.html'); } display_it(); 

is all that's displayed in the browser

**Comment by MacWarrior** [comment]
Hello @jdqw210,

It seems like you have a problem to interprete php.
Which script did you used ; on which system ? Was it a clean install ?

Best regards,
MacWarrior.

**Comment by MacWarrior** [comment]
Hello @jdqw210,

Any news ?

Best regards,
MacWarrior.
