### ISSUE TITLE
after data import it redirects back to agreement

### ISSUE THREAD

**Issue by danekxd** [MacWarrior/clipbucket-v5#164]
when i install clipbucket and done the mysql connection it redirects me back to agreement and after getting error An SQL error occures : Table 'cb_09action_log' already exists

**Comment by MacWarrior** [comment]
Hello @danekxd,

It looks like you have already installer CB, and that's why you got this SQL error.
Can you give more informations about your setup ? OS + version, PHP version, ....

Thanks by advance,
Best regards,
MacWarrior.

**Comment by danekxd** [comment]
im using an web hosting service, php 7.4

**Comment by MacWarrior** [comment]
Hello @danekxd,

Thanks for reply, will try PHP 7.4 asap !

Best regards,
MacWarrior.

**Comment by MacWarrior** [comment]
Hello @danekxd,

Any news ?

Best regards,
MacWarrior.
