### ISSUE TITLE
Limit Upload

### ISSUE THREAD

**Issue by go-sudo** [MacWarrior/clipbucket-v5#165]
Hello

Installed clipbucket and ffmpeg latest version 4.3 everything works fine but the uload  is limited by the script because with other video CMS installed on the same server i can upload 4GO file 
the config of nginx and apache are all ok as i mentioned i can upload big files on other CMS

any idea please

Regards

**Comment by MacWarrior** [comment]
Hello @go-sudo,

Can you please check Admin area > General Configurations > Website Configurations > Upload & Conversion > Max upload file size ?

Best regards,
MacWarrior.

**Comment by MacWarrior** [comment]
Hello @go-sudo,

Any news ?

Best regards,
MacWarrior.
