### ISSUE TITLE
Nginx

### ISSUE THREAD

**Issue by niladrishekhar** [MacWarrior/clipbucket-v5#166]
Guys I have been banging my head for the last three days over installing one self hosted video cms 
Tried my hands at cumulusclips and phpvibe and the nginx file was killing me.
Thanks to you the whole installation of clipbucket took less than 10 minutes.

Lots of love, respect and admiration from my side. Thanks a ton guys specially for the whole coverage and not leaving out small details to be figured out NOOB's like me.

Thanks and appreciation.

**Comment by MacWarrior** [comment]
Hi @niladrishekhar,

Thanks for your message, that's the kind of issue I'm please to read ! 😄

Be welcome !

Best regards,
MacWarrior.
