### ISSUE TITLE
Add new video categorie 

### ISSUE THREAD

**Issue by dferraes** [MacWarrior/clipbucket-v5#167]
Hi,

Every time when i tried to create new video category this error is displayed:

    A technical error occurred !

    Category has been added successfully

No error in error_log, no error in any other place.

**Comment by dferraes** [comment]
![error_new](https://user-images.githubusercontent.com/50035363/119237610-5331ca00-bb03-11eb-84c4-61ec2ef51b93.png)

**Comment by dferraes** [comment]
Ubuntu 20.04
Server version: Apache/2.4.46 (Ubuntu)
PHP Version 7.0.33-50+ubuntu20.04.1+deb.sury.org+1

PHP Server Configuration Info - ClipBucket 5.4.1, DEV, REV 16

A brief view of PHP server configuration Info
configurations and values
POST MAX SIZE
  1152M
UPLOAD MAX FILESIZE
  1024M
MEMORY LIMIT
  1024M
MAX EXECUTION TIME
  7200

Modules and paths
FFMPEG
FFmpeg is used to covert videos from different versions to FLV , MP4 and many other formats. Learn more
Version 4.2.4
PHP CLI
PHP CLI is used to peform video conversion in a background process. Learn more
Version 7.4.1
Media Info
MediaInfo supplies technical and tag information about a video or audio file. Learn more
Version 19.09
MP4Box
MP4Box is a tool used to repair MP4 files to make them streamable Learn more
Version 0.5.2
FFProbe
ffprobe Is an Extension of ffmpeg used to get info of media file Learn more
Version 4.2.4-1ubuntu0.1

**Comment by MacWarrior** [comment]
Hello @dferraes,

Thanks for report !
- Is the category correctly created ?
- If not : what's the category name you specified ?

Even if it may not be related, you should check your config : you have two php versions : 7.4.18 (7.0.33 before your edit) & 7.4.1

Best regards,
MacWarrior.

**Comment by dferraes** [comment]
Hi,

I enabled the debug mode and now i can see the problem, when you create new video category if you don't upload a category_thumb you get this error:

    error SQL : INSERT INTO `c2clpbckt`.cb_video_categories (category_name,category_desc,date_added,parent_id) VALUES ('Aca','','2021-05-22 13:54:27','0')
    error ERROR : Field 'category_thumb' doesn't have a default value

![image](https://user-images.githubusercontent.com/50035363/119237986-73fb1f00-bb05-11eb-88d3-dd4e7acb3c2f.png)

In a new test, i tried to insert a category_thumb (exactly i dont know what kind of file the system expect) and the problem persist:

![Screenshot_20210522_135829](https://user-images.githubusercontent.com/50035363/119238049-cc322100-bb05-11eb-820d-85ee9f8754ee.png)

![Screenshot_20210522_135856](https://user-images.githubusercontent.com/50035363/119238056-db18d380-bb05-11eb-826e-5743837332e2.png)

To solve temporaly this problem, i changed the create table statement from:

CREATE TABLE `cb_video_categories` (
  `category_id` int(225) NOT NULL AUTO_INCREMENT,
  `parent_id` int(255) NOT NULL DEFAULT 0,
  `category_name` varchar(30) NOT NULL DEFAULT '',
  `category_order` int(5) NOT NULL DEFAULT 1,
  `category_desc` text NOT NULL,
  `date_added` mediumtext NOT NULL,
  `category_thumb` mediumtext NOT NULL,
  `isdefault` enum('yes','no') NOT NULL DEFAULT 'no',
  PRIMARY KEY (`category_id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8

To:

CREATE TABLE `cb_video_categories` (
  `category_id` int(225) NOT NULL AUTO_INCREMENT,
  `parent_id` int(255) NOT NULL DEFAULT 0,
  `category_name` varchar(30) NOT NULL DEFAULT '',
  `category_order` int(5) NOT NULL DEFAULT 1,
  `category_desc` text NOT NULL,
  `date_added` mediumtext NOT NULL,
  `category_thumb` mediumtext DEFAULT NULL,
  `isdefault` enum('yes','no') NOT NULL DEFAULT 'no',
  PRIMARY KEY (`category_id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8

Now the new category was created correctly:

![Screenshot_20210522_140340](https://user-images.githubusercontent.com/50035363/119238160-84f86000-bb06-11eb-90db-72f4aad90259.png)

If i can help whith something else please let me know.

Thanks in advance.

**Comment by MacWarrior** [comment]
Hello @dferraes, 

Many thanks for your investigations.
I'll commit a fix asap !

This is a common SQL error due to partial incompatibility with SQL strict mode ; I've already made lots of corrections about it but I haven't test all CB functionnalities
I tested on my test environment without SQL error ; is SQL strict mode OFF or did I already fixed this SQL table... Idk yet but I'll chek this asap too 😄 

Best regards,
MacWarrior.

**Comment by MacWarrior** [comment]
Hello @dferraes,

There was some errors in previous SQL files which has been fixed on last revision.
From your situation, 2 options : 
- New clean install of CB
- Apply all ALTER TABLES about DEFAULT values in [upgrade_5.4.0.sql](https://github.com/MacWarrior/clipbucket-v5/blob/master/upload/cb_install/sql/upgrade_5.4.0.sql) AND [upgrade_5.4.1.sql](https://github.com/MacWarrior/clipbucket-v5/blob/master/upload/cb_install/sql/upgrade_5.4.1.sql)

Thanks again for your report and investigations.
Best regards,
MacWarrior.
