### ISSUE TITLE
Add language 500 error

### ISSUE THREAD

**Issue by asycs** [MacWarrior/clipbucket-v5#168]
Hello

I used the install_ubuntu21.04.sh script.
The installation was absolutely flawless.
When I try to add a language, I get a 500 error.

/admin_area/ajaxLang.php

Thanks for the support.

Alex

**Comment by MacWarrior** [comment]
Hello asycs,

The way language is added never worked for me.
I will totally refactor languages management someday.... Just not my top 1 priority...
What language do you want to add ? I'll explain how to do so !

Best regards,
MacWarrior.

**Comment by saman-magnus** [comment]
how can i add persian or arabic languages , i make fa.lang file but i dont know how can i added to admin-area languages  setting ?

**Comment by MacWarrior** [comment]
Hello @saman-magnus,

Language management need a full refactor... It's not working propely from interfaces
- Copy en.lang or fr.lang to fa.lang
- In DB, create a new entry in {db_prefix}_languages : 
    language_id : whatever you want except existing ones
    language_code : fa
    language_name : Language title displayed on website
    language_regex : /^fa/i
    language_active : yes
    language_default : no
- Then on back office, change default language

Best regards,
MacWarrior.

**Comment by MacWarrior** [comment]
Hello @saman-magnus, @asycs,

This issue is quite old and since then, we have totally refactored languages management in ClipBucketV5.
Now everything is stored in database and is manageable from admin area interfaces.

Best regards,
MacWarrior.
