### ISSUE TITLE
Video Upload / "Submit Now" Error

### ISSUE THREAD

**Issue by asycs** [MacWarrior/clipbucket-v5#169]
Hi
When I upload a video in the frontend, it only works partially.
The upload shows 100%, but when I click on "Submit Now" the error appears as shown in the picture.
However, the video has been uploaded and is available.

![2021-06-23_085821](https://user-images.githubusercontent.com/84372177/123050748-51f50500-d401-11eb-8e1a-28a18d390369.png)

![2021-06-23_090401](https://user-images.githubusercontent.com/84372177/123051358-fc6d2800-d401-11eb-80d3-fac83d30cdff.png)

Thanks
Alex

**Comment by asycs** [comment]
![2021-06-23_111019](https://user-images.githubusercontent.com/84372177/123070005-abfec600-d413-11eb-98e4-aaae22cd3408.png)

**Comment by ekardian** [comment]
i saw that in the past, you can see your php.ini and growup the time and size of files.
other is the aspect, i saw the same problem when i was uploading videos without the 16:9 required, from your console watch the properties of your video with "mediainfo file.mp4 | grep -i aspect", i fixed uploading without recoding, but was a long long loooooong time ago xD

**Comment by MacWarrior** [comment]
Hello, 

@asycs 
Thanks for report, this is exactly what I'm working on, repairing this import requiere lots of work...
BUT ! The video is uploaded correctly, only video informations (title, description, ...) aren't saved : you can edit them from video editing
Can you check video conversion log about conversion fail ?

@ekardian
This issue isn't related with video ratio... I never had any issue with video ratio 😄 

Best regards,
MacWarrior.

**Comment by MacWarrior** [comment]
Hello, 

Looks like I needed a new issue about this to finally take time to finish my work... 😆
Last commit fixes and improves this interface

I found one last issue with multiple file upload (in that case, inputs fields are reset every time you add a new file) ; it's not perfect, but still better than before last commit 😉

Best regards,
MacWarrior.

**Comment by ekardian** [comment]
> 
> 
> Hello,
> 
> @asycs
> Thanks for report, this is exactly what I'm working on, repairing this import requiere lots of work...
> BUT ! The video is uploaded correctly, only video informations (title, description, ...) aren't saved : you can edit them from video editing
> Can you check video conversion log about conversion fail ?
> 
> @ekardian
> This issue isn't related with video ratio... I never had any issue with video ratio 😄
> 
> Best regards,
> MacWarrior.

i dont remember how? but i remember sometimes do not recoding my upload for the aspect radio, only the 16:9 was recoding, but i have my db from 2016 growing without recoding, just uploading, clipbucket its installed only in my internet for my own collection of trailers ... of course XD

**Comment by MacWarrior** [comment]
> i dont remember how? but i remember sometimes do not recoding my upload for the aspect radio, only the 16:9 was recoding, but i have my db from 2016 growing without recoding, just uploading, clipbucket its installed only in my internet for my own collection of trailers ... of course XD

Hello,

With a bit more of reflection, I've made changes a long time about video resolution handling.
With current version, system try to find a matching resolution reference by using video width or heigth ; per example : 
- 1920x500 will be considered as 1080p
- 500x1080 will be considered as 1080p also

There is also an option available to allow a little difference (1%) between expected width/heigth and current width/heigth ; with this option, 1900x500 will be considered as 1080p too

With this modification, any video ratio can be handled

Best regards,
MacWarrior.

**Comment by MacWarrior** [comment]
Hello @asycs,

Last commit fix last issue with multiple files upload

Best regards,
MacWarrior.
