### ISSUE TITLE
Is it working on PHP 7.4.x?

### ISSUE THREAD

**Issue by anhthoai** [MacWarrior/clipbucket-v5#170]
Hello, is it working on PHP 7.4.x? something is wrong when done installation

**Comment by ekardian** [comment]
offf cooors in the requirements they said yes

**Comment by MacWarrior** [comment]
Hello,

I'm using PHP 7.4.21 without any specific error
Can you share your php errors for more investigations ?

Best regards,
MacWarrior.

**Comment by MacWarrior** [comment]
Hello @anhthoai 

Any news ?
Still no specific issue with PHP 7.4.22 from my side

Best regards,
MacWarrior.

**Comment by ekardian** [comment]
> Hello @anhthoai
> 
> Any news ?
> Still no specific issue with PHP 7.4.22 from my side
> 
> Best regards,
> MacWarrior.

i am without time this week, but next sunday i gonna try again, chers

**Comment by MacWarrior** [comment]
Hello @ekardian 

Don't forget to use latest sources revision 👍 

Best regards,
MacWarrior.

**Comment by anhthoai** [comment]
Hello @ekardian, It is working now.
