### ISSUE TITLE
Video conversion failed 

### ISSUE THREAD

**Issue by Wrechid** [MacWarrior/clipbucket-v5#172]
Everything I upload fails... Tried mpg, mp4, and avi... 

Installed using, install_debian10.sh

Raw Conversion Log

==========================================
Pre-Check Configurations
==========================================

File to be converted
--------------------
Initializing File 16286535505f5f7.mp4 and pre checking configurations...

System hardware Information
---------------------------
H/W path Device Class Description
===========================================
system Computer
/0 bus Motherboard
/0/0 memory 8GiB System memory
/0/1 processor Intel(R) Xeon(R) CPU W5590 @ 3.33GHz
/0/100 bridge 440FX - 82441FX PMC [Natoma]
/0/100/1 bridge 82371SB PIIX3 ISA [Natoma/Triton II]
/0/100/1.1 storage 82371AB/EB/MB PIIX4 IDE
/0/100/2 display SVGA II Adapter
/0/100/3 enp0s3 network 82540EM Gigabit Ethernet Controller
/0/100/4 generic VirtualBox Guest Service
/0/100/5 multimedia 82801AA AC'97 Audio Controller
/0/100/7 bridge 82371AB/EB/MB PIIX4 ACPI
/0/100/d storage 82801HM/HEM (ICH8M/ICH8M-E) SATA Controller [AHCI mode]
/0/2 input PnP device PNP0303
/0/3 input PnP device PNP0f03

Temporary Uploading
-------------------
File Uploaded to Temp directory successfully and video conversion file is being executed !

Video Conversion File Execution
-------------------------------
Video Converson File executed successfully with Target File > !16286535505f5f7.mp4

==========================================
Starting Conversion Log
==========================================

Getting Arguments
-----------------
Filename : 16286535505f5f7.mp4
File directory : 2021/08/10
Log file : /var/www/html/files/logs/2021/08/10/16286535505f5f7.log

Conversion queue
----------------
Getting the file information from the queue for conversion

Conversion queue
----------------
File has been moved from temporary dir to Conversion Queue

Parsing FFmpeg Configurations
-----------------------------
use_video_rate : 1
use_video_bit_rate : 1
use_audio_rate : 1
use_audio_bit_rate : 1
use_audio_codec : 1
use_video_codec : 1
format : mp4
video_codec : libx264
audio_codec : libfdk_aac
audio_rate : 22050
audio_bitrate : 128000
video_rate : 25
video_bitrate : 300000
video_bitrate_hd : 4096000
normal_res : 480
high_res : 720
max_video_duration : 320
resize : max
outputPath : 2021/08/10/
cb_combo_res : no
gen_240 : yes
gen_360 : yes
gen_480 : yes
gen_720 : no
gen_1080 : no
chromecast_fix : 1
force_8bits : 1

Starting Conversion
-------------------
Started on 2021-08-10 23:45:56 - 2021 Aug 10

Checking File...
File : /var/www/html/files/conversion_queue/16286535505f5f7.mp4

File Exists
-----------
Yes

Preparing file...
-----------------
format : mov,mp4,m4a,3gp,3g2,mj2
duration : 54.71
size : 4511643
bitrate : 659777
video_width : 640
video_height : 360
video_wh_ratio : 1.7777777777778
video_codec : h264
video_rate : 29.97002997003
video_bitrate : 561134
video_color : N/A
audio_codec : aac
audio_bitrate : 95999
audio_rate : 44100
audio_channels : 2
bits_per_raw_sample : 8
path : /var/www/html/files/conversion_queue/16286535505f5f7.mp4
rotation : 0

Thumbs Generation
-----------------
Starting

Thumbs Files
------------

====== End : Thumbs Generation =======

Conversion Completed
--------------------

====== End : Thumbs Generation =======

Time Took : 6.9486 seconds

conversion_status : failed

**Comment by MacWarrior** [comment]
Hello, 

There was some issues with SD/HD video conversion which has been fixed in last commit
I've also fixed incomplete conversion logs

Please try again with latest revision

Best regards,
MacWarrior.
