### ISSUE TITLE
Cannot upload photos

### ISSUE THREAD

**Issue by Wrechid** [MacWarrior/clipbucket-v5#174]
Sorry to keep bothering you... :)

Rev 82

I've tried click and drag, file browse, single, mass, and different formats...

It gives me the progress bar for each photo 100%, but nothing is added when I navigate to different page...

Thanx again...

**Comment by Wrechid** [comment]
http://wrechid.com:8888
test123
test123

**Comment by MacWarrior** [comment]
Hello @Wrechid, 

> Sorry to keep bothering you... :)

Don't worry, it's fine ! 😄 

> I've tried click and drag, file browse, single, mass, and different formats...
> It gives me the progress bar for each photo 100%, but nothing is added when I navigate to different page...

I've been testing it lately and unfortunately it's totally broken for now, I made a [message on another issue](https://github.com/MacWarrior/clipbucket-v5/issues/37#issuecomment-894711958) a few days ago

It's in my top list of things to do and it might be done in the next days

Best regards,
MacWarrior.

**Comment by Wrechid** [comment]
Any progress...?
I've been trying to figure it out...

**Comment by MacWarrior** [comment]
Hello @Wrechid,

Last revision fix photo upload ; please don't forget to apply SQL update _(Or clean install)_
Photo upload refactoring isn't finished yet, still have issues with multiple photos upload

Best regards,
MacWarrior.

**Comment by Wrechid** [comment]
Very good, thank you... 

Please let me know if you get multi photos working...

**Comment by MacWarrior** [comment]
Hello @Wrechid,

Last revision fix multi photo upload and improve general photo upload experience.*
Don't forget to manually apply SQL update if you don't make a new clean install.

Best regards,
MacWarrior.
