### ISSUE TITLE
im getting the same problem

### ISSUE THREAD

**Issue by in4mation-hub** [MacWarrior/clipbucket-v5#175]
hi, im getting the same Invalid email choose a category error.

**Comment by MacWarrior** [comment]
Hello @in4mation-hub,
 
Can youe bring a bit more informations ?
- Revision used
- System
- PHP version
- Screenshot

Thanks by advance,
Best regards,
MacWarrior.

**Comment by in4mation-hub** [comment]
The php version is 7.0 
![image](https://user-images.githubusercontent.com/88946631/129476472-068387f0-a76c-4766-b25e-2498e4a94bcb.png)
idk what do u mean by revision or system. Please explain it a bit easier...

**Comment by MacWarrior** [comment]
Hello @in4mation-hub,

I just tested on PHP 7.0 without any specific error.

> idk what do u mean by revision or system. Please explain it a bit easier...

Revision : Clipbucket V5 revision is viewable in admin area : 
- Dashboard : Update statut > Current version : 5.4.X - Revision **XX** (Dev)

System : Which operating system are you using ? (Windows 10, Debian 10, Ubuntu 2021.04, .... )

Can you provide a full page screenshot ?
Do you have any PHP error ?
When loading page, do you have any error in browser console ?

Best regards,
MacWarrior.

**Comment by in4mation-hub** [comment]
Thanks for the info!
Ill turn back asap!

**Comment by in4mation-hub** [comment]
Cliipbucket Version: 4.1
PHP Version: 7.4.8
System: Microsoft Windows 10
![full pg](https://user-images.githubusercontent.com/88946631/130099674-042d4396-bf29-4ba3-9d86-4657ee318a25.png)
![Screenshot 2021-08-19 183755](https://user-images.githubusercontent.com/88946631/130099680-edd29c45-603e-4b45-9e78-9fc071f39570.png)
Also, where can i find PHP Errors?

**Comment by MacWarrior** [comment]
> Cliipbucket Version: 4.1

Hello @in4mation-hub 

Looks like you're not using this version of Clipbucket, but the outdated original.

Please make a new installation with Clipbucket V5 to get support here 😅 

Best regards,
MacWarrior.

**Comment by in4mation-hub** [comment]
Hi! To be honest, InfinityFree only lets me to download 4.1! How am i supposed to?

**Comment by MacWarrior** [comment]
Hi @in4mation-hub 

Seems like you'll have to manually install CBV5 ; download sources on your PC and upload them to your host
Basicaly, replace old 4.1 sources directory with 5.X

If you can, you can also message your host to propose them to switch to this repo instead of the old one which is not supported anymore

Best regards,
MacWarrior.

**Comment by in4mation-hub** [comment]
nah im fine ive taken down my site, thx for the good service tho 😃
