### ISSUE TITLE
RE: Cannot upload photo 

### ISSUE THREAD

**Issue by Wrechid** [MacWarrior/clipbucket-v5#177]
I was able to upload 1 photo, 
after you applied mass upload fix it doesn't let me upload any photos...  

I also did a fresh install just to make sure...

http://wrechid.com:8888
test123
test123

**Comment by MacWarrior** [comment]
Hello @Wrechid, 

You might have a PHP error when uploading photos ; can you check your PHP logs ?
What PHP version are you using ?

Best regards,
MacWarrior.

**Comment by MacWarrior** [comment]
Hello @Wrechid, 

Last commit fix this issue.
I've been a bit hard on code cleanup 😅 

Thanks for report

Best regards,
MacWarrior.

**Comment by Wrechid** [comment]
Hehe, thanx again... :)
