### ISSUE TITLE
Cannot upload photo 

### ISSUE THREAD

**Issue by Wrechid** [MacWarrior/clipbucket-v5#178]
I just tested with Rev 89, still cannot upload photos... 

I dropped the sql db and deleted the git folder before I did a fresh install downloading from git... 

I'm using same php from this morning when I was able to upload individual images... 

http://wrechid.com:8888 
test123 
test123

**Comment by MacWarrior** [comment]
Hello @Wrechid,

Thanks for report.
This time, no error from my side ; can you check your PHP logs ?

I'll try a clean install later today just to make sure... 😅

Best regards,
MacWarrior.

**Comment by Wrechid** [comment]
Good Morning @MacWarrior,

each time i upload a photo it present an error of cannot find file or directory...

`2021/08/19 03:17:36 [error] 605#605: *1338 open() "/srv/http/clipbucket/upload/files/photos/1629357455814aa2_m." failed (2: No such file or directory), client: 86.247.25.181, server: wrechid.com:8888, request: "GET /files/photos//1629357455814aa2_m. HTTP/1.1", host: "wrechid.com:8888", referrer: "http://wrechid.com:8888/photo_upload.php"
2021/08/19 07:52:23 [error] 605#605: *1470 open() "/srv/http/clipbucket/upload/files/photos/162937394390bc21_m." failed (2: No such file or directory), client: 192.168.2.1, server: wrechid.com:8888, request: "GET /files/photos//162937394390bc21_m. HTTP/1.1", host: "wrechid.com:8888", referrer: "http://wrechid.com:8888/photo_upload.php"
`

the photos are there but they are in numbered dirs according to the date... as for permissions, the dirs are 755, the images are 644...

**Comment by MacWarrior** [comment]
Hello @Wrechid,

Looks like it's the access log and not error log
Here it says the file doesn't exists which is true, but we have to look at errors during import and photos generation

If you want and have enough confidence in me, I can directly check on your server

Best regards,
MacWarrior.

**Comment by Wrechid** [comment]
i have to head out for work, do you use skype...?
[logs.zip](https://github.com/MacWarrior/clipbucket-v5/files/7014324/logs.zip)

**Comment by MacWarrior** [comment]
> i have to head out for work, do you use skype...?
> [logs.zip](https://github.com/MacWarrior/clipbucket-v5/files/7014324/logs.zip)

Skype : macwarrior94 
Discord : MacWarrior#8496

**Comment by MacWarrior** [comment]
Hello @Wrechid,

As seen together, a fix has been published 😄 

Best regards,
MacWarrior.

**Comment by Wrechid** [comment]
Issue fixed, thank you... :)
