### ISSUE TITLE
Installing CB v5 for first time and getting this message - An SQL error occures : Invalid default value for 'date_added'

### ISSUE THREAD

**Issue by TechBill** [MacWarrior/clipbucket-v5#182]
We have paid CB version and we are facing issue with it so we wanted to try the V5 out but the installer is giving this error message after entering the DB information 

An SQL error occures : Invalid default value for 'date_added'

Also, the installer said it cannot detect ffmpeg and ffprobe etc when we know it is installed on the server so we thought we would try to complete the installation and see if the path setting to those binary is correct in the admin area however we are unable to get past the DB installation point.

**Comment by MacWarrior** [comment]
Hello @TechBill,

Issues has been resolved 

Best regards,
MacWarrior.
