### ISSUE TITLE
fresh install sql error occures : Incorrect table definition; there can be only one auto column and it must be defined as a key

### ISSUE THREAD

**Issue by mohmafia** [MacWarrior/clipbucket-v5#184]
when trying to install CB5 i get this error:
Creating Database Tables and Importing data
An SQL error occures : Incorrect table definition; there can be only one auto column and it must be defined as a key
and then it is stuck on Creating database structure...

**Comment by MacWarrior** [comment]
Hello @mohmafia, 

Thanks for report !
I missed this one before commit.... fixed on last revision !

Best regards,
MacWarrior.
