### ISSUE TITLE
How do i mess with the sub & view count so i can make people explode?

### ISSUE THREAD

**Issue by in4mation-hub** [MacWarrior/clipbucket-v5#187]
How can i mess with the sub count or video views? Any help is highly appreciated

**Comment by MacWarrior** [comment]
Hello @in4mation-hub,

Video views and sub count aren't meant to be manually updated 😄

But this is totally possible :
- For video views, you can manually update field `views` in `video` table with wanted views count
- For sub count, you can manually update field `subscribers` in `users` table with wanted subscribers count

Best regards,
MacWarrior.

**Comment by in4mation-hub** [comment]
Ok thanks!

**Comment by Hwilliams8548** [comment]
Well no, Theoretically the sub count would reset when someone subs. This is because It would recalculate the sub count

**Comment by MacWarrior** [comment]
@Hwilliams8548 : You're totally right ! 😄

**Comment by in4mation-hub** [comment]
wait i think when u put the subs if someone subs it will increase by 1 so if u putted 10 k subs u would have 10,001 subs isn't that how it works?

**Comment by MacWarrior** [comment]
Views count don't recalculate each time, so you can cheat on count view
Sub count recount every sub each time someone sub or unsub, so you can't cheat on sub count (On temporary)
