### ISSUE TITLE
i cant install clipbucket on my site

### ISSUE THREAD

**Issue by in4mation-hub** [MacWarrior/clipbucket-v5#188]
i have uploaded the upload folder in the site but it doesn't work. Does clipbucket work on 000webhost?

**Comment by MacWarrior** [comment]
Hello @in4mation-hub,

You should at least can access to installation pages even if your host don't provide all dependancies
But here this is a hosting/configuration issue and I can't help you on this part 😄 

Best regards,
MacWarrior.

**Comment by in4mation-hub** [comment]
ok
