### ISSUE TITLE
Clipbucket

### ISSUE THREAD

**Issue by SOM5rf** [MacWarrior/clipbucket-v5#191]
Hello Just a little question where do we have to install the ffmpeg and the other modules cause I don't have them in my directory

**Comment by MacWarrior** [comment]
Hello @SOM5rf,

All softwares are to be installed on your system and aren't packaged inside Clipbucket
For linux OS, you can check installation scripts : 
https://github.com/MacWarrior/clipbucket-v5/tree/master/utils

Best regards,
MacWarrior.

**Comment by SOM5rf** [comment]
So I have to install it seperately but where do I put the module files plugins, ajax, api ?

**Comment by MacWarrior** [comment]
Hello @SOM5rf, 

CB sources has to be uploaded to the root directory you specified in your vhost
Looks like you need to be learn things about hosting 😄 

You should really consider learning how to host something before trying to use CB which requiere some specific knowledge

On local env, you may use easy installation script, depending of your hosting OS

Best regards,
MacWarrior.

**Comment by SOM5rf** [comment]
Thank you, Yes I juzt started this 2 weeks ago I am doing a school project. 
One more question do I have to download them or are they just extra tools

**Comment by MacWarrior** [comment]
`Required : MySQL 5.6+ / MariaDB 10.3+ ; PHP 7.0+ (+ modules : mysqli, curl, xml, mbstring, gd) ; FFmpeg 3+ ; mediainfo ; lshw ; sendmail
Optionnal : Git`

Installing manually requiered softwares is the "hard" way go install CB
If you don't know what you're doing, you should really consider using easy installation script (as long as you're using one of the supported OS 😉)

**Comment by SOM5rf** [comment]
Thank you for responding yes I am using one of the supported OS where can i find the easy installtion script

**Comment by MacWarrior** [comment]
Make a little effort 😅 

> https://github.com/MacWarrior/clipbucket-v5/tree/master/utils

**Comment by SOM5rf** [comment]
Ok I am using I will reply when finished

**Comment by SOM5rf** [comment]
Ok Thank you I did not work . I am not mad or anything I think I will use something else .Thank you for always having a supporting community.
