### ISSUE TITLE
Cant get to admin settings while installing.

### ISSUE THREAD

**Issue by taterlab** [MacWarrior/clipbucket-v5#192]
Hello, Tried to install clipbucket via installation scripts on ubuntu/debian apache/ngnix, without succes
after database creation i am redirected to first page of installation.

running server in vm, accessing site via vm's ip

**Comment by MacWarrior** [comment]
Hello, 

What error did you get during installation process ?

Thanks by advance,
Best regards,
MacWarrior.

**Comment by MacWarrior** [comment]
Hello @taterlab,

Issue fixed in last commit (20236ee51e1f36f8a34ff33e21c63b09ab06b677)

Best regards,
MacWarrior.
