### ISSUE TITLE
An SQL error occured : Invalid default value for 'datecreated'

### ISSUE THREAD

**Issue by rems25000** [MacWarrior/clipbucket-v5#198]
Hello,
I'm on a clean Ubuntu 18.04 build.
I used the script for Ubuntu 18.04, it ran smoothly.
Once on the page to import the database I have an error.

`
Creating Database Tables and Importing data

An SQL error occured : Invalid default value for 'datecreated'SQL : CREATE TABLE `cb_video` ( `videoid` bigint(20) NOT NULL, `videokey` mediumtext NOT NULL, `video_password` varchar(255) NOT NULL DEFAULT '', `video_users` text NOT NULL, `username` text NULL DEFAULT NULL, `userid` int(11) NULL DEFAULT NULL, `title` text DEFAULT NULL, `file_name` varchar(32) NOT NULL DEFAULT '', `file_type` int(10) NOT NULL DEFAULT 0, `file_directory` varchar(25) NOT NULL DEFAULT '', `description` text DEFAULT NULL, `tags` mediumtext NOT NULL, `category` VARCHAR(3) NULL DEFAULT NULL, `category_parents` text NULL DEFAULT NULL, `broadcast` varchar(10) NOT NULL DEFAULT '', `location` mediumtext DEFAULT NULL, `datecreated` date NOT NULL DEFAULT CURRENT_TIMESTAMP, `country` mediumtext DEFAULT NULL, `blocked_countries` text NULL DEFAULT NULL, `sprite_count` int(11) NOT NULL DEFAULT 0, `allow_embedding` char(3) NOT NULL DEFAULT '', `rating` int(15) NOT NULL DEFAULT 0, `rated_by` varchar(20) NOT NULL DEFAULT '0', `voter_ids` mediumtext NOT NULL, `allow_comments` char(3) NOT NULL DEFAULT '', `comment_voting` char(3) NOT NULL DEFAULT '', `comments_count` int(15) NOT NULL DEFAULT 0, `last_commented` datetime DEFAULT NULL, `featured` char(3) NOT NULL DEFAULT 'no', `featured_date` datetime DEFAULT NULL, `featured_description` mediumtext NOT NULL, `allow_rating` char(3) NOT NULL DEFAULT '', `active` char(3) NOT NULL DEFAULT '0', `favourite_count` varchar(15) NOT NULL DEFAULT '0', `playlist_count` varchar(15) NOT NULL DEFAULT '0', `views` bigint(22) NOT NULL DEFAULT 0, `last_viewed` datetime NOT NULL DEFAULT '1000-01-01 00:00:00' ON UPDATE CURRENT_TIMESTAMP, `date_added` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, `flagged` varchar(3) NOT NULL DEFAULT 'no', `duration` varchar(20) NOT NULL DEFAULT '00', `status` enum('Successful','Processing','Failed') NOT NULL DEFAULT 'Processing', `failed_reason` enum('none','max_duration','max_file','invalid_format','invalid_upload') NOT NULL DEFAULT 'none', `default_thumb` int(3) NOT NULL DEFAULT 1, `aspect_ratio` varchar(10) NOT NULL DEFAULT '', `embed_code` text NULL DEFAULT NULL, `refer_url` text NULL DEFAULT NULL, `downloads` bigint(255) NOT NULL DEFAULT 0, `uploader_ip` varchar(20) NOT NULL DEFAULT '', `unique_embed_code` varchar(50) NOT NULL DEFAULT '', `remote_play_url` text NULL DEFAULT NULL, `video_files` tinytext NULL DEFAULT NULL, `server_ip` varchar(20) NOT NULL DEFAULT '', `file_server_path` text NULL DEFAULT NULL, `files_thumbs_path` text NULL DEFAULT NULL, `process_status` bigint(30) NOT NULL DEFAULT 0, `video_version` varchar(30) NOT NULL DEFAULT '5.5.0', `thumbs_version` varchar(5) NOT NULL DEFAULT '5.5.0', `re_conv_status` tinytext NULL DEFAULT NULL, `is_castable` tinyint(1) NOT NULL DEFAULT 0, `bits_color` tinyint(4) DEFAULT NULL, `subscription_email` enum('pending','sent') NOT NULL DEFAULT 'pending' ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
loading Creating database structure... `

impossible to go further in the installation process.
Help me :/

**Comment by MacWarrior** [comment]
Hi @rems25000,

Thanks for report ; I'll fix this asap ! (Tonight or tomorrow 😉)

Best regards,
MacWarrior.

**Comment by rems25000** [comment]
Hi MacWarrior,
How nice.
I wouldn't hesitate to tell you about any bugs I encounter.
Thank you.

**Comment by rems25000** [comment]
`datecreated` date NOT NULL DEFAULT CURRENT_TIMESTAMP,
TO
  `datecreated` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,

PASS

**Comment by Hwilliams8548** [comment]
I was having this same problems! I hope it gets fixed.

**Comment by rems25000** [comment]
Once the installation is done and a test video uploaded.
nothing more happens.

video log:

[16422703854aa57.log](https://github.com/MacWarrior/clipbucket-v5/files/7875620/16422703854aa57.log)

**Comment by MacWarrior** [comment]
@Hwilliams8548, @rems25000 : Which version of MySQL/MariaDB are you using ?

@rems25000 : You should have a PHP error, can you : 
- Enable development mode by creating a blank file  : /files/temp/development.dev
OR
- From admin area, menu Tool Box > Development Mode : Enable Development Mode

Then retry to import file and check for PHP errors

Best regards,
MacWarrior.

**Comment by Hwilliams8548** [comment]
@MacWarrior I am not home right now but when I get home I will check

**Comment by rems25000** [comment]
mysql  Ver 15.1 Distrib 10.1.48-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**Comment by rems25000** [comment]
I have no errors PHP in développer mode. 
Upload OK
the video is stored in files/conversion_queue
A log file is generated without error and without the start of conversion.
The video is displayed on the main page of the site but does not played

**Comment by rems25000** [comment]
in error.log:
PHP Parse error:  syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in /var/www/clipbucket/upload/includes/classes/conversion/ffmpeg.class.php on line 5

**Comment by MacWarrior** [comment]
"Required : MySQL 5.6+ / MariaDB 10.3+"

I've tested newer versions but It's been a long time since à tried old ones !

**Comment by MacWarrior** [comment]
What is your PHP version ?

**Comment by rems25000** [comment]
PHP 7.2.24-0ubuntu0.18.04.10 (cli) (built: Oct 25 2021 17:47:59) ( NTS )

**Comment by MacWarrior** [comment]
> in error.log: PHP Parse error: syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in /var/www/clipbucket/upload/includes/classes/conversion/ffmpeg.class.php on line 5

Ok, I have this one....
Latest edits I made on ffmpeg require PHP 7.4+... Fix will come in minutes...

**Comment by MacWarrior** [comment]
PHP error is now fixed with last commit
But you should really consider upgrading your PHP version to 7.4 at least
Cf. PHP Supported version : https://www.php.net/supported-versions.php

**Comment by rems25000** [comment]
in script:
apt-get install php7.2 apache2 mariadb-server php-curl ffmpeg php7.2-mysql php7.2-xml php7.2-mbstring php7.2-gd sendmail mediainfo --yes > /dev/null 2>&1

**Comment by MacWarrior** [comment]
> in script: apt-get install php7.2 apache2 mariadb-server php-curl ffmpeg php7.2-mysql php7.2-xml php7.2-mbstring php7.2-gd sendmail mediainfo --yes > /dev/null 2>&1

PHP 7.2 is the default version available with Ubundu 18.04
And for now, I want CB5 compatible with PHP 7.0+ so the PHP error you met was on me 😄
In all cases, you should consider upgrading your PHP version to a supported one (By PHP themself) before going live

Current dev version (5.5.0) will stay compatible with PHP 7.0-7.3 but I think I will update PHP minimum version to 7.4 with version 5.6 and then will stay correlated with PHP supported version
In this situation, I'll update installation script

But for now, let's focus on the SQL error... I should have some old Ubuntu 18.04 VM somewhere...

**Comment by rems25000** [comment]
currently :
PHP 7.4.27 (cli) (built: Dec 20 2021 21:27:56) ( NTS )
Server version: 10.3.32-MariaDB-1:10.3.32+maria~bionic mariadb.org binary distribution
I put the installation folder and I start from zero.

**Comment by rems25000** [comment]
Creating database structure... PASS!

**Comment by rems25000** [comment]
but after importing the video no conversion

**Comment by MacWarrior** [comment]
Did you updated to last revision ?
Re-check for php errors ?

**Comment by rems25000** [comment]
the video stays in temp and does not go to the convert folder.

**Comment by rems25000** [comment]
` thrown in /var/www/clipbucket/upload/includes/classes/db.class.php on line 64
PHP Fatal error:  Uncaught Error: Class 'mysqli' not found in /var/www/clipbucket/upload/includes/classes/db.class.php:64
Stack trace:
#0 /var/www/clipbucket/upload/includes/config.php(16): Clipbucket_db->connect()
#1 /var/www/clipbucket/upload/includes/common.php(54): require_once('/var/www/clipbu...')
#2 /var/www/clipbucket/upload/includes/config.inc.php(9): require_once('/var/www/clipbu...')
#3 /var/www/clipbucket/upload/actions/video_convert.php(6): include('/var/www/clipbu...')
#4 {main}
  thrown in /var/www/clipbucket/upload/includes/classes/db.class.php on line 64
`

**Comment by MacWarrior** [comment]
You are missing PHP libraries : 

`apt install php7.4-mysql php7.4-xml php7.4-mbstring php7.4-gd`

**Comment by rems25000** [comment]
it works....

**Comment by rems25000** [comment]
But, conversion finished, it's the video that asks to wait.

**Comment by MacWarrior** [comment]
Can you provide logs or screenshots ?

**Comment by rems25000** [comment]
submit button now don't redirect. just validation message.
[1642286319d77d4.log](https://github.com/MacWarrior/clipbucket-v5/files/7876028/1642286319d77d4.log)
![image](https://user-images.githubusercontent.com/97801362/149640022-d26d231f-60c7-4c01-8458-690a55b2c59c.png)

**Comment by MacWarrior** [comment]
Video conversion seems to have failed ; can you check conversion log ?

**Comment by rems25000** [comment]
in my previous comment the .log file
if there is another log please tell me the path.

**Comment by MacWarrior** [comment]
Conversion log from 4h ago was generated with a PHP error I fixed since ; you have to re-upload your video to make a new import test

Conversion log is also available from admin area > Videos > Videos manager : your video

**Comment by rems25000** [comment]
Raw Conversion Log


==========================================
Pre-Check Configurations
==========================================

File to be converted
--------------------
Initializing File 1642291238bd6b1.mp4 and pre checking configurations...

Temporary Uploading
-------------------
File Uploaded to Temp directory successfully and video conversion file is being executed !

Video Conversion File Execution
-------------------------------
Video Converson File executed successfully with Target File > !1642291238bd6b1.mp4


==========================================
Starting Conversion Log
==========================================

Getting Arguments
-----------------
Filename : 1642291238bd6b1.mp4
File directory : 2022/01/16
Log file : /var/www/clipbucket/upload/files/logs/2022/01/16/1642291238bd6b1.log


Conversion queue
----------------
Getting the file information from the queue for conversion

Conversion queue
----------------
File has been moved from temporary dir to Conversion Queue

Starting Conversion
-------------------
Started on 2022-01-16 00:00:43 - 2022 Jan 16

Checking File...
File : /var/www/clipbucket/upload/files/conversion_queue/1642291238bd6b1.mp4

Preparing file...
-----------------
video_wh_ratio : 1.7777777777778
video_color : N/A
path : /var/www/clipbucket/upload/files/conversion_queue/1642291238bd6b1.mp4
format : mov,mp4,m4a,3gp,3g2,mj2
duration : 62.28
bitrate : 1347820
video_bitrate : 959963
video_width : 1280
video_height : 720
bits_per_raw_sample : 8
video_codec : h264
video_rate : 25
size : 10498677
audio_codec : aac
audio_bitrate : 383727
audio_rate : 48000
audio_channels : 6
rotation : 0


Thumbs Generation
-----------------

====== End : Thumbs Generation =======


Conversion Ouput
----------------
Converting Video file 240 @ 2022-01-16 00:00:52

Files resolution : 240


== Conversion Command ==

/usr/local/bin/ffmpeg -i /var/www/clipbucket/upload/files/conversion_queue/1642291238bd6b1.mp4 -y -hide_banner -vcodec libx264 -preset medium -r 25 -pix_fmt yuv420p -max_muxing_queue_size 1024 -start_at_zero -vb 240000 -s 428x240 -aspect 16/9 -b:a 128000 -ar 22050 -c:a aac -profile:a aac_low -ac 2 -map 0:0 -map 0:1 -c:s mov_text -f mp4 -movflags faststart /var/www/clipbucket/upload/files/videos/2022/01/16/1642291238bd6b1-240.mp4 2> /var/www/clipbucket/upload/files/temp/1642291252deb17.tmp
End resolutions @ 2022-01-16 00:01:00



OutPut Details
--------------
video_wh_ratio : 1.7833333333333
video_color : N/A
path : /var/www/clipbucket/upload/files/videos/2022/01/16/1642291238bd6b1-240.mp4
format : mov,mp4,m4a,3gp,3g2,mj2
duration : 62.28
bitrate : 361143
video_bitrate : 227579
video_width : 428
video_height : 240
bits_per_raw_sample : 8
video_codec : h264
video_rate : 25
size : 2815202
audio_codec : aac
audio_bitrate : 128867
audio_rate : 22050
audio_channels : 2
rotation : 0


Conversion Ouput
----------------
Converting Video file 360 @ 2022-01-16 00:01:00

Files resolution : 360


== Conversion Command ==

/usr/local/bin/ffmpeg -i /var/www/clipbucket/upload/files/conversion_queue/1642291238bd6b1.mp4 -y -hide_banner -vcodec libx264 -preset medium -r 25 -pix_fmt yuv420p -max_muxing_queue_size 1024 -start_at_zero -vb 400000 -s 640x360 -aspect 16/9 -b:a 128000 -ar 22050 -c:a aac -profile:a aac_low -ac 2 -map 0:0 -map 0:1 -c:s mov_text -f mp4 -movflags faststart /var/www/clipbucket/upload/files/videos/2022/01/16/1642291238bd6b1-360.mp4 2> /var/www/clipbucket/upload/files/temp/164229126013125.tmp
End resolutions @ 2022-01-16 00:01:12



OutPut Details
--------------
video_wh_ratio : 1.7777777777778
video_color : N/A
path : /var/www/clipbucket/upload/files/videos/2022/01/16/1642291238bd6b1-360.mp4
format : mov,mp4,m4a,3gp,3g2,mj2
duration : 62.28
bitrate : 511535
video_bitrate : 378235
video_width : 640
video_height : 360
bits_per_raw_sample : 8
video_codec : h264
video_rate : 25
size : 3987549
audio_codec : aac
audio_bitrate : 128867
audio_rate : 22050
audio_channels : 2
rotation : 0


Conversion Ouput
----------------
Converting Video file 480 @ 2022-01-16 00:01:13

Files resolution : 480


== Conversion Command ==

/usr/local/bin/ffmpeg -i /var/www/clipbucket/upload/files/conversion_queue/1642291238bd6b1.mp4 -y -hide_banner -vcodec libx264 -preset medium -r 25 -pix_fmt yuv420p -max_muxing_queue_size 1024 -start_at_zero -vb 700000 -s 854x480 -aspect 16/9 -b:a 128000 -ar 22050 -c:a aac -profile:a aac_low -ac 2 -map 0:0 -map 0:1 -c:s mov_text -f mp4 -movflags faststart /var/www/clipbucket/upload/files/videos/2022/01/16/1642291238bd6b1-480.mp4 2> /var/www/clipbucket/upload/files/temp/16422912739522a.tmp
End resolutions @ 2022-01-16 00:01:31



OutPut Details
--------------
video_wh_ratio : 1.7791666666667
video_color : N/A
path : /var/www/clipbucket/upload/files/videos/2022/01/16/1642291238bd6b1-480.mp4
format : mov,mp4,m4a,3gp,3g2,mj2
duration : 62.28
bitrate : 795379
video_bitrate : 662255
video_width : 854
video_height : 480
bits_per_raw_sample : 8
video_codec : h264
video_rate : 25
size : 6200182
audio_codec : aac
audio_bitrate : 128867
audio_rate : 22050
audio_channels : 2
rotation : 0


Conversion Ouput
----------------
Converting Video file 720 @ 2022-01-16 00:01:32

Files resolution : 720


== Conversion Command ==

/usr/local/bin/ffmpeg -i /var/www/clipbucket/upload/files/conversion_queue/1642291238bd6b1.mp4 -y -hide_banner -vcodec libx264 -preset medium -r 25 -pix_fmt yuv420p -max_muxing_queue_size 1024 -start_at_zero -vb 2500000 -s 1280x720 -aspect 16/9 -b:a 128000 -ar 22050 -c:a aac -profile:a aac_low -ac 2 -map 0:0 -map 0:1 -c:s mov_text -f mp4 -movflags faststart /var/www/clipbucket/upload/files/videos/2022/01/16/1642291238bd6b1-720.mp4 2> /var/www/clipbucket/upload/files/temp/16422912924e0e3.tmp
End resolutions @ 2022-01-16 00:02:08



OutPut Details
--------------
video_wh_ratio : 1.7777777777778
video_color : N/A
path : /var/www/clipbucket/upload/files/videos/2022/01/16/1642291238bd6b1-720.mp4
format : mov,mp4,m4a,3gp,3g2,mj2
duration : 62.28
bitrate : 2465734
video_bitrate : 2335194
video_width : 1280
video_height : 720
bits_per_raw_sample : 8
video_codec : h264
video_rate : 25
size : 19221016
audio_codec : aac
audio_bitrate : 128867
audio_rate : 22050
audio_channels : 2
rotation : 0


Conversion Completed
--------------------
Time Took : 84.8525 seconds
Conversion_status : completed

**Comment by MacWarrior** [comment]
> Conversion_status : completed

And everything looks fine, video should be playing well...

**Comment by rems25000** [comment]
no, the player systematically displays the black video.

**Comment by MacWarrior** [comment]
Even from admin area player ?

**Comment by rems25000** [comment]
![image](https://user-images.githubusercontent.com/97801362/149640519-5ab5333d-9e74-4e66-8281-ab94423aaae3.png)
![image](https://user-images.githubusercontent.com/97801362/149640541-4059d2ce-f540-471b-a836-7e3e9935036c.png)

**Comment by MacWarrior** [comment]
Je parlais plutôt de la page d'édition de la vidéo qui propose également un player
Le sous-menu visionner redirige vers la page du front office

Il semble également y avoir un soucis avec le type de vidéo ; peux-tu vérifier dans la configuration (General > Website Configurations > Conversion si le format MP4 est bien sélectionné ?
![image](https://user-images.githubusercontent.com/200590/149640618-acf5f743-1fa5-4c76-a31c-8ac990fe823a.png)

**Comment by rems25000** [comment]
la config actuelle:
![image](https://user-images.githubusercontent.com/97801362/149640697-5e859650-d69a-4764-bc8d-3e96e485aa67.png)
je ne trouve pas de page qui permet de visionner autrement que avec watch_video.php

**Comment by MacWarrior** [comment]
Via le sous-menu Editer : 

![image](https://user-images.githubusercontent.com/200590/149640751-b945f87a-7c89-455b-8649-3afd6d0d0159.png)

Ou directement en cliquant sur le titre de la vidéo depuis l'espace d'administration

**Comment by MacWarrior** [comment]
Ce qui n'est pas normal, c'est le "0" affiché sur les vidéos : 

![image](https://user-images.githubusercontent.com/200590/149640781-a0807bad-d255-4618-8a26-8b6d494786b6.png)

Il devrait afficher "MP4" ou "HLS" selon le type de conversion sélectionné

**Comment by rems25000** [comment]
![image](https://user-images.githubusercontent.com/97801362/149640784-15dc58ad-40ea-4497-8998-c03babcb1ece.png)

**Comment by rems25000** [comment]
![image](https://user-images.githubusercontent.com/97801362/149640839-11b8b5e4-274d-47e2-a11b-ba20138baf09.png)

**Comment by MacWarrior** [comment]
Je confirme que le soucis viens du champ file_type de la table video qui doit contenir "0" au lieu de "MP4"

J'investigue sur le sujet, mais ne pourrai probablement pas corriger ce soir !

**Comment by rems25000** [comment]
si je modifier directement en sql j'ai sa:
Incorrect integer value: 'MP4' for column `clipbucket`.`cb_video`.`file_type` at row 1
si je met 1 sa ne fonctionne pas.

**Comment by rems25000** [comment]
la case ne prend que des nombres.

**Comment by MacWarrior** [comment]
Ok, j'ai trouvé !
La colonne file_type n'a pas le bon type lors de la création ; je corrige !

```
ALTER TABLE `{tbl_prefix}video`
	MODIFY COLUMN `file_type` VARCHAR(3) NULL DEFAULT NULL;
```

En remplaçant le préfixe de la table, cette requête mettra à jour la structure de la table qui pose problème

**Comment by rems25000** [comment]
![image](https://user-images.githubusercontent.com/97801362/149654131-7b7e7e38-d55d-48b0-bb1c-f9c2e8a6f7d3.png)

**Comment by rems25000** [comment]
maintenant au moment de faire "bubmit now" j'ai Video does not exist

**Comment by MacWarrior** [comment]
Pas de soucis de mon côté ; une erreur PHP ?

**Comment by rems25000** [comment]
non erreur chaise, clavier. :)

**Comment by rems25000** [comment]
![image](https://user-images.githubusercontent.com/97801362/149654529-dd87b49b-59d3-403e-a355-145c8d0060ba.png)

**Comment by rems25000** [comment]
dernière question,^^ si je veut par exemple exporter en masse la bibliothèque d'un logiciel qui commence par un P et finir par un X.  sans convertir les vidéo car je le nas est déjà bien full.
et t'il possible que le lecteur lise des format comme MKV ou AVI sans conversion préalable?

**Comment by MacWarrior** [comment]
Pour le logiciel, désolé, mais j'arrive pas à lire entre les lignes 😅 

Les navigateurs ne sont pas en mesure de lire des MKV / AVI, il n'y a que peu de formats compatibles et c'est le mp4 avec encodage x264 qui est le plus compatible : la conversion est donc inévitable

**Comment by rems25000** [comment]
il n'y a pas de module pour transcoder des vidéo  que le laisse sur un lecteur maper? 
Mon problème c'est que je dois convertir toute les vidéos (en masse). et t'il pas possible inventorier dans le logiciel les vidéos et qu’il les transcodes au fur et a mesure de la demande?

**Comment by MacWarrior** [comment]
A ce niveau, nous sommes à peu près dans la même situation 😅 

Remplace le dossier /files/mass_uploads par un lien symbolique vers le dossier contenant toutes les vidéos
Ensuite côté interface admin : Vidéos > Mass Upload Videos
=> Toutes les vidéos seront listées et il sera possible de les importer, plusieurs à la fois

**Comment by rems25000** [comment]
J'ai pensé a sa; seulement je vais passer de quelque terra a plusieurs terra car stockage en dur et non conversion en flux tentu en temporaire.

**Comment by MacWarrior** [comment]
Malheureusement pas de solution miracle ; j'en suis à un peu plus de 6To de mon côté ; et j'ai simplement... acheté un nas plus gros
La conversion est un procédé très lent, suivant le CPU à coup de 5-6 films de 1h30/2h par jour

Quel est le besoin "réel" derrière l'utilisation de CB ?
De mon côté, j'utilise CB pour permettre le stream via internet simplement, mais j'utilise KODI/Videostation pour lire les vidéos sur ma TV

**Comment by rems25000** [comment]
Je cherche a faire c'est:
1) garder les vidéo sur le NAS au chaud.  
2) les inventorier dans le logiciel CB
3) que le logiciel ne reconvertisse pas tout les qualité mais convertisse en temps réel au besoin.
4) une fois la session de lecture fini il surprime la vidéo temporaire. 
5) pour la conversion tkt pas je peu convertir 22GO de 4K en quelque minute et on a pas besoin de l’intégralité de la vidéo dais la première seconde.

**Comment by rems25000** [comment]
Sur PLEX il transcode au fur est mesure un seul fichier pour toutes les qualités à la demande mais c'est privé et non public...
![image](https://user-images.githubusercontent.com/97801362/149655308-35f432ee-e835-41f3-9cc6-434b9452cc53.png)

**Comment by rems25000** [comment]
viens sur mon chat privé https://chat.remiserv.fr (accès invité possible) si tu veut pour discuter et pas flood le forum :)

**Comment by rems25000** [comment]
Hello, j'ai un bug de backoffice. ta le temps de venir sur le chat ?

**Comment by rems25000** [comment]
@MacWarrior j'ai mis a jour avec git. une fois ue je vide mon cache j'ai une page vide ou un message "
    ATTENTION: LE SITE EST EN MODE HORS LIGNE
    alors qui c'est bien en mode en ligne sur le backoffice. tu peu regarder vite fait avec moi?

**Comment by MacWarrior** [comment]
@rems25000 Comment as-tu mis à jour ? Téléchargement du ZIP + remplacer les sources ?
Ou Git pull dans le dossier source ?

Vérifie que le fichier /upload/files/temp/install.me n'existe PAS

**Comment by rems25000** [comment]
GG :)

**Comment by rems25000** [comment]
'ai un bug bizard j'ai une vidéo qui se lit bien, mais c'est l'image Thumb qui reste en permanence on entend le son. sur une seul vidéo.

**Comment by rems25000** [comment]
et j'ai toujours "error Une erreur technique est survenue ! " quand je veut créer une catégorie de vidéo

**Comment by MacWarrior** [comment]
> 'ai un bug bizard j'ai une vidéo qui se lit bien, mais c'est l'image Thumb qui reste en permanence on entend le son. sur une seul vidéo.

Chaque incident sur un ticket différent ; j'ai eu ce soucis sur certaines conversion HLS ; est-tu bien en MP4 ?
Sur une nouvelle conversion après upload ?

> et j'ai toujours "error Une erreur technique est survenue ! " quand je veut créer une catégorie de vidéo
Chaque incident sur un ticket différent aussi ; avec la dernière révision ?
Peux-tu activer le mode dev en créant le fichier /upload/files/temp/development.dev et ré-essayer pour avoir la requête SQL en erreur ?

**Comment by rems25000** [comment]
au pire viens sur le chat on regarde sa ?

**Comment by MacWarrior** [comment]
Connecte-toi donc au discord ; c'est plus pratique pour moi

**Comment by MacWarrior** [comment]
Bonjour @rems25000, 

La problématique à l'origine du ticket ayant été résolue, je clos le ticket 😉 

Cordialement,
MacWarrior.

---------------------

Hi @rems25000,

Original issue has been resolved, so I close this issue 😉 

Best regards,
MacWarrior.
