### ISSUE TITLE
Refactor languages/translations

### ISSUE THREAD

**Issue by MacWarrior** [MacWarrior/clipbucket-v5#201]
Languages management is currently not working properly : 
- Can't create new language
- Can't edit translations from admin area

Refactoring languages management will consist in : 
- Store translations in DB
- Create new language by copying translations from another one
- Add new interface to edit translations from admin area
- Remove *.lang files

**Comment by saman-magnus** [comment]
hi MavWarrior i do it from ur way

    Copy en.lang or fr.lang to fa.lang
    In DB, create a new entry in {db_prefix}_languages :
    language_id : whatever you want except existing ones
    language_code : fa
    language_name : Language title displayed on website
    language_regex : /^fa/i
    language_active : yes
    language_default : no
    Then on back office, change default language
this working no any issue's , only hard think : have to translate from English to Persian ;) more than 2000 words 
![backlang](https://user-images.githubusercontent.com/41460065/150341329-0d4f7fee-d84b-4b29-a995-148b1f670b69.png)

**Comment by MacWarrior** [comment]
Hello @saman-magnus,

There used to be an "auto-translate" system, but it's not working since a long time and was based on a trial subscription to a microsoft service (which required credit card and personnal informations validation)
Once I've refactored translation system, I'll probably look into implementing Google Translate API

But for now, I'm doing exactly what you're doing : translating key by key 😅 

Best regards,
MacWarrior.
