### ISSUE TITLE
In case you forget to select a category in mass uploid videos. fatal error

### ISSUE THREAD

**Issue by rems25000** [MacWarrior/clipbucket-v5#205]
admin_area/mass_uploader.php

In case you forget to select a category in mass uploid videos.

![image](https://user-images.githubusercontent.com/97801362/150431933-a16f74e3-ac7e-4f8a-9ad8-7789444b6119.png)

**Comment by MacWarrior** [comment]
Bonjour @rems25000, 

L'impression d'écran n'est pas la bonne, mais un correctif a été poussé

Cordialement,
MacWarrior.

===========

Hello @rems25000, 

Screenshot is not the right one, but I pushed a fix.

Best regards,
MacWarrior.
