### ISSUE TITLE
Manage Categories collections -> Add new category error.

### ISSUE THREAD

**Issue by rems25000** [MacWarrior/clipbucket-v5#206]
![image](https://user-images.githubusercontent.com/97801362/150431239-95343d35-1e5a-4b98-9376-79fe373c593f.png)

**Comment by MacWarrior** [comment]
Bonjour @rems25000,

Je viens de pousser un correctif ; une mise à jour SQL est nécessaire.

Cordialement,
MacWarrior.

========

Hello @rems25000,

I just pushed a fix ; an SQL update is required.

Best regards,
MacWarrior.
