### ISSUE TITLE
auto Resolution HLS quality

### ISSUE THREAD

**Issue by saman-magnus** [MacWarrior/clipbucket-v5#214]
hi  MacWarrior  , this only a idea , if u can plz fix auto Resolution for HLS format's in video-js

in JS file >>> 

`var options = {
  width: 640,
  height: 360,
  plugins: {
    videoJsResolutionSwitcher: {
      default: 480,
      dynamicLabel: true
    }
  }
}

var player = videojs('content_video', options);

player.on(['loadstart', 'play', 'playing', 'firstplay', 'pause', 'ended', 'adplay', 'adplaying', 'adfirstplay', 'adpause', 'adended', 'contentplay', 'contentplaying', 'contentfirstplay', 'contentpause', 'contentended', 'contentupdate', 'loadeddata', 'loadedmetadata'], function(e) {
  console.warn('VIDEOJS player event: ',  e.type);
});`

in HTML file >>>

`<video id="content_video" class="video-js vjs-default-skin"
       controls
       preload="none"
       autoplay
       loop
       muted
       width="640" height="360">`

Thank You

**Comment by MacWarrior** [comment]
Hello @saman-magnus, 

Be carefull with HLS conversion as it is still in progress and my latests advancements on this subject might suggest big changes

Can you describe your issue ?
In my tests, video resolutions worked fine and as I understand HLS, auto resolution implies specific instructions inside m3u8 file and not in videojs instructions

Best regards,
MacWarrior.

**Comment by saman-magnus** [comment]
hello  MacWarrior
@ Templates And Players > Player setting > Default video resolution> dont have auto resolution ! so whats after (for example : if i select the 480px default  player playing 480 resolution , so i try this one at any internet speed's all of them playing 480 Px , but this should be change when user have slow internet speed ! )
Thank you

**Comment by MacWarrior** [comment]
Hello @saman-magnus,

"Auto resolution" is a new feature comming with fully integrated HLS ; it's not a bug 😅 
Current HLS implementation isn't compatible with subtitles, multiple audio tracks and multiple resolutions

As I said, it's still in progress and require lots of work

Best regards,
MacWarrior.
