### ISSUE TITLE
how do i install on 000webhost

### ISSUE THREAD

**Issue by in4mation-hub** [MacWarrior/clipbucket-v5#218]

**Comment by MacWarrior** [comment]
Hello @in4mation-hub,

No description ? What is your issue ?
CB require ffmpeg, if you can't install ffmpeg, then you can't use ffmpeg.

Best regards,
MacWarrior.

**Comment by in4mation-hub** [comment]
could you please tell me how to install FFMpeg?

**Comment by in4mation-hub** [comment]
first of all, it shows me this and i have no idea what to do.
![image](https://user-images.githubusercontent.com/88946631/152588427-693f5257-a595-4d35-a718-96861c361ea0.png)
 Second, in the database, where i put database name, username, password it doesnt let me input the values. What do i do Please help

**Comment by MacWarrior** [comment]
Hello @in4mation-hub,

Two options : 
1 - You have SSH root access and so have to install required softwares
2 - You don't and have to check your manager if softwares are available
=> If not, you might want to contact your host or check their documentation

Best regards,
MacWarrior.

**Comment by in4mation-hub** [comment]
could you tell me how to fill database name, password, username cause the values wont let me type in them

**Comment by MacWarrior** [comment]
Hello @in4mation-hub, 

They are all asked during installation process
If you have issues, please give informations

Best regards,
MacWarrior.
