### ISSUE TITLE
German translation now available

### ISSUE THREAD

**Issue by joo4mart** [MacWarrior/clipbucket-v5#219]
Hallo!
The last days I have written the German translation file, sie attached file.
For better integration the file _upload/cb_install/sql/configs.sql_ needs an upgrade like:

```
 INSERT INTO `{tbl_prefix}languages` (`language_id`, `language_code`, `language_name`, `language_regex`, `language_active`, `language_default`) VALUES
 	(1, 'en', 'English', '/^en/i', 'yes', 'yes'),
-	(2, 'fr', 'French', '/^fr/i', 'yes', 'no');
+	(2, 'fr', 'French', '/^fr/i', 'yes', 'no'),
+	(3, 'de', 'German', '/^de/i', 'yes', 'no');

``` 
[de.lang.zip](https://github.com/MacWarrior/clipbucket-v5/files/8100527/de.lang.zip)

**Comment by MacWarrior** [comment]
Hello @joo4mart,

Thanks for translation, working on integrating it !

Best regards,
MacWarrior.

**Comment by MacWarrior** [comment]
Hello @joo4mart,

Translation has been integrated ! Thanks again !

Best regards,
MacWarrior.
