### ISSUE TITLE
expand number of categories for videos

### ISSUE THREAD

**Issue by joo4mart** [MacWarrior/clipbucket-v5#220]
Until now only one category can be set for videos. But as said it shoud be at least "4". I have found the problem in the database: the column 'category' has only a size of varchar(3). But eaech category needs three characters + space, e.g. "#3# ".

Here is the patch to expand the size of column category to varchar(30) for up to 7 categories, and file_type to varchar(4) for correct saving of  .webm files.
[need-larger-columns3.patch.zip](https://github.com/MacWarrior/clipbucket-v5/files/8107268/need-larger-columns3.patch.zip)

**Comment by MacWarrior** [comment]
Hello @joo4mart, 

Nice catch ! Column structure from my own DB was different and not coherent with current SQL state...
Category column has to be VARCHAR(200) or TEXT ; working on a fix !

Best regards,
MacWarrior.
