### ISSUE TITLE
Set Video fps more dynamically for better quality

### ISSUE THREAD

**Issue by joo4mart** [MacWarrior/clipbucket-v5#222]
'Video rate' , which is the fps rate, is manual set at 'General' 'Website Configurations' at 'Conversion'. But this value is often not the best choice. Usually if you change video from 50 fps to 25 fps all is perfect. But if you change video from 60 fps to 25 fps, or 50 fps to 30 fps, the software (ffmpeg) must remove a frame, but not in a regular pattern, which significantly degrades the quality of the video.
I think it is better to set a value for 'fps max' that should not be exceeded. My goal is to keep the original fps value as often as possible to not reduce the quality unnecessarily.

Here I send you patches for optimize the use of this fps rate dynamically. It would be nice you could use it for ClipBucket
[05_select-best-fps-value.patch.zip](https://github.com/MacWarrior/clipbucket-v5/files/8156189/05_select-best-fps-value.patch.zip)
[06_optimize-labels-and-help.patch.zip](https://github.com/MacWarrior/clipbucket-v5/files/8156190/06_optimize-labels-and-help.patch.zip)
.

**Comment by MacWarrior** [comment]
Hello @joo4mart, 

Many thanks for your participation.
Checking your modifications... 😄 

Best regards,
MacWarrior.

**Comment by MacWarrior** [comment]
Hello @joo4mart, 

Do you have any comparative example of 50 fps video converted to 30fps (vs. 25 fps) ?
Why are you using 3.3 as multiplicator ?

What result do you expect with this kind of parameters : Config 30 fps, video 133 fps ?
Note : It seems like ffmpeg allow float values as video rates

Best regards,
MacWarrior.

**Comment by joo4mart** [comment]
Sorry for not commenting.
The ideal is to reduce the FPS rate by an integer factor, so either by 2 or 3 or 4, where "3" leads to untypical fps rates.
Optimal conversions would be e.g.:
-   50 to 25 fps
-   60 to 30 fps
-   59.94 to 29.97 fps
-   30 to 15 fps

On the other hand, if the fps rate is converted from 60 to 25, or from 50 to 30, or even from 50 to 29.97, then the video quality deteriorates significantly, because because frames have to be discarded irregularly.

**Comment by joo4mart** [comment]
More answers:
I have chosen the ratio 3.3 arbitrarily. Actually, the fps rate should already be reduced by a factor of 3 or 4 with a ratio greater than 2. I abbreviated the calculation in these cases and then used the configured fps rate.

**Comment by MacWarrior** [comment]
Hello @joo4mart,

What do you think of this : 
```php
<?php
    $config = 30;
    $videos = [50,60,133,45,70,59.94];
    
    foreach($videos as $video){
    
        if( $video <= $config ){
            $final_vrate = $video;
        } else {
            $div = intdiv(max($video,$config),min($video,$config));
            if( $div == 1 ){
                $final_vrate = max($video,$config)/ceil($video/$config);
            } else {
                $final_vrate = $video/$div;
            }
        }
        echo '- Config : '.$config.' ; Video : '.$video.' : '.$final_vrate.'fps'.PHP_EOL;
    }
```

- Config : 30 ; Video : 50 : 25fps
- Config : 30 ; Video : 60 : 30fps
- Config : 30 ; Video : 133 : 33.25fps
- Config : 30 ; Video : 45 : 22.5fps
- Config : 30 ; Video : 70 : 35fps
- Config : 30 ; Video : 59.94 : 29.97fps

Best regards,
MacWarrior.

**Comment by joo4mart** [comment]
I have never seen videos with 45 / 70 / 133 fps, but ok:

- Config : 30 ; Video : 50 : 25fps = perfect
- Config : 30 ; Video : 60 : 30fps = perfect
- Config : 30 ; Video : 133 : 33.25fps => untypically
- Config : 30 ; Video : 45 : 22.5fps => untypically
- Config : 30 ; Video : 70 : 35fps = not seen, but perfect
- Config : 30 ; Video : 59.94 : 29.97fps = perfect

**Comment by joo4mart** [comment]
For your information:

- Movies: 24 fps (from old analog movies)
- Europe: 25, 50 fps (from PAL standards)
- USA: 29.97, 30, 59.95, 60 fps (from NTSC standards)

Video transmission standards in North America, Japan, and South Korea are still based on 60  / 1.001 ≈ 59.94 images per second.

More Infos: https://en.wikipedia.org/wiki/List_of_broadcast_video_formats

**Comment by MacWarrior** [comment]
Annnnnnnd it's done 😄
