### ISSUE TITLE
Admin area - Duplicate submenu active flag

### ISSUE THREAD

**Issue by MacWarrior** [MacWarrior/clipbucket-v5#223]
On admin area, submenus with same translation are all flagged active instead of only one : 

![image](https://user-images.githubusercontent.com/200590/156063012-46044805-0fa7-4607-bb20-0b20b64892dd.png)

**Comment by joo4mart** [comment]
The second one of 'Manage Categries' are for photos and should be found under 'Photos'.

**Comment by MacWarrior** [comment]
Hello @joo4mart,

Both videos and collections have categories ; but not photos which are only linked to collections.
This issue is about the display issue, showing active flag on both submenus because they share the same name

Best regards,
MacWarrior.

**Comment by MacWarrior** [comment]
Hello,

Issue fixed in last commit

Best regards,
MacWarrior.
