### ISSUE TITLE
SQL error viewing photos

### ISSUE THREAD

**Issue by joo4mart** [MacWarrior/clipbucket-v5#224]
If I select menu point 'Photos' usually I get the following error message:

> SELECT C.*, U.username, CPARENT.collection_name AS collection_name_parent
> FROM `clipbucket`.cb_collections C
>   INNER JOIN `clipbucket`.cb_users U ON C.userid = U.userid
>   LEFT JOIN `clipbucket`.cb_collections CPARENT ON C.collection_id_parent = CPARENT.collection_id
> WHERE C.active = 'yes' AND date_added IS NOT NULL
> ORDER BY date_added DESC LIMIT 0,10
> 
> ERROR : Column 'date_added' in where clause is ambiguous

I have tested and found, the correct SQL command should have added 'C.' in front of date_added:
> WHERE C.active = 'yes' AND C.date_added IS NOT NULL
> ORDER BY C.date_added DESC LIMIT 0,10

**Comment by joo4mart** [comment]
A similar error will come while select menu point 'Collections'.

**Comment by MacWarrior** [comment]
Hello @joo4mart, 

Thanks for report, your suggestion is correct ! 👍

Issue has been fixed on last commit

Best regards,
MacWarrior.
