### ISSUE TITLE
Optimize translations

### ISSUE THREAD

**Issue by joo4mart** [MacWarrior/clipbucket-v5#225]
Hello MacWarrior!
1) I have optimized some german translations, and I have added some time terms in plural.
2) And I haver reorganized the three translation files, so that they are identically sorted.

Here are my patches:
[01_translation-times.patch.zip](https://github.com/MacWarrior/clipbucket-v5/files/8238702/01_translation-times.patch.zip)
[02_reorg-translations.patch.zip](https://github.com/MacWarrior/clipbucket-v5/files/8238703/02_reorg-translations.patch.zip)

**Comment by MacWarrior** [comment]
Hello @joo4mart, 

Many thanks for your participation ; looking to integrate your modifications.
Don't lose too much time on translation organization, someday everything will be stored in DB 😉 

Best regards, 
MacWarrior.

**Comment by MacWarrior** [comment]
Hello @joo4mart,

Modifications has been committed ; I've also edited the function displaying time to use plurals translations implemented

Thanks again, 
Best regards,
MacWarrior.
