### ISSUE TITLE
optimize check of ffmpeg version

### ISSUE THREAD

**Issue by joo4mart** [MacWarrior/clipbucket-v5#226]
My output of 'ffmpeg -version' shows only a two-parted version:
> "Version ffmpeg version 4.4 Copyright (c) 2000-2021 the FFmpeg developers"

The code for checking ffmpeg version failed because it want to see three-parted version number. I have made a small patch for that problem. Perhaps you have a better idea for coding?
[09_optimize-check-ffmpeg.patch.zip](https://github.com/MacWarrior/clipbucket-v5/files/8238857/09_optimize-check-ffmpeg.patch.zip)

**Comment by MacWarrior** [comment]
Hello @joo4mart, 

Modifications has been committed 😄 

Best regards,
MacWarrior.
