### ISSUE TITLE
Running only with PHP 8.0 and higher?

### ISSUE THREAD

**Issue by joo4mart** [MacWarrior/clipbucket-v5#227]
With newest revision 70 clipbucket needs at least php 8.0. I got this error message:
> Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.0.0". 
> You are running 7.4.28. in /var/lib/clipbucket/upload/vendor/composer/platform_check.php on line 24

This dependency comes with commit ab6678b6ab267e4314df7b90046c2ab7b10100f8 (Implement Whoops 2.14.5 in DEV mode).
Is there any way running with my old PHP 7.4 version?

**Comment by MacWarrior** [comment]
Hello @joo4mart,

Thanks for report ; issue will be fixed asap !

Best regards,
MacWarrior.
