### ISSUE TITLE
Issue with database creation

### ISSUE THREAD

**Issue by ecureuilfourbe** [MacWarrior/clipbucket-v5#228]
Hey, I'm trying to install clipbucket, for Weeks now, I've found your "Beginner" script, everythings is fine (if you add "git" in the apt install commande :) ), but when I go trough the step of generating database, I have this error
![pb dataB clipbucket](https://user-images.githubusercontent.com/36704066/159297140-9c429953-9c9a-4494-a546-878aa232e48c.png)

I've try with an ubuntu 16.04 and 18.04 using virtualBox, same issue.
Any ideas ?
Thanks

**Comment by MacWarrior** [comment]
Hello @ecureuilfourbe,

Can you please confirm the version you're using ?
You can see revision number in /upload/changelog/550.json ; line 2 & 3 : version & revision

Thanks by advance,
Best regards,
MacWarrior.

**Comment by MacWarrior** [comment]
Can you also try to replace : 

``datecreated` date NOT NULL DEFAULT (CURRENT_DATE), `
by : 
``datecreated` date NOT NULL DEFAULT CURRENT_DATE,`
in 
/upload/cb_install/sql/structure.sql

Then retry installation ?

Thanks by advance,
Best regards,
MacWarrior.

**Comment by joo4mart** [comment]
> Hey, I'm trying to install clipbucket, for Weeks now

At which operation system you have tested at first time?

**Comment by ecureuilfourbe** [comment]
Hi, thank's for the quick response my version is 5.5.0  revision is 75 and status is "dev", i'm trying your fix, i'll be back

**Comment by MacWarrior** [comment]
Hello @ecureuilfourbe, 

Issue has been fixed on last commit
To update, go to your CB directory and use git pull command

Best regards,
MacWarrior.
