### ISSUE TITLE
better select of player resolution

### ISSUE THREAD

**Issue by joo4mart** [MacWarrior/clipbucket-v5#230]
After some tests I have found a better solution for the player to find a good resolution, if default value cannot be found.
See this patch:
[better-default-resolution.patch.zip](https://github.com/MacWarrior/clipbucket-v5/files/8328233/better-default-resolution.patch.zip)

**Comment by MacWarrior** [comment]
Hello @joo4mart, 

Thanks for patch, it has been implemented on latest revision ! 😄

Best regards,
MacWarrior.
