### ISSUE TITLE
optimized install script

### ISSUE THREAD

**Issue by joo4mart** [MacWarrior/clipbucket-v5#231]
Since I started working with ClipBucket, I have tried to optimise the installation script for Debian 11.
1) Above all, I wanted to make the script for Debian 11 usable with both Nginx and Apache2. 
2) Secondly, the script should also be usable for updates.

Look at my version 1.8:
[install_on_debian11_v18.zip](https://github.com/MacWarrior/clipbucket-v5/files/8336581/install_on_debian11_v18.zip)

As next step I could optimize and create a install script for Debian 10 ...

**Comment by joo4mart** [comment]
... small update of this script:
[install_on_debian11_v19.zip](https://github.com/MacWarrior/clipbucket-v5/files/8336748/install_on_debian11_v19.zip)

**Comment by joo4mart** [comment]
For Debian 10 I think it is good to take php7.4 for both webserver. My result script:
[install_on_debian10_v19.zip](https://github.com/MacWarrior/clipbucket-v5/files/8336814/install_on_debian10_v19.zip)

**Comment by MacWarrior** [comment]
Hello @joo4mart,

We recently updated our [Debian12 installation script](https://github.com/MacWarrior/clipbucket-v5/blob/master/utils/install_debian12.sh) which now provide multiple configurations choices.

Thanks for your participation, I'll see to implement a simple way to update ; "installation" script should not be used to "update" 😉

Best regards,
MacWarrior.

**Comment by MacWarrior** [comment]
Hello @joo4mart,

Since revision 356, there is an integrated update system based on git, this totally replace the need of a system shell script to update : 

![image](https://github.com/MacWarrior/clipbucket-v5/assets/200590/9f60bf56-8f32-4ed3-8413-90b84127920b)

Best regards,
MacWarrior.
