### ISSUE TITLE
Some Questions

### ISSUE THREAD

**Issue by ecureuilfourbe** [MacWarrior/clipbucket-v5#234]
Hello, it's me again, 

I have juste one question:

- Where does the uploaded videos goes first, in which folder ? I'm trying to set up a samba share, so right after i've finish to edit my video, I want to export directly in this folder and let clipbucket do the conversion and upload.

Hope my question is uderstandable 

Best regards,

**Comment by Guber01** [comment]
I just replaced the folders and made the maunt nfs disk. And given them appropriate rights. After processing, the files are discarded in these folders (videos, photos, audios). I think samba will also work.
https://prnt.sc/0th4A4_XD-QF

**Comment by ecureuilfourbe** [comment]
> I just replaced the folders and made the maunt nfs disk. And given them appropriate rights. After processing, the files are discarded in these folders (videos, photos, audios). I think samba will also work. https://prnt.sc/0th4A4_XD-QF

Hey, sorry for the late response, I'm curious, how do you do that exactly ? symbolic link or something ?

**Comment by Guber01** [comment]
In the Linux environment, for some reason it did not work through a symbolic link. I am a manting directly folder NFS to the folder with the site.
>>> 194.16.x.x:/mnt/hdd/nfs-d/videos /var/www/web/files/videos

**Comment by ecureuilfourbe** [comment]
Oh OK I see thanks one last question and you can close this issue, can we make livestream ?

**Comment by ecureuilfourbe** [comment]
OK, thank you for taking the time to answers my questions.

Best regards
