### ISSUE TITLE
uploading video error

### ISSUE THREAD

**Issue by Blisk** [MacWarrior/clipbucket-v5#235]
I have few days ago update my clipbucket from original 4.1 version to version 5.
Before update when I upload video I get confirmation video was uploaded and window is close I get web page of listed. videos.
But now not it stuck on page where I upload video. Video is uploaded anyway, but still. What can be wrong?
![2022-04-19 14_10_43-Upload - Important Videos - Opera](https://user-images.githubusercontent.com/2773050/164001338-e68c006e-bf31-4ff2-8cf6-6ff047792bc5.png)

**Comment by MacWarrior** [comment]
Hello @Blisk,

Can you enable development mode from admin area and then check php logs while you retry uploading a video ?

Best regards,
MacWarrior.

**Comment by Blisk** [comment]
Here is log
[Tue Apr 19 13:08:30.090130 2022] [proxy_fcgi:error] [pid 38643:tid 139680758609664] [client 192.168.0.1:34904] AH01071: Got error 'Primary script unknown'
[Tue Apr 19 14:25:07.346547 2022] [proxy_fcgi:error] [pid 1605:tid 139908870031104] (70008)Partial results are valid but processing is incomplete: [client 192.168.0.1:38474] AH01075: Error dispatching request to : (reading input brigade), referer: https://yourtop.news/upload.php

**Comment by MacWarrior** [comment]
Hello @Blisk, 

Can you retry while checking your browser console ?

Best regards,
MacWarrior.

**Comment by Blisk** [comment]
I just see when  I check website there is also log. Here it is
http://zerobin.povej.net/?276b44c66036a5ee#FLuxlAd+VIGa9lzkVh/uJjV3jZTJxduuuOg+sJhFGbk=

**Comment by Blisk** [comment]
Any idea what can be wrong here?

**Comment by Blisk** [comment]
This error still persist even with new users

**Comment by Blisk** [comment]
Yes this work OK now, no error anymore.
