### ISSUE TITLE
error message when I try to send a message

### ISSUE THREAD

**Issue by ecureuilfourbe** [MacWarrior/clipbucket-v5#237]
Hey, this error message shows up when I try to send a message (from one user to another)  

![image](https://user-images.githubusercontent.com/36704066/166225432-d3528bae-24a5-4a62-9f94-3247d72bd503.png)

any idea ?

have a nice day

**Comment by MacWarrior** [comment]
Hello @ecureuilfourbe, 

Issue has been fixed on last commit

Best regards,
MacWarrior.
