### ISSUE TITLE
new user add not working

### ISSUE THREAD

**Issue by Blisk** [MacWarrior/clipbucket-v5#238]
When I try to add new user and leave ALL for categories I get error if I select basic user or anything else than it works
![slika](https://user-images.githubusercontent.com/2773050/166821829-5b502c17-8b26-4702-b704-7016e02d7fd6.png)

error SQL : INSERT INTO clipbucket.cb_users (username,email,dob,country,sex,category,level,usr_status,welcome_email_sent,avcode,signup_ip,doj,featured_video,user_session_key,user_session_code) VALUES ('MacWarrior','abc@yourtop.news','2008-05-01','SI','Male','all','1','Ok','yes','de1f11d051','192.168.0.1','2022-05-04 20:29:15','','7c9b545b9d56ca0cfbe9ee686f304195','82338')
    error ERROR : Incorrect integer value: 'all' for column clipbucket.cb_users.category at row 1

**Comment by MacWarrior** [comment]
Hello @Blisk, 

Category "All" should not be selectable ; a fix has been released on latest commit

Best regards,
MacWarrior.
