### ISSUE TITLE
image upload not working

### ISSUE THREAD

**Issue by Blisk** [MacWarrior/clipbucket-v5#240]
I also noticed that when I upload image file is in the folder but not show up on web page

**Comment by MacWarrior** [comment]
Hello @Blisk,

Can you give a bit more details ?
How do you upload images ?
Maybe error logs or screenshots ?

Best regards,
MacWarrior.

**Comment by Blisk** [comment]
Uploading photos still doesn't work when I upload it it is like usually but when i click on photos it doesn't exist, you can try by yourself.

**Comment by Blisk** [comment]
I see photos are uploaded in folder clipbucket/files/photos/2022/11/08/166793696499b660.jpg
but not on web page none shows up.
And when I check logs, nothing there no errors

**Comment by MacWarrior** [comment]
Hi @Blisk, 

Sorry I missed your reply.
Go to admin area > General > Website configurations > Upload
And disable option "Photo Activation" ; then new uploaded photos will be automatically activated

Best regards,
MacWarrior.
