### ISSUE TITLE
uploading video stops

### ISSUE THREAD

**Issue by Blisk** [MacWarrior/clipbucket-v5#243]
I tested few large videos 200Mb+ and it stop on certain percentage, sometimes 24% sometimes 50% sometimes 95%.
And doesn't move no matter how long I wati.
and this is error in log.
[Tue Jun 07 14:52:43.521093 2022] [proxy_fcgi:error] [pid 18500:tid 139888728979200] (70008)Partial results are valid but processing is incomplete: [client 192.168.0.1:15927] AH01075: Error dispatching request to : (reading input brigade), referer: https://mywebsite.com/upload.php
![2022-06-07 14_56_53-Upload - Important Videos - Opera](https://user-images.githubusercontent.com/2773050/172386200-8d25114e-9714-4036-af80-6e0caecaa407.png)

**Comment by MacWarrior** [comment]
Hello @Blisk,

Can you retry with dev mode enabled ? You should have PHP/SQL errors from server side OR js error on browser side...

Thanks by advance,
Best regards,
MacWarrior

**Comment by Blisk** [comment]
first what I noticed is this, when start uploading sometimes in the middle just get notification files is uploaded but it is still on 33%
I will also enable dev mod and post results.
Max Upload filesize is 5000 in php.ini I have all set to 2.5Gb
Before I didn't have this troubles.
![2022-06-08 11_05_29-](https://user-images.githubusercontent.com/2773050/172578816-fd5b6321-13ce-4500-804b-64b47be110cd.png)

**Comment by MacWarrior** [comment]
Hello @Blisk, 

Thanks for error log ; I'll fix this SQL error but it doesn't seems to be related to video upload
Do you have any JS error in your browser console ? 

Best regards,
MacWarrior.

**Comment by Blisk** [comment]
No I didn't see any errors in browser console.
But I have new error. I have uploaded video and it works but I get this.
![slika](https://user-images.githubusercontent.com/2773050/177279125-c3591eb6-456c-450c-ad51-810fb5fa8201.png)

**Comment by MacWarrior** [comment]
Hello @Blisk, 

SQL error remonter on June 8 has been fixed on last revision.
About your last error, can you : 
- Update to latest revision
- Enable dev mode
- Retry

Thanks by advance, 
Best regards,
MacWarrior.

**Comment by alex4984191** [comment]
> Hello @Blisk,
> 
> Thanks for error log ; I'll fix this SQL error but it doesn't seems to be related to video upload Do you have any JS error in your browser console ?
> 
> Best regards, MacWarrior.

Hi
When I upload it, it also stops and says "video uploaded successfully"
In the browser console I see "actions/file_uploader.php:1 Failed to load resource: net::ERR_HTTP2_PING_FAILED"
Last update.

**Comment by alex4984191** [comment]
> > Hello @Blisk,
> > Thanks for error log ; I'll fix this SQL error but it doesn't seems to be related to video upload Do you have any JS error in your browser console ?
> > Best regards, MacWarrior.
> 
> Hi When I upload it, it also stops and says "video uploaded successfully" In the browser console I see "actions/file_uploader.php:1 Failed to load resource: net::ERR_HTTP2_PING_FAILED" Last update.

The web server settings are correct. the limit is up to 5G of the uploaded file. Files of small size (200-250 megabytes) are uploaded, but after clicking "send" on the upload page it writes "video not found". But it appears in the account and it can be edited.

**Comment by TheCosmicZero** [comment]
Hi @Blisk . I have had similar errors happen on my system. They were related to the file names being too long or having odd characters in them. I have had my users rename the files with 8.3 names before uploading. They have not had an issues since doing it this way. 

Regards,
TCZ

**Comment by MacWarrior** [comment]
> Hi @Blisk . I have had similar errors happen on my system. They were related to the file names being too long or having odd characters in them. I have had my users rename the files with 8.3 names before uploading. They have not had an issues since doing it this way. 
> 
> 
> 
> Regards,
> 
> TCZ

Hello @TheCosmicZero,

Can you give me an example of file name ?

Thanks by advance,
Best regards,
MacWarrior.

**Comment by TheCosmicZero** [comment]
@MacWarrior I will see if I can dig one up. It has been a while since I had the issue.

**Comment by Blisk** [comment]
I didn't have this issue anymore.

**Comment by Blisk** [comment]
this issue still persist and it is not gone

**Comment by Blisk** [comment]
I have a lot of times these issues, don't know why. I hope this can be solved because a lot of videos I can not upload.
![slika](https://user-images.githubusercontent.com/2773050/203512761-7c330ade-695c-4a24-9e0d-26bb073577eb.png)

**Comment by MacWarrior** [comment]
Hello @Blisk, @TheCosmicZero, @alex4984191, 

Issue has been, solved in latest commit
Admin access role is no longer required

Best regards, 
MacWarrior.
