### ISSUE TITLE
"Video does not exist" in video upload 

### ISSUE THREAD

**Issue by alex4984191** [MacWarrior/clipbucket-v5#246]
I switched from the original Clipbucket to your version.
Previously, when uploading a video, I could change the fields in the upload form.
Now if I click "send" I get the message "Video does not exist" until the video is processed.
Is it possible to make the fields change and be saved before the video is processed.
This is observed only in users. If the video is uploaded by the administrator (or if I enable "Administrator Access" for users) then everything is fine.
Console and logs is clean.

**Comment by MacWarrior** [comment]
Hello @alex4984191,

Thanks for report, I'll check with a standard user.

Best regards,
MacWarrior.

**Comment by alex4984191** [comment]
> 

Thank you for your work. This is the best solution. There are no analogues to this - it helped us.

**Comment by Blisk** [comment]
I still have this issue and I just uploaded new files right now and test it.

**Comment by alex4984191** [comment]
I also noticed that the user cannot upload the cover of the video until the video is processed. The image is uploaded, but is not displayed in the list. After the video processing is finished, the image does not appear. But if user upload it again, then everything is fine.
It seems to me that these problems are connected. At the moment I'm trying to trace variables in the video upload functions. So far without success...

**Comment by alex4984191** [comment]
A temporary solution was the addition of "Admin access" by the users without all moderation capabilities.

**Comment by Blisk** [comment]
> A temporary solution was the addition of "Admin access" by the users without all moderation capabilities.

So I need to add admin access to user for this to be gone?

**Comment by MacWarrior** [comment]
Hello @Blisk, @alex4984191, 

Issue has been, solved in latest commit

Admin access role is no longer required 

Best regards, 
MacWarrior.
