### ISSUE TITLE
uploading video  taking title from files

### ISSUE THREAD

**Issue by Blisk** [MacWarrior/clipbucket-v5#248]
Is it possible to remove that extension from titles, this would be great.
![image](https://user-images.githubusercontent.com/2773050/200662384-e8b38776-a187-445a-b865-2296a3aa4c3a.png)
so it will looks like this
![image](https://user-images.githubusercontent.com/2773050/200662715-47a076fe-d28e-41bf-9cff-6e3540aaad98.png)

**Comment by MacWarrior** [comment]
Hello @Blisk, 

Enhancement has been done on last commit

Best regards,
MacWarrior.

**Comment by Blisk** [comment]
I have uploaded last files to my server but no there are still .mp4 in title and...
![slika](https://user-images.githubusercontent.com/2773050/212351310-9e9e4a7c-ec26-4661-9730-915e1479f6da.png)

**Comment by MacWarrior** [comment]
Hello @Blisk,

Are you fully updated ?
From which form did you uploaded your video ?

Best regards,
MacWarrior.

**Comment by Blisk** [comment]
it work now ok, thank you
