### ISSUE TITLE
how to log into file bad login requests

### ISSUE THREAD

**Issue by Blisk** [MacWarrior/clipbucket-v5#250]
How to log into file when someone tries to guess username and password?
![slika](https://user-images.githubusercontent.com/2773050/210018266-90f15d18-17cc-4ff2-90a8-6eaa1fb7374b.png)

**Comment by Blisk** [comment]
Ok I see this is log in mysql database. I need this log in file to make fail2ban to block those failed logins.

**Comment by MacWarrior** [comment]
Hello @Blisk,

For this request, you might want to create a SH script which would create an export from your DB, but this is out of CB perimeter.

Best regards,
MacWarrior.

**Comment by Blisk** [comment]
> Hello @Blisk,
> 
> For this request, you might want to create a SH script which would create an export from your DB, but this is out of CB perimeter.
> 
> Best regards, MacWarrior.

simple captcha will solve this
