### ISSUE TITLE
cannot enable subtitles

### ISSUE THREAD

**Issue by joo4mart** [MacWarrior/clipbucket-v5#252]
Hello!
I have tried to enable subtitles at site '/admin_area/manage_players.php?mode=show_settings', but after 'Update Player Settings' it switch back to 'No'.

I have found, that in the database table 'xx_config' in the line 'player_subtitles' the value changes from EMPTY to 'yes'. This could be ok, but I cannot see subtitles. Then I have changed this value by hand to '1' -> then I can see subtitles in a video. But if I try to changing this value at the site again, subtitles vanished and can not be enabled again.

Can you find the code, where 'yes' will be ignored?

**Comment by MacWarrior** [comment]
Hello,

Thanks for report, issue reproduced
Will fix asap !

Best regards,
MacWarrior.

**Comment by MacWarrior** [comment]
Hello @joo4mart, 

Issue fixed on last commit

Best regards,
MacWarrior.
