### ISSUE TITLE
Add Portuguese (BR) to the project

### ISSUE THREAD

**Issue by raiancollyn** [MacWarrior/clipbucket-v5#253]
Hello MacWarrior, I would like to contribute to the project, so I made a translation of the en.lang file into Portuguese (BR), and of course, it may not be perfect, but I believe it should already help people.

Follow the attached file for implementation.
[pt-BR.zip](https://github.com/MacWarrior/clipbucket-v5/files/10413637/pt-BR.zip)

**Comment by raiancollyn** [comment]
I made the manual insertion in the "cb_languages" table, but I believe that it can be put in the installation script, if you want to check it out, it is like this in my table:
![image](https://user-images.githubusercontent.com/20705376/212403081-ed2afa19-57bb-4e1f-a7ac-42c1c92233bf.png)

After that, the process I did was that I just uploaded the file to the folder: includes -> langs
Then, going to the Admin Panel under General -> Language Settings, I clicked on "Recreate from pack" in it.

Here for me it worked correctly:
![image](https://user-images.githubusercontent.com/20705376/212404733-422e54e5-ba24-416e-83f7-30f7c46ccb60.png)

**Comment by MacWarrior** [comment]
Hi @raiancollyn, 

Many thanks for your participation, I will add it to repo asap !

Best regards,
MacWarrior.

**Comment by MacWarrior** [comment]
Hi @raiancollyn, 

Translation has been added in last commit
Thanks again !

Best regards,
MacWarrior.
