### ISSUE TITLE
searching videos

### ISSUE THREAD

**Issue by Blisk** [MacWarrior/clipbucket-v5#255]
I have updated some video with description but only description, not title and when I try to find that video by typing word at top right where search is video can't be found.

**Comment by MacWarrior** [comment]
Hi @Blisk,

Current search engine is pretty basic and will require a full refactor
It's mostly based on title and tags and work very badly with multiple words ; we've already planned to update it to enhance search results with multiple words searchs

Per example : 
- Video title : this is a test video abcd
- Video tags : test, abcd, specific-tag

Search examples : 
- "test video abcd", "test video", "test", "abcd", "specitic-tag" : sould work
- "test abcd", "video test", "abcd specitif-tag" : sould not work

Best regards,
MacWarrior.

**Comment by Blisk** [comment]
thank you

**Comment by Trabizon61** [comment]
same issue and same issue with channels, pohotos

**Comment by MacWarrior** [comment]
Hello @Blisk, 

Integrated search engine has been updated on revision [5.5.1 - 181](https://github.com/MacWarrior/clipbucket-v5/commit/2f27aa9f45dc73a1ba8862c717e1a97f18cc3b72) and now works on : 
- Title
- Tags
- Uploader name
- Categories
- Description (For videos only)

Search results are also ordered by match on this same list

Best regards,
MacWarrior.
