### ISSUE TITLE
video size after update is disaster

### ISSUE THREAD

**Issue by Blisk** [MacWarrior/clipbucket-v5#256]
I just update my clipbucket files and now when I try to watch video it is so small it can not be watched.
What is wrong here?? Funny is when I expande video to whole screen and than back to small like before I get normal size of video. But on the beginning is extreme small.

![slika](https://user-images.githubusercontent.com/2773050/229795494-a113927d-089b-41d1-8784-88a119644000.png)
https://yourtop.news

**Comment by MacWarrior** [comment]
Hello @Blisk,

Issue has been fixed in last commit.

Best regards,
MacWarrior.

**Comment by Blisk** [comment]
I just uploaded files and it is the same small size of video.
