### ISSUE TITLE
related photos - how to get some to show - it doesn't seem to work ?

### ISSUE THREAD

**Issue by spirogg** [MacWarrior/clipbucket-v5#26]
how would related photos work ?
- would it have to be based on tags
- channels

 Im not sure maybe its suppose to be tags as (keywords) ? 
not sure but seems not working what ever i try - just wondering 

thanks so much 

(PS) if your tired of me adding bugs to your fork please tell me to stop :)
I just like your Ideas better and yours seems more stable and Chromecast is so cool
-
![related photos](https://user-images.githubusercontent.com/17736688/40605032-9b228d10-6226-11e8-82ec-f8673b92fc3a.PNG)

**Comment by MacWarrior** [comment]
As I understand for videos, all "related items" are linked by the current item title

**Comment by spirogg** [comment]
If we have same title or word in title for photo. Then this will show ? 
 - cause I uploaded 3 photos with same name and it doesn't do anything. ?

**Comment by spirogg** [comment]
Maybe we can make this latest uploaded photos. Or just random photos.from.otyer.collection if too hard to fix related ??

**Comment by MacWarrior** [comment]
Hi,
I've fixed lots of things related to photos since this issue was opened ; can you try again with latest rev ?

**Comment by spirogg** [comment]
@MacWarrior ok this related photos still not working latest rev :( 

if it is hard to fix can we get code and file to edit to make it Popular Photos - like when we view a video ?

**Comment by spirogg** [comment]
@MacWarrior pretty much everything seems really awesome and solid build so far 

- except we need some related photos or make it popular photos like in videos :)

- ![capture](https://user-images.githubusercontent.com/17736688/50426493-80a3bc00-0854-11e9-8113-d8995a479aaa.PNG)

**Comment by spirogg** [comment]
working now related based on title words thanks works good
