### ISSUE TITLE
This video might not work properly in clipbucket 4

### ISSUE THREAD

**Issue by deeptofbyt** [MacWarrior/clipbucket-v5#260]
Hello,
I am new at clipbucket. I have installed clipbucket 4 stable version in Ubuntu 18.04. Now i am facing these problems. Is there someone who can help me about this problem? 
Screenshots are attached.  
1. This video might not work properly 
2. Can't able to add member or can't able to "Create New Account" - it shows "please select your category".
3. There are a lot of storage but it shows only 25% left, not able to upload any large file.
FFMPEG Version 7.100

Thanks in advanced.

![1home](https://github.com/MacWarrior/clipbucket-v5/assets/138993087/731679b4-b123-4b1b-9291-558859ac2ff3)
![add member](https://github.com/MacWarrior/clipbucket-v5/assets/138993087/5307f5fd-6412-4da0-b073-cb78ea2c143c)
![server modules](https://github.com/MacWarrior/clipbucket-v5/assets/138993087/14c73b48-1b05-4e92-9323-aca1b22e0fd0)
![storage problem](https://github.com/MacWarrior/clipbucket-v5/assets/138993087/d677b497-af1c-43f1-a107-baa02c60b12f)
![video manager](https://github.com/MacWarrior/clipbucket-v5/assets/138993087/da3bf172-8719-4805-bb9c-104a97218a73)
![video might not work properly](https://github.com/MacWarrior/clipbucket-v5/assets/138993087/61085bb0-1994-4ddb-a579-b793e2aaed0a)

**Comment by MacWarrior** [comment]
Hello @deeptofbyt, 

Unfortunately, official CB 4 is dead years ago and so isn't supported anymore by original creators
Please update to CB 5 (Latest revision for better results) to get a working version of Clipbucket and support here 

Best regards,
MacWarrior.
