### ISSUE TITLE
You have 64 files to execute to upgrade your database. You can use this following link : Update

### ISSUE THREAD

**Issue by alex4984191** [MacWarrior/clipbucket-v5#261]
After click to "Update" I hame error in /admin_area/admin_tool.php?id_tool=5

/includes/classes/admin_tool.class.php
return self::getTools([' id_tool = ' . mysql_clean($id)])[0];

**Comment by MacWarrior** [comment]
Hello @alex4984191 ,
Can you copy/paste your error ?
64 updates seems a bit strange as version system isn't that old

Thanks by advance,
Best regards,
MacWarrior

**Comment by alex4984191** [comment]
![image](https://github.com/MacWarrior/clipbucket-v5/assets/847289/6fe226f5-8856-4502-8886-d201c47268a9)

**Comment by MacWarrior** [comment]
Can you also show your dashboard page ?
Error seems legit because you should not have version and tools initialized
From which version/revision are you updating ?

You can also try to directly go to /admin_area/upgrade_db.php
Redirection to this page should be automatic when version system isn't initialised

**Comment by alex4984191** [comment]
I reinstalled the system and everything worked. I had to make changes to structure.sql

CREATE TABLE `clipbucket`.`{tbl_prefix}tools` --> `{tbl_prefix}tools`
CREATE TABLE `clipbucket`.`{tbl_prefix}tools_status` --> `{tbl_prefix}tools_status` 

the installation hung on the creation of the structure and did not continue further, after the change everything is ok

**Comment by MacWarrior** [comment]
Thanks for reply, we'll check this asap !

**Comment by MacWarrior** [comment]
Hi @alex4984191,

Issue has been fixed on last commit

Thanks again for your report

Best regards,
MacWarrior.
