### ISSUE TITLE
How do you update to the latest version of ClipBucket 

### ISSUE THREAD

**Issue by ivxmca** [MacWarrior/clipbucket-v5#263]
Current version : 5.5.0 - Revision 159 (Dev)

Also, how do you remove the 'Overall Stats' in the footer?

Finally, how do you get more videos to display on the homepage?

**Comment by MacWarrior** [comment]
Hello,

- To update to latest revision, use git command : git pull
Once file are updated, log in on /admin_area/ and follow update instructions ; you'll be asked for your previous version & revision to init upgrade system and get latests functionnalities

- Overall Stats are enable with dev mode, to disable it, go to admin area > Tool Box > Development Mode, and disable it

- There is currently no specific option to increase default number of videos on homepage, but "load more" buttons will display more videos without limit

Best regards,
MacWarrior

**Comment by ivxmark** [comment]
Is it possible to download the files then upload with the changes manually?

**Comment by MacWarrior** [comment]
Hello @ivxmark, 

You can download a [ZIP from Master](https://github.com/MacWarrior/clipbucket-v5/archive/refs/heads/master.zip) and then replace files on your server.
Don't upload /files/temp/install.me, or delete it after update
Then log in on /admin_area and follow update instructions

Best regards,
MacWarrior.

**Comment by ivxmark** [comment]
Which revision do I select?

**Comment by MacWarrior** [comment]
From where you update : 
> Current version : 5.5.0 - Revision 159 (Dev)

**Comment by ivxmark** [comment]
Is there a way to private DM you as the DB upgrade is not taking place.

Thank you :)

**Comment by MacWarrior** [comment]
Hello @ivxmark, 

Can you show a screenshot of what's happening ?
I'm available on discord

Best regards,
MacWarrior.

**Comment by ivxmark** [comment]
What is your discord username?

**Comment by MacWarrior** [comment]
Hello @ivxmark,

Discord server invitation link, like on readme : https://discord.gg/HDm5CjM

Best regards,
MacWarrior.

**Comment by MacWarrior** [comment]
Hello, 

Issue seems to have been resolved.

Best regards,
MacWarrior.
