### ISSUE TITLE
Show Thumbnail Videos Only For Allowed User

### ISSUE THREAD

**Issue by ismaeltj9** [MacWarrior/clipbucket-v5#266]
Hello, is it possible to show thumbnail only for private user allowed? Nowadays the thumb is showed for everyone and the videos reproduce only for allowed users.

**Comment by MacWarrior** [comment]
Hello @ismaeltj9, 

Do you want to disable access to guest users ?
This can be done in Admin Area > Users > Users levels : Edit Guest profile and disable "View Videos Page"

Best regards,
MacWarrior

**Comment by ismaeltj9** [comment]
Hello @MacWarrior,

No, I want to show only thumbs from videos that user have permission to watch, not all videos, for example in images attached, the user see a lot of thumbs, but have no permission to watch.

![Screenshot_54](https://github.com/MacWarrior/clipbucket-v5/assets/24549114/b7da7c9c-b260-40ae-90d0-cd05e0c43879)
![Screenshot_55](https://github.com/MacWarrior/clipbucket-v5/assets/24549114/55ba0d99-3b90-45c6-b85e-b4bab8c7eebe)

**Comment by MacWarrior** [comment]
Hello @ismaeltj9, 

Thanks for precision, we worked on this kind of issue very recently, I'll check this asap !

Best regards,
MacWarrior.

**Comment by MacWarrior** [comment]
Hello @ismaeltj9,
 
Privacy has been fixed on latest commit : unavailable videos (and photos, even in playlists or collections) won't be visible anymore

Best regards,
MacWarrior.

**Comment by ismaeltj9** [comment]
Hello @MacWarrior,

Thank you for answer, how can I update my system?

"Current version : 5.5.0 - Revision 164 (Dev)
Latest version (Dev) : 5.5.0 - Revision 271"

**Comment by MacWarrior** [comment]
Hello @ismaeltj9, 

If you used easy installation script or git commands to clone repo, then go to clipbucket directory on your server and use these commands : 
```
git reset --hard
git pull
chmod 755 ./* -R
chown www-data ./* -R
```

Best regards,
MacWarrior.
