### ISSUE TITLE
Upload of bigger duration videos not working

### ISSUE THREAD

**Issue by orlovskyjavaprofi** [MacWarrior/clipbucket-v5#274]
So i can upload videos with 4 or 10 minutes, longer than that is not possible.
**FIXED : I use latest dev version, my admin panel not accesible i see blank page when i open admin panel.**
Fix this issues ASAP.

**Comment by MacWarrior** [comment]
Hello @orlovskyjavaprofi ,

This looks an server configuration issue
Please check your php configuration, depending of your installation.

For apache, you need to edit both apache & cli config ; and also php-fpm config if you use it

For nginx, you need to edit php-fpm & cli config ; and also your nginx vhost

You can also check your current php configuration from admin area > tool box

Best regards,
MacWarrior.

**Comment by orlovskyjavaprofi** [comment]
look both clil, fpm and apach ini configured for max 
safe_mode = off
output_buffering = on
open_basedir = off
max_execution_time = good large value
memory_limit = large valueM
session.gc_maxlifetime = good large value
post_max_size = good large valueM
upload_max_filesize = good large valueM
i will not disclose the fix number , because of the security reasons, but rest assured those value are setup correctly, for me the problem somethin where the uploader handle files.
Provide exact class names which responsible for handling files.
Its feels kind of messy with this project.

**Comment by MacWarrior** [comment]
Hello @orlovskyjavaprofi, 

There is absolutely no security issue with these values.
Please check as said Admin Area > Tool Box > System info : Hosting tab
Please also make sure your configuration is set correctly in in Admin Area > General > Website configurations : Upload tab : Max upload file size (Should be a number, in Mb, line "10000" for 10Go)

![image](https://github.com/MacWarrior/clipbucket-v5/assets/200590/b4598d11-24de-45b5-a5a8-65ebb9ac7479)

Please also enable Dev mode in Admin Area > Tool Box > Development Mode ; and then retry uploading file
- Check your browser console during file upload
=> If you got a 413 error, this means your server configuration isn't correct
- Check your php log file
=> If you got a 500 error, please share it here

Best regards,
MacWarrior.

**Comment by orlovskyjavaprofi** [comment]
Does 100G means 100G per post ? hehe mkv files?

**Comment by orlovskyjavaprofi** [comment]
Let me repeate this menu which you showed , all green , all values are correct.

**Comment by orlovskyjavaprofi** [comment]
look something with uploader is broken, i upload my mp4 its ca 160mb big and 10 minutes and still it fail!
Smaller clips from phone strangely enough working .
<a href="https://ibb.co/cwjRvLV"><img src="https://i.ibb.co/yprKRS7/uploaderbigfiles.png" alt="uploaderbigfiles" border="0"></a>

**Comment by orlovskyjavaprofi** [comment]
**Ok, the solution was simple as always,** i almost forgotten that my website used **a lot of cloudflare and ofcourse on free plan you cant move large files via cloudflare network,** **would be it amazing if would do that for free,** anyway, i plan implement customized 2fa solution, add a little bit security for login.
