### ISSUE TITLE
Manage page solution if page not added

### ISSUE THREAD

**Issue by orlovskyjavaprofi** [MacWarrior/clipbucket-v5#275]
So recently i started to customize the platform and found new bug , here is solution if custom page is not added

ALTER TABLE `irsclipbucket`.`voiceOfIRS_pages` MODIFY COLUMN `page_order` INT NOT NULL DEFAULT 0;

**Comment by orlovskyjavaprofi** [comment]
**This should be straight after installation, otherwise you catch nasty bug with inability to create new custom page!**

**Comment by orlovskyjavaprofi** [comment]
**Done and Done**

**Comment by MacWarrior** [comment]
Hello @orlovskyjavaprofi, 

Thanks for report, issue confirmed.
Be carefull when sharing personnalised SQL as you also copy/pasted your DB prefix.
Please don't self-close issue unless creating it was an error from your side, especially if a fix is required.

Will fix it asap.

Best regards,
MacWarrior.

**Comment by orlovskyjavaprofi** [comment]
We need to use ChatGpt on this project and streamlined it.
I still thinking about taking time for improving the uploader.

**Comment by MacWarrior** [comment]
Hello @orlovskyjavaprofi,

Issue fixed on last commit.

Best regards,
MacWarrior.
