### ISSUE TITLE
Where options for configuring email settings

### ISSUE THREAD

**Issue by orlovskyjavaprofi** [MacWarrior/clipbucket-v5#276]
Am i blind but current dev version i dont see any page for email phpmail setup. 
How i currently can setup my email, so that people can notified , and for registration purposes.

**Comment by MacWarrior** [comment]
Hello @orlovskyjavaprofi, 

Email templates are in Admin Area > General > Email templates
There are very few email options ; all of them are in Admin Area > General > Website configurations : Emails tab

Best regards,
MacWarrior.
