### ISSUE TITLE
Example for GDPR consent cookie banner

### ISSUE THREAD

**Issue by orlovskyjavaprofi** [MacWarrior/clipbucket-v5#279]
Well i am gone full into production , cool most of feature which i need working it was a lot of work!

Here is a code which you can embed on your page for GDPR cookie consent:

https://pastebin.com/xqMPdyEX

**Comment by Trabizon61** [comment]
Thanks, bro where I must put the code? Into footer.html? If yes it does not work

**Comment by MacWarrior** [comment]
Hello @orlovskyjavaprofi, 

To respect RGPD, cookies banner has to be displayed before any cookie is created, and rejecting cookies has to cancel cookies generation.
Once cookies have been allowed or not, at anytime, users have to be able to change their choice
This implement requiere way more than a single JS pop-in as all cookies are still enabled.

Anyway, about cookies, RGPD only focus on ads cookies and tracking cookies ; and as long as ClipbucketV5 don't have any... Cookies banner is not required by RGPD on ClipbucketV5.
You might need one if you add specific ads or tracking scripts to your own ClipbucketV5, but in this specific case, this single script won't be enough.

Best regards,
MacWarrior.
