### ISSUE TITLE
There is a plugin for translations of the websitte, use latest Jquery and Pluploader

### ISSUE THREAD

**Issue by orlovskyjavaprofi** [MacWarrior/clipbucket-v5#281]
Look its cool you own and translate, but there exist a quick and dirty web widget **Gtranslate** and it works.
Latest jquery 3.7.1 works fine, no issues.
**Same goes to the file uploader which PL uploader 2.3.9**

**Comment by MacWarrior** [comment]
Hello @orlovskyjavaprofi, 

Thanks for report, libs have been updated.

Best regards,
MacWarrior.
