### ISSUE TITLE
Update for main.html

### ISSUE THREAD

**Issue by orlovskyjavaprofi** [MacWarrior/clipbucket-v5#284]
**here is update code https://pastebin.com/kkmMAvyM**

**Comment by orlovskyjavaprofi** [comment]
Ok, this look even more cleaner!
[https://pastebin.com/naMix3T6 main.html](https://pastebin.com/naMix3T6 main.html) **for admin dashboard!**

**Comment by MacWarrior** [comment]
Hello @orlovskyjavaprofi,

Thanks for your participation, unfortunately your code is outdated and you don't even introduce what it does.
Please create a pull request and tell us more about what you've done here.

Best regards,
MacWarrior.
