### ISSUE TITLE
Fix for Oxygenz - Remote Play  plugin

### ISSUE THREAD

**Issue by orlovskyjavaprofi** [MacWarrior/clipbucket-v5#287]
ALTER TABLE `yourprefix_video`
ADD COLUMN remote_play_url VARCHAR(500);

Standard clipbucket database missing in table video the column , so with this is easy fix.

**Comment by MacWarrior** [comment]
Hello @orlovskyjavaprofi,

Field is correctly created when installing plugin and it's useless until you use remote play plugin.

Best regards,
MacWarrior.
