### ISSUE TITLE
Fix for plugin social_beast

### ISSUE THREAD

**Issue by orlovskyjavaprofi** [MacWarrior/clipbucket-v5#288]
CREATE TABLE IF NOT EXISTS yourprefix_social_beast_links (
    `id` int(20) NOT NULL AUTO_INCREMENT,
    `facebook` TEXT NOT NULL,
    `twitter` TEXT NOT NULL,
    `google` TEXT NOT NULL,
    `linkedin` TEXT NOT NULL,
    `pinterest` TEXT NOT NULL,
    `reddit` TEXT NOT NULL,
    `youtube` TEXT NOT NULL,
    `vine` TEXT NOT NULL,
    `rss` TEXT NOT NULL,
    `github` TEXT NOT NULL,
    `dropbox` TEXT NOT NULL,
    `stumbleupon` TEXT NOT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO yourPrefix_social_beast_links (`id`, `facebook`, `twitter`, `google`, `linkedin`, `pinterest`, `reddit`, `youtube`, `vine`, `rss`, `github`, `dropbox`, `stumbleupon`) VALUES (NULL, '', '', '', '', '', '', '', '', '', '', '', '');

**Comment by orlovskyjavaprofi** [comment]
Ah the plugin need more work as it seems, inserting and creating table wont help :(

**Comment by MacWarrior** [comment]
Hello @orlovskyjavaprofi, 

Social beast has been rewritten and integrated on revision 120, it's not a plugin anymore

Best regards,
MacWarrior.
