### ISSUE TITLE
Search results will not shown

### ISSUE THREAD

**Issue by Trabizon61** [MacWarrior/clipbucket-v5#290]
HI everbody the videos uploaded and converted successfully but if I search a video, or channel, photo that exists will not be displayed on the search results I get the message " No results found "

**Comment by MacWarrior** [comment]
Hello @Trabizon61, 

Can you provide some screenshots ?
What terms are you searching ? What are the titles you intend to see in search with these terms ?

Search is based on title and tags

Best regards,
MacWarrior.

**Comment by Trabizon61** [comment]
> Hello @Trabizon61,
> 
> Can you provide some screenshots ? What terms are you searching ? What are the titles you intend to see in search with these terms ?
> 
> Search is based on title and tags
> 
> Best regards, MacWarrior.

Hi thank you for the info, for video it works but channels will not be found

The channel "hitaf" exists but it will not be shown

<img width="1197" alt="Bildschirmfoto 2023-10-31 um 09 03 07" src="https://github.com/MacWarrior/clipbucket-v5/assets/25510423/f52d0d45-44a1-4180-8fac-9cdf3af051b6">

**Comment by MacWarrior** [comment]
Hello @Trabizon61, 

Issue has been fixed on latest commit.
There is still work to do to increase search efficacy, but for now it works well with title and tags

Best regards,
MacWarrior.

**Comment by Trabizon61** [comment]
bro I uploaded and replaced the file but now I get a white blank page at the search
