### ISSUE TITLE
where is android and ios native app?

### ISSUE THREAD

**Issue by saman222** [MacWarrior/clipbucket-v5#291]
hi
i see ANDROID APP in the: https://clipbucket.com/features/
is it exist with clipbucjet-v5?
what about all features in the above link? is it still work in v5?
thank you

**Comment by MacWarrior** [comment]
Hello @saman222,

Android & iOS apps for Clipbucket are "premium version" only and have never been open source or free

Old clipbucket, renamed as Vodlix, sells Android & iOs App for 1199£/month or 500£ without updates.

At [Oxygenz](https://clipbucket.oxygenz.fr), we might provide in near future, custom iOS & Android apps for ClipBucketV5, incorporating the features of ClipbucketV5 in its mobile version ; and for a fraction of the price offered by Vodlix

Best regards,
MacWarrior.

**Comment by saman222** [comment]
can you give me any clue for those who want to create android app? is there any API or your mean create a something such as webview or ionic cordova?
