### ISSUE TITLE
Chunked Uploads (Feature Request)

### ISSUE THREAD

**Issue by alexckent** [MacWarrior/clipbucket-v5#314]
Love the software, thank you!

Please may I add a feature request - chunked uploads.

Our video files are often more than a GB, so that's too much for setting upload_max_filesize and post_max_size in php.ini. We only seem to realistically manage to accept videos about 200MB, but even this could be a security issue.

Maybe you could implement an uploader like Plupload that uses javascript on the frontend to chunk the upload - and then recombines it serverside?

Thanks! Alex

**Comment by MacWarrior** [comment]
Hello @alexckent, 

I'm working on it ; got still a few things to fix but this should comes to CB5 soon 👍 

Best regards,
MacWarrior.

**Comment by MacWarrior** [comment]
Hello @alexckent, 

Chunked upload has been implemented in latest revision

Best regards,
MacWarrior.
