### ISSUE TITLE
error during installation

### ISSUE THREAD

**Issue by gaetano118** [MacWarrior/clipbucket-v5#337]
> SQL : CREATE TABLE `cb_video` ( `videoid` bigint(20) NOT NULL, `videokey` mediumtext NOT NULL, `video_password` varchar(255) NOT NULL DEFAULT '', `video_users` text NOT NULL DEFAULT '', `username` text NULL DEFAULT NULL, `userid` int(11) NULL DEFAULT NULL, `title` text DEFAULT NULL, `file_name` varchar(32) NOT NULL DEFAULT '', `file_type` VARCHAR(3) NULL DEFAULT NULL, `file_directory` varchar(25) NOT NULL DEFAULT '', `description` text DEFAULT NULL, `category` VARCHAR(200) NULL DEFAULT NULL, `broadcast` varchar(10) NOT NULL DEFAULT '', `location` mediumtext DEFAULT NULL, `datecreated` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, `country` mediumtext DEFAULT NULL, `allow_embedding` char(3) NOT NULL DEFAULT '', `rating` int(15) NOT NULL DEFAULT 0, `rated_by` varchar(20) NOT NULL DEFAULT '0', `voter_ids` mediumtext NOT NULL, `allow_comments` char(3) NOT NULL DEFAULT '', `comment_voting` char(3) NOT NULL DEFAULT '', `comments_count` int(15) NOT NULL DEFAULT 0, `last_commented` datetime DEFAULT NULL, `featured` char(3) NOT NULL DEFAULT 'no', `featured_date` datetime DEFAULT NULL, `allow_rating` char(3) NOT NULL DEFAULT '', `active` char(3) NOT NULL DEFAULT '0', `favourite_count` varchar(15) NOT NULL DEFAULT '0', `playlist_count` varchar(15) NOT NULL DEFAULT '0', `views` bigint(22) NOT NULL DEFAULT 0, `last_viewed` datetime NOT NULL DEFAULT '1000-01-01 00:00:00' ON UPDATE CURRENT_TIMESTAMP, `date_added` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, `flagged` varchar(3) NOT NULL DEFAULT 'no', `duration` varchar(20) NOT NULL DEFAULT '00', `status` enum('Successful','Processing','Failed','Waiting') NOT NULL DEFAULT 'Processing', `default_thumb` int(3) NOT NULL DEFAULT 1, `embed_code` text NULL DEFAULT NULL, `downloads` bigint(255) NOT NULL DEFAULT 0, `uploader_ip` varchar(20) NOT NULL DEFAULT '', `video_files` tinytext NULL DEFAULT NULL, `file_server_path` text NULL DEFAULT NULL, `video_version` varchar(30) NOT NULL DEFAULT '5.5.0', `thumbs_version` varchar(5) NOT NULL DEFAULT '5.5.0', `re_conv_status` tinytext NULL DEFAULT NULL, `is_castable` tinyint(1) NOT NULL DEFAULT 0, `bits_color` tinyint(4) DEFAULT NULL, `subscription_email` enum('pending','sent') NOT NULL DEFAULT 'pending', `age_restriction` INT DEFAULT NULL ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_520_ci;
> Error : BLOB, TEXT, GEOMETRY or JSON column 'video_users' can't have a default value

this is the error I get during installation

the version of MYSQL is
_mysql  Ver 8.0.36-0ubuntu0.22.04.1 for Linux on x86_64 ((Ubuntu))_
the version of PHP is
_PHP Version 7.4.33_
Solution?

**Comment by MacWarrior** [comment]
Hello @gaetano118,

This is a common issue with SQL strict mode which is default on most MySQL 8...
We'll fix this asap

Best regards,
MacWarrior.

**Comment by gaetano118** [comment]
Thanks, I'll wait for the update

**Comment by gaetano118** [comment]
Thanks, the installation worked, I encountered other problems, I'll see if I can solve them.
Thank you very much
