### ISSUE TITLE
installation in a subfolder

### ISSUE THREAD

**Issue by gaetano118** [MacWarrior/clipbucket-v5#339]
I encountered a problem that I couldn't solve, everything works as long as it's installed in the root of the server otherwise it doesn't work, it always goes to the root folder, has anyone managed to solve the problem?

**Comment by MacWarrior** [comment]
Hello @gaetano118,

Unfortunately, Clipbucket has been originally written to only work on root directory ; same issue already exists (#156)
Most internal links are hardcoded and need to be rewritten to work with subdirectories

We'll work on it someday, when we'll have time for it 😄 

Best regards,
MacWarrior.

**Comment by gaetano118** [comment]
ok I understand, thanks
