### ISSUE TITLE
sql folder is missing from downloads

### ISSUE THREAD

**Issue by kearym** [MacWarrior/clipbucket-v5#340]
I was trying to install this on a new server and the installation instructions refer to a sql folder that isn't a part of the downloads. I found some other versions of clip bucket on GitHub and they have a sql folder. Am I missing something? Thanks for keeping this alive.

**Comment by MacWarrior** [comment]
Hello @kearym, 

Which instructions did you followed ?

Best regards,
MacWarrior.

**Comment by kearym** [comment]
https://github.com/MacWarrior/clipbucket-v5/blob/master/docs/installation.html

**Comment by MacWarrior** [comment]
Oh ! Well, this isn't used and even less updated 😅
To make a clean new install, just clone repository on your server and make your vhost point to /upload directory
Then everything is automated from web interface : 
![image](https://github.com/MacWarrior/clipbucket-v5/assets/200590/8bee79f1-a70d-4531-8004-08c1fa995be6)

You can also find vhost examples in [installation scripts](https://github.com/MacWarrior/clipbucket-v5/tree/master/utils)
