### ISSUE TITLE
Spanish translation files

### ISSUE THREAD

**Issue by gvasquezj** [MacWarrior/clipbucket-v5#353]
Attached cb_languages_translations.sql and cb_languages.sql, contains Spanish language. I don't know how to add here without screwing up. so I leave them for some professional to do it

Greetings

[cb_languages.zip](https://github.com/MacWarrior/clipbucket-v5/files/14629191/cb_languages.zip)

**Comment by MacWarrior** [comment]
Hello @gvasquezj, 

Thanks for your participation !

It seems you use an old version of ClibBucketV5
Can you also provite your cb_language_keys table ?

Thanks by advance, 
Best regards,
MacWarrior.

**Comment by gvasquezj** [comment]
[cb_languages_keys.zip](https://github.com/MacWarrior/clipbucket-v5/files/14704955/cb_languages_keys.zip)

Here goes the file, it may be an old version since I downloaded clipbucket a while ago

Best regards,
GV

**Comment by MacWarrior** [comment]
Hello @gvasquezj,

Thanks again, Spanish translation has just been added with latest revision.

Best regards,
MacWarrior.
