### ISSUE TITLE
Media info not found

### ISSUE THREAD

**Issue by SaturnTeamDev** [MacWarrior/clipbucket-v5#362]
I installed CB 5.5 in my lamp stack in the Cloudron panel on my Ubuntu 22.04 VPS. All the prerequisites were found except for Media Info. I installed it using apt-get install through macOS Terminal and verified the location. I filled in the location (/usr/bin/mediainfo) in CB admin. I tried rebooting LAMP and the server. The apt command installed the general Ubuntu 22.03+ package. But CB still says it can't locate the binary. I tried uploading a short MPEG video. The loading bar worked but that was it. The image and info won't show up and all the options are greyed out. I'm thinking the mediainfo version is not good or there is an incorrect server pointer to the binary? I'm stuck and can't use CB. Help!

**Comment by SaturnTeamDev** [comment]
After a long review of files and paths, I realized the mediainfo install showed up in SFTP but not in the Terminal. The bin was set with 644 permissions. I have changed it and am rebooting the server/LAMP and clearing browser cache.

**Comment by MacWarrior** [comment]
Hello @SaturnTeamDev,

ClipbucketV5 uses 'which' command to get softwares paths
If software is correctly installed and configured to be used by http server user, then it should work, like this (with www-data user in my case by example) : 
![image](https://github.com/MacWarrior/clipbucket-v5/assets/200590/79880f65-774d-4afd-8931-82a13757e34e)

During installation process, only PHP and MySQL are mendatory, all other software can have their path configured lated in admin area configurations

We have never tried installing Clipbucket on macOS and will consider testing it

Best regards,
MacWarrior.

**Comment by SaturnTeamDev** [comment]
I know the software uses the which command. I didn't mean that I installed it on macOS. I was saying I was using macOS terminal to update my install which is in Ubuntu 22.04. I installed the site through LAMP in the Cloudron panel. This seemed to place all the files in a docker system. I might try to install the site on the base server without any panel or docker.

**Comment by SaturnTeamDev** [comment]
I did use the easy installation script and got everything installed. Mediainfo is working now. I do have some problems which include English typos in the site. I will make a separate post on here about those issues.
