### ISSUE TITLE
enhancement if you could do this photos after upload and submit redirect to photo manager

### ISSUE THREAD

**Issue by spirogg** [MacWarrior/clipbucket-v5#37]
Hi when we upload a video after Submit redirects to video manager for user, 
https://mydomain.com/manage_videos.php

would be nice to keep same as video upload

- can we make it for photo upload also after upload photo and save it redirect to manage photos
https://mydomain.com/manage_photos.php

**Comment by spirogg** [comment]
@MacWarrior i figured it out you have to add 

```
// After click save dtails it redirects to manage_photos.php
					        
					        	setTimeout(function(){
									$("#uploadMessage").addClass("hidden");
									window.location = "/manage_photos.php";
								}, 3000);						   			
					   		// Remove bellow NOT SURE IF 3000 is ok or need 5000 but now it works

					   	/*		setTimeout(function(){
					   				$("#uploadMessage").addClass("hidden");
					   			}, 5000);
					   			*/
```
![image](https://user-images.githubusercontent.com/17736688/96352725-28722580-108b-11eb-801f-c032e917ae92.png)

**Comment by spirogg** [comment]
LOL im not even a programer lol but I feel good I found this and solved it now you just have to add and mark as solved, Im going to keep looking to find solutions for more enhancements and or bugs 
thanks again for all your hard work :)

Spiro

**Comment by MacWarrior** [comment]
Hello @spirogg,

It's been, a long time 😄
I've been looking on your request and it's not compatible with multiple files upload because it would redirect to uploaded photo just after upload

Video upload has been refactored recently, and it seems like the same thing is requiered for photos ; it seems totally broken for now 😢

Best regards,
MacWarrior.

**Comment by MacWarrior** [comment]
Hello @spirogg,

I've just finished to refactor photo upload and as I mentioned in my previous message, redirecting to photo manager would be in conflict with multi upload.
Please have a look on last revision about it ; you might change your mind 😉

Best regards,
MacWarrior.
