### ISSUE TITLE
New users not able to upload channel background banner

### ISSUE THREAD

**Issue by SaturnTeamDev** [MacWarrior/clipbucket-v5#370]
I completed install and got email working. I have set up testing accounts. When new users (including admin) click the button to upload a channel background banner, the image does not upload. There is an error symbol in some browsers but not others. The text for the error refers to the user not being found. I can go into the admin panel and manually upload a banner image for any user and that works. After that initial admin uploaded image, the user can click the button on their channel to change to a new banner. Any ideas?
[J'ai terminé l'installation et le courrier électronique fonctionne. J'ai créé des comptes de test. Lorsque de nouveaux utilisateurs (y compris l'administrateur) cliquent sur le bouton pour télécharger une bannière d'arrière-plan de chaîne, l'image n'est pas téléchargée. Il y a un symbole d'erreur dans certains navigateurs mais pas dans d'autres. Le texte de l'erreur fait référence à l'utilisateur introuvable. Je peux accéder au panneau d'administration et télécharger manuellement une image de bannière pour n'importe quel utilisateur et cela fonctionne. Après cette image initiale téléchargée par l'administrateur, l'utilisateur peut cliquer sur le bouton de sa chaîne pour passer à une nouvelle bannière. Des idées?]

**Comment by MacWarrior** [comment]
Hello @SaturnTeamDev, 

I haven't been able to reproduce your issue

On which browser did youo get the issue ? 
Can you provide a screenshot ?
Can you also provide the image you tried to upload ?

Best regards,
MacWarrior.

**Comment by SaturnTeamDev** [comment]
Thank you for responding. I narrowed down the source of the issue. I took a number of screenshots to guide you through the problem. I have tested this issue in Chrome, Safari, and Firefox on macOS. Here is the testing profile with the banner area:
![StandardBanner](https://github.com/MacWarrior/clipbucket-v5/assets/43824646/ddbec21f-5937-4cc8-9a7a-319eeab09014)
In Firefox, I opened Dev Tools to check what is going on on the back end and I see the JavaScript uploader and can check for breaks/errors:
![DevTools](https://github.com/MacWarrior/clipbucket-v5/assets/43824646/80e2bcef-c556-43f4-aa17-8884ab033cd2)
Here is the background banner I am trying to upload to my test user's channel:
![SampleBanner](https://github.com/MacWarrior/clipbucket-v5/assets/43824646/16215ee8-8d2b-4b4b-844b-3d071646352b)
When I click to upload the picture, it goes through the process but no image is attached. Below, I have a screenshot of the result in Safari:
![ErrorSafari](https://github.com/MacWarrior/clipbucket-v5/assets/43824646/b8c96c3f-58cc-4302-92bd-a702d67b0487)
I realized the problem is the uploader is trying to attach the image to the channel using a number string ID instead of the username associated with the channel:
![UserDoesntExist](https://github.com/MacWarrior/clipbucket-v5/assets/43824646/a632277e-4c68-4253-bc80-f55dd1165380)
Here is a screenshot from Firefox Dev Tools:
![DevTools2](https://github.com/MacWarrior/clipbucket-v5/assets/43824646/d7e4fa99-d2f0-4bfe-ae8a-afcbcc9a9d64)
The button and script go through the process correctly but the image is not able to be attached.
Here is a screenshot of the approach to editing the user's banner through the admin panel:
![AdminPanel](https://github.com/MacWarrior/clipbucket-v5/assets/43824646/8d0bde9b-7000-4a44-9ea9-3061b1109af8)
That admin process works correctly. But it is uploading the background banner using a different link to the username ID instead of a channel number ID. As you can see in the screenshots, when the script attempts to attach the image, it is trying to attach the banner to **channel 1714230033** instead of **user JustTesting2 (UID 4)**. In other words, the uploader error is resulting from **_channel.php?#_** instead of **_user.php?uid=4#background_**.

**Comment by MacWarrior** [comment]
Hi @SaturnTeamDev, 

Thanks for reply and all details ; will give it a look

Best regards,
MacWarrior.

**Comment by MacWarrior** [comment]
Hi @SaturnTeamDev,

User doesn't exist seems relevant in this case because there is no such user/channel existing
How do you get this error without manually edit of the URL ?

Upload issues have been fixed with lastest revision

Best regards,
MacWarrior.

**Comment by SaturnTeamDev** [comment]
There was no manual edit of the URL. I tried uploading the banner image in multiple browsers. When I control click to open the "?" error image, that was the message. But the user exists. I can execute all normal tasks with the test user except for uploading a banner.

**Comment by SaturnTeamDev** [comment]
UPDATE: I have installed the latest revision and updated my database. The banner issue has gone away. Thank you!

**Comment by SaturnTeamDev** [comment]
UPDATE: I have installed the latest code revision. The banner issue I was having has gone away. It is fixed. Thank you!
