### ISSUE TITLE
Website addresses in video description improperly formatted

### ISSUE THREAD

**Issue by SaturnTeamDev** [MacWarrior/clipbucket-v5#373]
I was adding a test web address to a video upload description. I expected it to result in a clickable link like it does in the user's website field. Instead, it looks like the following after submitting:
 `<a href="https://Example.com">https://Example.com</a>`
Obviously, CB understands it is a web address but is confused on how to format it in the description box.

**Comment by MacWarrior** [comment]
Hi @SaturnTeamDev, 

Thanks for report, fix is in progress !

Best regards,
MacWarrior.

**Comment by MacWarrior** [comment]
Hi @SaturnTeamDev, 

Issue has been fixed in latest commit

Best regards,
MacWarrior.

**Comment by SaturnTeamDev** [comment]
I just installed the latest update. The links are properly formatted now. Thank you for fixing this!
