### ISSUE TITLE
Fixed Comment Censor plugin

### ISSUE THREAD

**Issue by SaturnTeamDev** [MacWarrior/clipbucket-v5#377]
The old plugin for comment_censor.php is listed in available plugins but it's for version 2 of CB. I looked over the code and couldn't figure out why it wouldn't be compatible. As it turns out, you just need to change the line in comment_censor.php to "ClipBucket Version: 5.5.1". After that, reload the Plugin Manager page and click the checkbox next to the plugin, go down to the bottom of the page, and click "Install Plugins". Once it appears at the top, activate it. After that, just go back into the plugin's php page and add to the banned words list in there. Here is a screenshot of the plugin working in version 5.5.1:
![CommentCensor](https://github.com/MacWarrior/clipbucket-v5/assets/43824646/4e26fc72-72d5-4ddb-8ef3-7afc8c62bd31)

![InstalledPlugins](https://github.com/MacWarrior/clipbucket-v5/assets/43824646/0402bc3c-9216-429d-8a72-b314847ba77c)

**Comment by MacWarrior** [comment]
Hello @SaturnTeamDev,

Old plugins aren't noted as compatible because they haven't been updated / tested
Comment censor has been replaced in latest commits by a configuration in Admin Area > Website configurations > Comments

Best regards,
MacWarrior.

**Comment by SaturnTeamDev** [comment]
Okay. I just installed the latest update and tested the new comment and description censor. It is working. Thank you.
