### ISSUE TITLE
Profile name missing next to "by" under video on channel page

### ISSUE THREAD

**Issue by SaturnTeamDev** [MacWarrior/clipbucket-v5#382]
When users see a video on the Videos page, it says, "by username" under the video. But if they load that user's channel page from the Channels page, the same video just says, "by" under the video. Their name is missing. I'm not sure why.

**Comment by SaturnTeamDev** [comment]
Update: This problem is also affecting videos in the Related sidebar. Usernames have vanished. I was supposed to launch my site today but this has stopped my launch.

**Comment by MacWarrior** [comment]
Hello @SaturnTeamDev,

I'm not reproducing this king of issue on my side ; which version / revision of ClipBucketV5 are you using ?
Latest is 5.5.1 - 55

Please also provide a few screenshots

Thanks by advance,
Best regards,
MacWarrior.

**Comment by SaturnTeamDev** [comment]
Here are the relevant screenshots including the revision screen. This site was created using the automatic installation script.
![IssuePic1](https://github.com/user-attachments/assets/374a6e66-6e70-47bc-b727-2b87109af0d5)
![IssuePic2](https://github.com/user-attachments/assets/4eb3a10b-6cb2-445b-8c41-8460f3fb340d)
![IssuePic3](https://github.com/user-attachments/assets/d1148837-d632-4181-aced-625e4f023de0)

**Comment by MacWarrior** [comment]
Hi @SaturnTeamDev,

Thanks for reply, I was looking at the wrong spot... I'll fit it asap !

**Comment by MacWarrior** [comment]
Hi @SaturnTeamDev,

Issue was fixed on latest revision

Best regards,
MacWarrior.

**Comment by SaturnTeamDev** [comment]
Ouch! This is so frustrating. I was fixing the code myself. Then, I upgraded to your new revision. Now, the username is not showing up on the Videos page and the Collections page! I'm looking through the code to try to figure out how to fix it. I was hopeful I was going to be able to launch my site today. You should run through all the pages to check for these problems. Thank you.

**Comment by MacWarrior** [comment]
Hi @SaturnTeamDev,

It's all about old vs new systems in place... I'll fix it asap...

Best regards,
MacWarrior.

**Comment by SaturnTeamDev** [comment]
Okay. Now, the problem I am having is that the nine preloaded videos on the Channel page are missing the username. When I click to load more, those do have the username next to "by". I am checking the code, but have not found the solution yet, because I don't know what the $display_type is for that section. Here is a screenshot:
![ChannelsIssue](https://github.com/user-attachments/assets/ed1efbff-5f90-486a-8a83-0c6884a71f6b)

**Comment by MacWarrior** [comment]
Hi @SaturnTeamDev, 

I've pushed lots of fixes I've been working on for the last few weeks
I also included a fix for video uploader's username

Best regards,
MacWarrior.

**Comment by SaturnTeamDev** [comment]
> Hi @SaturnTeamDev,
> 
> I've pushed lots of fixes I've been working on for the last few weeks I also included a fix for video uploader's username
> 
> Best regards, MacWarrior.

Okay, I appreciate it. Could you at least tell me what the $display_type is for that preloaded (top nine videos) user channel section? Right now, I am just editing each possible type section and reloading the site to figure out where it is in the code. Thanks.

**Comment by MacWarrior** [comment]
Hi @SaturnTeamDev,

In view_channel.html : 
```
{include file="$style_dir/blocks/videos/video.html" display_type='homeVideos'}
```

**Comment by SaturnTeamDev** [comment]
Okay. I just used my browser's dev tools to identify the display type. It shows "div id="user-videos".

**Comment by SaturnTeamDev** [comment]
I can see now that view_collection.html is saying that Collections and each user channel page both use homeVideos. That seems to be creating some kind of conflict and resulting in only one being able to show the username under the video. I am going to try to copy the code block in the video page html to create a separate display type for Collections.

**Comment by SaturnTeamDev** [comment]
**Revision 57 Update:** I just upgraded the site. Now, I have two problems. The issue I was having on the user channel page is now reversed. The nine preloaded videos show the username. But when I click the "Load More" button, those extra videos do not show the username. There is also a _new_ problem. The _avatar pictures don't show on the main Channels page_. If I load each individual channel page, the avatars show up.

**Comment by MacWarrior** [comment]
Hi @SaturnTeamDev,

Thanks for your returns ; it's always very valuable to get this corrected, so thanks again for reporting them.

1) User's avatar has been fixed in latest commit
2) Channel > Videos tab > Load more has also been fixed in latest commit

Best regards,
MacWarrior.

**Comment by SaturnTeamDev** [comment]
@MacWarrior,

I have upgraded to Revision 60 and can confirm that this issue is now completely **fixed**. Also, the avatars are now working on the Channels page. Thank you for your hard work!
