### ISSUE TITLE
Missing Channel Name on Individual Video Pages

### ISSUE THREAD

**Issue by SaturnTeamDev** [MacWarrior/clipbucket-v5#387]
With the 2nd to last update, the channel names under videos have vanished. It just shows their logo or default logo. Users may forget who uploaded the video they are watching. I have already launched my site now, so this is a glaring error. I am attaching a screenshot:
![Error](https://github.com/user-attachments/assets/e3cdb89c-2326-4c32-97a8-dd36f3abb162)

**Comment by MacWarrior** [comment]
Hello @SaturnTeamDev, 

Thanks for report, issue confirmed ; fix will be available today

Best regards,
MacWarrior.

**Comment by MacWarrior** [comment]
Hello @SaturnTeamDev, 

Issue has been fixed with latest revision

Best regards,
MacWarrior.
