### ISSUE TITLE
Missing Avatar on Video Pages

### ISSUE THREAD

**Issue by SaturnTeamDev** [MacWarrior/clipbucket-v5#389]
Earlier today, the issue was fixed for the channel name not showing up on each video page. Now, with this latest revision, the **avatar next to it is missing**. I would appreciate if this can be fixed. Merci!
![MissingAvatar](https://github.com/user-attachments/assets/dcaa4d41-6e6b-4477-90fb-e870ffdf2bbb)

**Comment by MacWarrior** [comment]
Hello @SaturnTeamDev,

Thanks again for your report.
Unfortunately... issue confirmed ; I see what I can do asap ; at worst it will be fixed on monday

Best regards,
MacWarrior.

**Comment by MacWarrior** [comment]
Hello @SaturnTeamDev, 

Issue has been fixed with last revision.

Best regards,
MacWarrior.
