### ISSUE TITLE
HLS stream instead of mp4

### ISSUE THREAD

**Issue by anhthoai** [MacWarrior/clipbucket-v5#41]
Hello. Do you have plan to add "convert videos to hls"? It will be better than mp4 streaming.

**Comment by MacWarrior** [comment]
Hi, 

There's currently no plan to add specific features.
This looks interesting but may requiere lots of work for implementing it (Upgrade converting, streaming and downloading features)
You should suggest it to the official CB team

**Comment by MacWarrior** [comment]
Hi,

Because of the HLS format, it wouldn't be possible to download a full video file once converted from MP4 to HLS without starting a conversion for the download or conserving a full mp4 file which would result as a double disk space usage

I'm still thinking about this enhancement...

**Comment by MacWarrior** [comment]
Hi,

Just to let you know I'm currently working on implementing HLS conversion
Some parts are already done and working on latests revisions

Best regards,
MacWarrior.
