### ISSUE TITLE
PHP CLI is not correctly configured  and Unable to find PHP CLI

### ISSUE THREAD

**Issue by noglokel** [MacWarrior/clipbucket-v5#416]
Cannot get pass the installation
![Screenshot_20240816_190518_Samsung Internet](https://github.com/user-attachments/assets/6fc1c8ac-dca1-47d4-940c-9890fcd072cf)
![Screenshot_20240816_190531_Samsung Internet](https://github.com/user-attachments/assets/747f65cd-759b-46cf-a482-2b5c7969da2d)
 page

**Comment by MacWarrior** [comment]
Hello @noglokel, 

Issue has already been fixed since ; please update to latest revision 😉 

Best regards,
MacWarrior.

**Comment by noglokel** [comment]
ok
