### ISSUE TITLE
Error : Duplicate entry 'backdrop_delete_successfully' for key 'cb_languages_keys.language_key'   and   importing languages.sql

### ISSUE THREAD

**Issue by noglokel** [MacWarrior/clipbucket-v5#417]
What might this problem be ? 
![Screenshot_20240817_124755_Samsung Internet](https://github.com/user-attachments/assets/24838423-b845-4ee0-90b4-5768ccd4a852)
![Screenshot_20240817_124406_Samsung Internet](https://github.com/user-attachments/assets/ffe4965d-e414-44e8-a99f-787ae600d441)

**Comment by MacWarrior** [comment]
Hello @noglokel ,

First issue is on our side... will fix it asap !
Thanks for report !

Second one is because you re-launched an installation on a non-empty database ; make sure to remove all tables in your DB before re-launching installation

Best regards,
MacWarrior.

**Comment by noglokel** [comment]
ok thanks

**Comment by MacWarrior** [comment]
Hello @noglokel, 

Thanks again for report, issue has been fixed with latest revision

Best regards,
MacWarrior.

**Comment by noglokel** [comment]
great - we will give it a shot.

**Comment by noglokel** [comment]
We sent this in  Error : Duplicate entry 'storage_history' for key 'cb_languages_keys.language_key' #419 
(not sure if it should continue her or as a new one) 
![Screenshot_20240819_180638_Samsung Internet](https://github.com/user-attachments/assets/51a537f8-a773-4623-aa41-bc9ee3425d57)
