### ISSUE TITLE
Error : Duplicate entry 'storage_history' for key 'cb_languages_keys.language_key'

### ISSUE THREAD

**Issue by noglokel** [MacWarrior/clipbucket-v5#419]
We have this error now - 
![Screenshot_20240819_180638_Samsung Internet](https://github.com/user-attachments/assets/a4ff081b-019b-4192-bec4-213a3547cc8b)

**Comment by MacWarrior** [comment]
Hello @noglokel,

I'm terribly sorry for this error, again...
A fix has been published with latest revision

Best regards,
MacWarrior.

**Comment by noglokel** [comment]
ok - we will give it a shot now. thanks
