### ISSUE TITLE
About the debian script installer for beginners

### ISSUE THREAD

**Issue by ekardian** [MacWarrior/clipbucket-v5#421]
The script for debian beginners fail if clone the repository, i don not cap a screenshot but, when i downloaded from the stable like the 5.5.0, this is running good.

The issue is when you need to fill the user db, password db, afther this we press the next the page do not load the next step

other thing, if cb run only in the web root why the script is isntalling in a sub folder like http://localhost/clipbucket/upload

[debian-install](https://github.com/MacWarrior/clipbucket-v5/blob/master/utils/install_debian-ubuntu.sh)

**Comment by ekardian** [comment]
![imagen](https://github.com/user-attachments/assets/2e8a8a35-aa21-4ec2-9cd0-38a616ac1bf2)
Working good in the web root, now i gonna try fix my old db

**Comment by MacWarrior** [comment]
Hello @ekardian, 

You might get some JS error in your browser, please disable all extensions and retry ; also give us any error message you got

Installation script don't use "localhost", it defines a custom local dns like clipbucket.local, and vhost is configured to use it as root directory

Best regards,
MacWarrior.

**Comment by ekardian** [comment]
was installed with the clipbucket.local, and was configured too with the vhost as root directory, but, i had to delete the older directory /var/www , now it work, im not in the machine, tomorrow i gonna share the config apache.conf

**Comment by ekardian** [comment]
Tested in Debian 12.2, apache2
it work with restarting service with apache2ctl with systemctl was not reflecting the new configurations, and comment a part of my apache2.conf that was created with the **script begginer installer for debian 12**

`sudo apache2ctl restart`

with

`sudo systemctl restart apache2 `

i commented this part,  because i saw two web root

```
#<Directory /var/www/>
#       Options Indexes FollowSymLinks
#       AllowOverride None
#       Require all granted
#</Directory>
```

at then end of apache2.conf
```

<Directory /srv/http/>
        Options Indexes FollowSymLinks
        AllowOverride None
        Require all granted
</Directory>
```

my sites-enabled/001-clipbucket.conf
```

<VirtualHost *:80>
    ServerName localhost
    DocumentRoot /srv/http/clipbucket/upload

    <Directory /srv/http/clipbucket/upload>
        Options Indexes FollowSymLinks
        AllowOverride all
        Order allow,deny
        allow from all
    </Directory>

    <FilesMatch .php$>
        SetHandler "proxy:unix:/run/php/php8.2-fpm.sock|fcgi://localhost"
    </FilesMatch>

    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
```

and i restarted with **apache2ctl**, with **systemctl** is not reflecting the new config

`sudo apache2ctl restart`

**Comment by MacWarrior** [comment]
Hello @ekardian, 

Clipbucket isn't compatible with subdirectory for now ; even if pages should load correctly, internal links aren't currently build, some are still hardcoded and simply won't work
This is absolutely something we'll work on as said on #156

Best regards,
MacWarrior.
