### ISSUE TITLE
FATAL Error, need help

### ISSUE THREAD

**Issue by DragonRoberts1** [MacWarrior/clipbucket-v5#441]
![error](https://github.com/user-attachments/assets/fa53e706-4aa2-4579-900e-1670019e495e)

I need some help, please.
Thank you for your time.

**Comment by MacWarrior** [comment]
Hello,

Your PHP timezone seems to be set to "Host" which is not a correct timezone
Try fixing your PHP config until we publish a workaround


Best regards,
MacWarrior

**Comment by DragonRoberts1** [comment]
Now I can't continue: 
![clipbucket](https://github.com/user-attachments/assets/9ecc0834-b798-4dea-8c8f-b6d5102ee81a)

**Comment by MacWarrior** [comment]
Hello @DragonRoberts1, 

Issue must be because of your open_basedir configuration
We've just pushed a fix to handle this issue with latest revision ; please update and retry, but you'll need to update your configuration to be able to setup ClipBucket.

Best regards,
MacWarrior.

**Comment by DragonRoberts1** [comment]
Thank you for your time and help.

Gratefully appreciated,
Dragon
