### ISSUE TITLE
version 148 - delete video remain in video manager 

### ISSUE THREAD

**Issue by noglokel** [MacWarrior/clipbucket-v5#443]
when delete video - the video is deleted by remain video manager  and stall on video delete file

**Comment by MacWarrior** [comment]
Hello @noglokel, 

I have no particular issue on my side ; can you enable dev mode and retry ?
Do you have any PHP error during video deletion ?

Which version / revision are you using, on which host system ?

Thanks by advance,
Best regards,
MacWarrior.

**Comment by noglokel** [comment]
Dev mode
![Screenshot_20240929_103806_Samsung Internet](https://github.com/user-attachments/assets/f618d149-6404-435d-9c55-f6c8a93b5227)
![Screenshot_20240929_103814_Samsung Internet](https://github.com/user-attachments/assets/dee03d49-b505-4462-9f17-94018f292c37)

**Comment by MacWarrior** [comment]
Hello @noglokel, 

On which page do you get this error ?
How have you updated to latest revision ? From admin area ?

Can you show me admin area dashboard ?

Best regards,
MacWarrior.

**Comment by noglokel** [comment]
from admin area 
https://nakenterprisestudio.com/admin_area/video_manager.php?delete_video=2
![Screenshot_20240929_104620_Samsung Internet](https://github.com/user-attachments/assets/136a9515-c251-44cc-97d8-7db39f50bee5)

**Comment by MacWarrior** [comment]
Thanks @noglokel, got it
Fix will be done asap !

**Comment by MacWarrior** [comment]
And, it's fixed with revision 149 !

**Comment by noglokel** [comment]
We went back to version - 138  

This is the test result for deleting a video  CB - version 138 
![Screenshot_20240929_113112_Samsung Internet](https://github.com/user-attachments/assets/01482d35-4b58-4405-a76e-88dc54c56082)
![Screenshot_20240929_113259_Samsung Internet](https://github.com/user-attachments/assets/113db33e-d228-4678-81c8-8b8dd0e3d079)

**Comment by MacWarrior** [comment]
@noglokel Update to revision 149+, where issue has been fixed

**Comment by noglokel** [comment]
yes - fix in version 150
thanks ....
![Screenshot_20240929_115819_Samsung Internet](https://github.com/user-attachments/assets/fc963426-cedb-4275-9cdc-051653159d93)
![Screenshot_20240929_115837_Samsung Internet](https://github.com/user-attachments/assets/bbf56a31-520e-4472-8eda-cc41b4bc20a5)
