### ISSUE TITLE
I want to use www.domain.com

### ISSUE THREAD

**Issue by kxb1991** [MacWarrior/clipbucket-v5#479]
Hello,

I want to use www.domain.com but i have errores...

He did what his friend said.
https://github.com/arslancb/clipbucket/issues/409#issuecomment-343705706

Currently, everything works; however, when I attempt to log in, I am redirected to https://www.domain.com:80/.

Any have solution?

Thanks.

**Comment by kxb1991** [comment]
Hey 
The last version...

I tested all but no solution... vhost other script is working good... wordpress for exemple.

Thanks.

**Comment by MacWarrior** [comment]
Hello @kxb1991, 

I need a precise version : 5.5.0 (latest release) or 5.5.1 (latest version) ?

Sorry, I had absolutely no idea a such redirection existed ; it comes from original files... I'll update it asap

Best regard,
MacWarrior.

**Comment by MacWarrior** [comment]
Hello @kxb1991, 

Issue has been fixed on latest revision (205)

Best regards,
MacWarrioor.

**Comment by kxb1991** [comment]
Hello,

I installed 5.5.0, i update files... but same problem... when i go to login page https://www.domaine.com/ after login i redirect to https://www.domaine.com:80, I use litespeed open, Wordpress is working, other CMS is working PHPBoost...

**Comment by kxb1991** [comment]
I think the probleme is when script create session... when i remove all sessions in database is working in first time... but after generate the first session... al redirecto to :80

**Comment by MacWarrior** [comment]
Hello @kxb1991, 

Fix has been done on latest version 5.5.1, please update to latest version for fix

Best regards,
MacWarrior.

**Comment by kxb1991** [comment]
I update files... same problem.

**Comment by MacWarrior** [comment]
Hello @kxb1991,

Can you show me a screenshot of your admin area > Dashboard > Update status ?

Best regards,
MacWarrior.

**Comment by MacWarrior** [comment]
Hello @kxb1991, 

I just tested with a www. domain and there is no more redirection
If you still have issue, it comes from your browser cache or your server setup (probably vhost)

Best regards,
MacWarrior.
