### ISSUE TITLE
Docker MariaDB Issue

### ISSUE THREAD

**Issue by tiritibambix** [MacWarrior/clipbucket-v5#486]
Hello!  
I've been on the lookout for a good video hosting solution that I can use with Docker for quite some time now. I've done quite a bit of Googling, browsing Reddit, and checking out awesome-selfhosted, but I hadn't come across ClipBucket until recently, thanks to... Mistral.

The project seems fantastic, and I'm eager to give it a try, so I followed the documented instructions for Docker:

1. **Build the Docker Image:**

```shell
docker build -t clipbucket https://github.com/MacWarrior/clipbucket-v5.git#master
```

2. **Run the ClipBucket Container:**

```shell
docker run \
--restart unless-stopped \
-e DOMAIN_NAME=clipbucket.local \
-e MYSQL_ROOT_PASSWORD=clipbucket_password \
-v clipbucket_db:/var/lib/mysql \
-v clipbucket_files:/srv/http/clipbucket \
-p 80:80 \
-d --name clipbucket clipbucket
```

However, when I check the container's log, I see  
```
Starting MariaDB database server: mariadbd failed!
```

I also noticed the section for "advanced users" mentioning a database that needs to run with ClipBucket.  
I’m definitely not an advanced user; I’m still pretty new to this.  
Does that mean I can't run ClipBucket? Are there any additional instructions available to help make it work properly?

Thanks so much for your help!

**Comment by MacWarrior** [comment]
Hello @tiritibambix, 

Thanks for your report.
We've been testing our docker setup on multiples configurations (Windows 10, 11, synology) without any particular issue

On what system did you tried to install our docker ?

"Advanced users" is for users wanting to install ClipBucket manually, without docker ; you don't have to worry about it in your case 😉 

Best regards,
MacWarrior.

**Comment by tiritibambix** [comment]
Thanks for your answer.

I'm running docker on an amd64 machine with Debian.

I'm not sure what additional nformations I could give you to solve this issue, so please, ask.

**Comment by tiritibambix** [comment]
Thank you for your answer.
Just so you know, I tried removing the port in domain name but got the same error.

**Comment by nvanhaezebrouck** [comment]
Hello!

The issue you are encountering could indeed be related to volume conflicts. If multiple Docker containers are attempting to use the same volume for the database (e.g., clipbucket_db), it can lead to errors like the one you described. To troubleshoot and resolve the problem, I recommend trying the following steps:

### 1. Use a Different Volume: 
Modify your docker run command to use a new volume name for the database. For example:

```bash
docker run \
--restart unless-stopped \
-e DOMAIN_NAME=192.168.1.104:6598 \
-e MYSQL_ROOT_PASSWORD=clipbucket_password \
-v clipbucket_db_new_volume:/var/lib/mysql \
-v clipbucket_files:/srv/http/clipbucket \
-p 6598:80 \
-d --name clipbucket_test clipbucket
```
This creates a fresh volume (clipbucket_db_new_volume) for MariaDB to use, avoiding potential conflicts with other containers.

### 2. Check for Conflicting Containers: 
Ensure no other containers are currently using the clipbucket_db volume. You can list all running containers and their associated volumes with the following commands:

```bash
docker ps
docker volume ls
```
If you find any containers using the conflicting volume, stop or remove them before retrying.

### 3. Clean Up Stale Volumes: 
If you're sure no other containers need the clipbucket_db volume, you can safely remove it using:

```bash
docker volume rm clipbucket_db
```
Be cautious with this step as it will delete any data stored in the volume.

### 4. Verify Logs: 
After making the changes, start your container and check the logs again to ensure MariaDB starts successfully:

```bash
docker logs clipbucket
```

Best regards , nicolas

**Comment by tiritibambix** [comment]
Thank you Nicolas.

Your answer had me thinking...

I dont use docker volumes but bind volumes instead.
So my command looks more like this:
```
-v /srv/dev-disk-by-uuid-7fe66601-5ca0-4c09-bc13-a015025fe53a/Files/Clipbucket/db:/var/lib/mysql
-v /srv/dev-disk-by-uuid-7fe66601-5ca0-4c09-bc13-a015025fe53a/Files/Clipbucket/files:/srv/http/clipbucket
```

Is this a problem ?

**Comment by nvanhaezebrouck** [comment]
I've been working since yesterday to improve the Dockerfile and find a stable solution to your issue. I completely understand your preference for bind mounts due to their flexibility and compatibility with your backup routine. I'm continuing to look for a way to make bind mounts work seamlessly with ClipBucket while ensuring everything functions properly.

I'll keep you updated as soon as I have any progress. Thank you for your patience! 😊

**Comment by tiritibambix** [comment]
No... Thank YOU for your patience!

I can't wait to see your progress :)

**Comment by nvanhaezebrouck** [comment]
We just deployed a new version of the Dockerfile to address your issue.

Here are the changes:

- MYSQL_ROOT_PASSWORD has been renamed to MYSQL_PASSWORD.
- Added UID and GID support.
- Created an official Docker Hub repository.

To find your UID and GID, you can use the command `id username` on Debian.

Here’s the updated command to run the container:

```bash
docker run \
--restart unless-stopped \
--pull=always \
-e DOMAIN_NAME=192.168.1.104:6598 \
-e MYSQL_PASSWORD=clipbucket_password \
-e UID=1000 \
-e GID=1000 \
-v /srv/dev-disk-by-uuid-7fe66601-5ca0-4c09-bc13-a015025fe53a/Files/Clipbucket/db:/var/lib/mysql \
-v /srv/dev-disk-by-uuid-7fe66601-5ca0-4c09-bc13-a015025fe53a/Files/Clipbucket/files:/srv/http/clipbucket \
-p 6598:80 \
-d --name clipbucket clipbucket
```
All the details can be found in the README file.

It seems you created a Docker Hub repository. If you no longer need it, could you delete it? We've set up an official version now.

Also, make sure to delete the contents of:
/srv/dev-disk-by-uuid-7fe66601-5ca0-4c09-bc13-a015025fe53a/Files/Clipbucket/db
/srv/dev-disk-by-uuid-7fe66601-5ca0-4c09-bc13-a015025fe53a/Files/Clipbucket/files
This will ensure a clean new installation.

Thank you! 😊

best regards Nicolas.

**Comment by tiritibambix** [comment]
Damn, that was quick. Thanks a lot for your work !

I just had to change UID and GID to PUID and GUID.
Also add image name to pull oxygens/clipbucket-v5.
Install screen keeps ommiting port number but that's no big deal.

I deleted my repo from DockerHub :)

If anyone is interested, here is the docker-compose I used:
```
services:
  clipbucket:
    restart: unless-stopped
    pull_policy: always
    environment:
      - DOMAIN_NAME=
      - MYSQL_PASSWORD=clipbucket_password
      - PUID=
      - GUID=
    volumes:
      - ./Clipbucket/db:/var/lib/mysql
      - ./Clipbucket/files:/srv/http/clipbucket
    ports:
      - xx:80
    container_name: clipbucket
    image: oxygenz/clipbucket-v5
```

Thanks again for your patience and dedication.
I'll have some time to tinker with Clipbucket next week. I can't wait :)

**Comment by MacWarrior** [comment]
Hello @tiritibambix, 

Thanks for your fast response

Custom port & base url issue has been fixed with latest revision (225)

Best regards,
MacWarrior.

**Comment by tiritibambix** [comment]
Thanks lot. You rock !
