### ISSUE TITLE
Incorrect Redirect After Update to Revision 227

### ISSUE THREAD

**Issue by Trabizon61** [MacWarrior/clipbucket-v5#492]
After the update to revision 227, I noticed an issue. When I go to the "Videos" section, it works fine, but when I click on "Channels," the page is not found and I get a 404 error. If I then go back to "Videos," the link changes to https://example.TLD/videos/channels/videos/, which seems to be an issue caused by the update or fix. 

However, when I click on "Channels" from the homepage, I can access the Channels page. But if I click on "Channels" again, I get the same error, and the URL changes to https://example.TLD/channels/channels/. It seems like there is a redirect issue after the update.

Please check it, thanks

**Comment by MacWarrior** [comment]
Hello @Trabizon61, 

URL examples given tell me you use SEO URLs

Do you use Apache or Nginx ?
If Nginx, you might have some vhosts issues (Check [Installation guide](https://github.com/MacWarrior/clipbucket-v5/wiki/ClipBucketV5-installation-guide))

Are you logged in when redirect occure ?

This seems OK on my side : 
![Capture d’écran 2024-12-18 162956](https://github.com/user-attachments/assets/453d5e4e-d8b0-4841-a8aa-9e6bc8c08637)

Best regards,
MacWarrior.

**Comment by MacWarrior** [comment]
@Trabizon61 My bad, I just reproduced your error ; will check it asap !

**Comment by Trabizon61** [comment]
> @Trabizon61 My bad, I just reproduced your error ; will check it asap !

No problem :) Thank you.
