### ISSUE TITLE
suggestion for collection Videos to make like playlist please

### ISSUE THREAD

**Issue by spirogg** [MacWarrior/clipbucket-v5#56]
hi when we add videos to a collection and we click on the collection, after clicking on a video in the collection we should still see the rest of collection

![capture](https://user-images.githubusercontent.com/17736688/45601517-a1e24a00-b9d3-11e8-917f-7c263aa78769.JPG)
![capture1](https://user-images.githubusercontent.com/17736688/45601518-a1e24a00-b9d3-11e8-9fe1-f4fee240c883.JPG)

this would make sense, so if someone wants to view my collection of videos its kinda like the playlist

not sure how hard to do this but would be cool

:) thanks 

Spiro

**Comment by MacWarrior** [comment]
Hi, 
Maybe just addign a "Related to" space on the sidebar ?
Will think about it

**Comment by spirogg** [comment]
@MacWarrior don't forget related doesn't show for photos #26 , not sure why?
