### ISSUE TITLE
i got email about groups ? was this because subscribe and because not working?

### ISSUE THREAD

**Issue by spirogg** [MacWarrior/clipbucket-v5#57]
I got this email, is this possibly because of the subscribe button and since I click on it, and it doesn't work it still send me an email?

```
admin invited you to join the Mi Tube group "{group_name}".

{group_description}

To see more details and confirm this group invitation, follow the link below:
{group_url}

Thanks,
Mi Tube
```

**Comment by MacWarrior** [comment]
Hi,

Confirmed, this email comes from the subscription button
All emails (almost) are not functionnals, I will work on it but it will be long ! :)

**Comment by MacWarrior** [comment]
Ok, so i've removed everything related to groups, now I have to refactor almost every emails, wish me good luck 😉

**Comment by spirogg** [comment]
@MacWarrior Good Luck :)

But I really want to thank you for all your hard work. You are making this awesome. 

So thank you thank you. !!!!

Regards 

Spiro.

**Comment by spirogg** [comment]
@MacWarrior I don't think this is finished yet, but just for fyi
- I cannot save the templates to emails If I try to change them to my own words

![capture](https://user-images.githubusercontent.com/17736688/46322148-edd4e780-c5ac-11e8-9324-0f18ad8e81ae.PNG)
