### ISSUE TITLE
user avatar - photo gives error not able to upload see photo

### ISSUE THREAD

**Issue by spirogg** [MacWarrior/clipbucket-v5#65]
hi im using the latest and did fresh install just 5 mins ago,
when i try to upload an avatar or image for my user pic. it give me an error 

I even tried to upload my picture in admin area still gives error

![capture](https://user-images.githubusercontent.com/17736688/46309605-683c4200-c582-11e8-98d1-436bed29c295.PNG)
![capture](https://user-images.githubusercontent.com/17736688/46311743-c835e700-c588-11e8-81a4-4102bf2df0dd.PNG)
![capture1](https://user-images.githubusercontent.com/17736688/46311745-c835e700-c588-11e8-8bf1-d6354277b3eb.PNG)

**Comment by spirogg** [comment]
![capture](https://user-images.githubusercontent.com/17736688/46309694-b6e9dc00-c582-11e8-8844-b7e04e409b9e.PNG)

**Comment by spirogg** [comment]
Also when you turn off picture url in admin_area, when you go to user pic upload area the field is still showing

**Comment by spirogg** [comment]
Hi @MacWarrior  /files/avatars/  does not exist
I will re-download master and see if it creates  /files/avatars/ 
5 mins i will reply

**Comment by spirogg** [comment]
ok no /files/avatars/ is created with install I will create the file and see if it works
i will reply in 2 mins

**Comment by spirogg** [comment]
latest update 5 mins ago re-downloaded master and even after install it does not create this folder /files/avatars 
![capture](https://user-images.githubusercontent.com/17736688/46319987-e2c88a00-c5a1-11e8-8fb5-19bba98fe24d.PNG)


- after i create this folder /files/avatars it is working now

thank you so much
![capture1](https://user-images.githubusercontent.com/17736688/46319988-e2c88a00-c5a1-11e8-83e7-03b37e96ab7c.PNG)

**Comment by spirogg** [comment]
Question: 
is there no background area to upload background or background URL?

 will you remove this from admin_area or fix it so it works?

**Comment by MacWarrior** [comment]
Hi,
Thanks for replies, I must have made a mistake, will fix it asap

**Comment by MacWarrior** [comment]
Background may be only for channels, will check it too

**Comment by spirogg** [comment]
Thank you for fixing this 

- Also when you turn off picture url in admin_area, when you go to user pic upload area the field is still showing. it now goes away when you turn off 🥇

**Comment by spirogg** [comment]
PS you must add in your repo the folder /files/avatars so when someone else download from github it is already available and will work :)

**Comment by MacWarrior** [comment]
Hi,

Missing avatars directory fixed in this commit : 8c4a52b9edd1a63cb51f4aff9dc1c2f8a86957d7

**Comment by spirogg** [comment]
Is this the only thing left as enhancement? 

Background may be only for channels, will check it too

Just for my.logs :)
