### ISSUE TITLE
when adding a collection - the page stays on even after you create collection ?

### ISSUE THREAD

**Issue by spirogg** [MacWarrior/clipbucket-v5#67]
hi after creating a collection, and you submit to create the collection, can you make it go back to upload photos so we don't have to click on upload photos again?

otherwise, you are stuck on the same page (collections) and confuse users
 (what to do next or is it finish ?? did I created collection already ???) 

see photo, after I create a collection, and click add collection it stays on same page

![capture](https://user-images.githubusercontent.com/17736688/46320494-4eabf200-c5a4-11e8-9443-458816668eaa.PNG)

**Comment by spirogg** [comment]
`$("#uploadMessage").addClass("hidden");
									window.location = "/photo_upload.php";
								}, 1000);`

**Comment by MacWarrior** [comment]
Hello @spirogg,

I just finished to refactor photo upload and this was included ! 👍 

Best regards,
MacWarrior.
