### ISSUE TITLE
Tags area: can you make tags easier to add instead of adding comma ?

### ISSUE THREAD

**Issue by spirogg** [MacWarrior/clipbucket-v5#68]
Hi, first I would like to know if you can make tags when you enter a word and press spacebar or click outside of tags the word is created with a small x where we can click to delete the tagged words

example: Music x  Photos x  Movies x 

![capture1](https://user-images.githubusercontent.com/17736688/46320763-7cde0180-c5a5-11e8-8d2c-76d0d617632c.PNG)

if its too hard can you make example text next to the word tags so people know to use a comma
  Music, Photos, Movies

![capture](https://user-images.githubusercontent.com/17736688/46320787-98e1a300-c5a5-11e8-96af-5a556acf1d1e.PNG)

**Comment by MacWarrior** [comment]
Hello @spirogg,

Easy tag input has been implemented on last commit

Best regards,
MacWarrior.
