### ISSUE TITLE
update cover photo with .jpg file gives error : File extension error.

### ISSUE THREAD

**Issue by spirogg** [MacWarrior/clipbucket-v5#69]
hi, I have in admin_area
allow these extensions:
 jpg,jpeg,png

jpg doesn't work give an error: File extension error.
jpeg works
png works

![capture](https://user-images.githubusercontent.com/17736688/46321554-86696880-c5a9-11e8-8bde-eca12f3cd1ba.PNG)

**Comment by spirogg** [comment]
Also if we upload a cover photo and just want to remove it and use the default cover photo, is there a way to make this an option? 

Idea
- when we mouse over the update cover photo we can then have 2 options:
1) upload cover (as we have now) 
2) delete the cover photo ( or revert to default) 

It would be nice to be able to delete the cover photo and use the default if a user wanted to

**Comment by spirogg** [comment]
Also maybe a way to reposition photo. If height is larger or.more.white space up the r down ?

Idea :
upload cover photo
reposition cover photo
Remove cover photo (reverts to default)

**Comment by MacWarrior** [comment]
Hi,

When do you get that error ? Can you provide a screenshot ?

**Comment by MacWarrior** [comment]
Ok, got it on background update with .jpg file

**Comment by MacWarrior** [comment]
Hi,

The format error has been fixed on last commit

**Comment by spirogg** [comment]
ok works
