### ISSUE TITLE
ffmpeg says nothing there but mine is correct /usr/local/bin/ffmpeg

### ISSUE THREAD

**Issue by spirogg** [MacWarrior/clipbucket-v5#7]
![ffmpeg is correct path and working when upload](https://user-images.githubusercontent.com/17736688/40581602-c1787af6-6122-11e8-825b-fdaa0d7f4fbf.PNG)
![ffmpeg shows not there but i can upload videos and they convert](https://user-images.githubusercontent.com/17736688/40581604-c1862fc0-6122-11e8-9871-72f235415cb8.PNG)

**Comment by MacWarrior** [comment]
Hi, 

Found this today ; didn't have time to fix yet

Please try on your server and send me result : 
`ls /usr/local/bin/ffmpeg`

**Comment by spirogg** [comment]
server1:~# ls /usr/local/bin/ffmpeg
/usr/local/bin/ffmpeg

**Comment by MacWarrior** [comment]
Hi
I've been working on the installation process and specially on software path saving during the installation process.
Can you try again with latest revision ?

**Comment by MacWarrior** [comment]
Hi,

There was many things badly done about dependancies and software paths.
I've made some fix about this ; can you still reproduce with latest revision ?

**Comment by spirogg** [comment]
this is working now perfectly thanks
