### ISSUE TITLE
xss

### ISSUE THREAD

**Issue by pnemuk** [MacWarrior/clipbucket-v5#79]
first I want to thank you for having done so much work.
I found xss on search page can you confirm that?

`http://demo.clipbucket.com/free/search_result.php?query=video&type="><script >alert(String.fromCharCode(88,83,83))</script>`
![clipbucket_xss](https://user-images.githubusercontent.com/17758303/50533949-0d8c9500-0b35-11e9-864c-8e50ac5ac0c7.png)

**Comment by MacWarrior** [comment]
Hi,
I can't reproduce this on my repo ; your exemple is on the official one

So I this this is already fixed here :smile:

But thanks for report !

**Comment by pnemuk** [comment]
Okay I just downloaded your repo and fresh install, but unfortunately xss also performed on your repo.
![clipbucket_new_repo_xss](https://user-images.githubusercontent.com/17758303/50541632-0e134300-0baa-11e9-840a-3bcdd0c15230.jpg)

**Comment by spirogg** [comment]
@MacWarrior ?

**Comment by MacWarrior** [comment]
Hi,

Got it : it was only reproducible on dev environment and I tested on my live environment
Fixed on last commit

**Comment by pnemuk** [comment]
its not fixed yet please test again.

**Comment by MacWarrior** [comment]
Hi,
Can you retry with updated sources from my repo ?

Just tested id now and is works well : 
![capture](https://user-images.githubusercontent.com/200590/50546885-b0c1d500-0c2f-11e9-99b8-0881664941ea.jpg)

**Comment by MacWarrior** [comment]
Ok, I have another error in that case : blank page
Working on it

**Comment by MacWarrior** [comment]
Hi,

I think we're good with last commit, can you confirm ?

**Comment by pnemuk** [comment]
just downloaded, tested and i can confirm that xss is fixed.
nice work, please do not stop updating this repo.

**Comment by spirogg** [comment]
@MacWarrior nice work !!! You are awesome HAPPY NEW YEAR !! 
This repo is awesome #1

**Comment by MacWarrior** [comment]
Hi,

Thanks for your replies and thanks for your encouragements
Happy anticipated new year to you too

**Comment by pnemuk** [comment]
I found new XSS.
Can you confirm?

/search_result.php?query="><script>alert%28document.cookie%29<%2Fscript>&type=videos

**Comment by MacWarrior** [comment]
Hello @pnemuk,

Issue confirmed, thanks for report ! Fixing it...

Best regards,
MacWarrior.

**Comment by MacWarrior** [comment]
Hello @pnemuk, 

XSS fixed on last commit, thanks again !

Best regards,
MacWarrior.
