### ISSUE TITLE
upload photo and add collection not working right either

### ISSUE THREAD

**Issue by spirogg** [MacWarrior/clipbucket-v5#81]
go to upload photo then on fresh install it asks to create collection I add title description tags select uncategorized and submit then i wait and nothing is happening.. then i go to look if there is collection it is created but never said collection was added

**Comment by spirogg** [comment]
![capture](https://user-images.githubusercontent.com/17736688/50585158-4a100780-0e39-11e9-8f39-51ab412f27b2.PNG)

**Comment by MacWarrior** [comment]
Hi,

I had a similar issue while working on PHP 7.3.X compatibility.
Can you retry with latest version ?

Thanks by advance

**Comment by spirogg** [comment]
ok works  now perfect
