### ISSUE TITLE
mobile view the upload wording is off

### ISSUE THREAD

**Issue by spirogg** [MacWarrior/clipbucket-v5#82]
hi when view with mobile android not sure abiyt Iphone since i dont have,

but the wording upload is off to the right and not show unless you scroll right to see all the way

see photo

thanks 

![capture](https://user-images.githubusercontent.com/17736688/50585059-c1916700-0e38-11e9-8afc-2ef5296b3aca.PNG)

**Comment by spirogg** [comment]
![capture](https://user-images.githubusercontent.com/17736688/50585086-e7b70700-0e38-11e9-9bb0-669b42fd0f17.PNG)

**Comment by spirogg** [comment]
anyway to remove the wording and that would fix the issue I Guess simple solution. people will know what that means

**Comment by MacWarrior** [comment]
Hello @spirogg, 

It's been a long time, but this precise issue has been fixed recently !

Best regards,
MacWarrior.
