### ISSUE TITLE
photo share / embed direct link just shows url of site nothing else at end ?

### ISSUE THREAD

**Issue by spirogg** [MacWarrior/clipbucket-v5#83]
here is photo, the share / embed doesn't show **direct link** just url of website

should be direct link to photo yes ?
everything else seems ok for share /embed just the direct link 

![capture](https://user-images.githubusercontent.com/17736688/50585278-d6222f00-0e39-11e9-8261-a3c6dc7abda8.PNG)

**Comment by spirogg** [comment]
Ok maybe we remove this area so no direct link at all will show for video or photo just leave the rest :)

**Comment by spirogg** [comment]
- Question - what are your folder permissions ? 
im doing fresh install again just uploaded - so i want to know what folders you have 777 or 755 etc please

**Comment by spirogg** [comment]
- here it is again
- same issue - direct link
- 
![capture](https://user-images.githubusercontent.com/17736688/50730444-6cdd3d00-1113-11e9-9bff-3b384c748d22.PNG)
![capture1](https://user-images.githubusercontent.com/17736688/50730445-6f3f9700-1113-11e9-9015-e260350fd7f4.PNG)

**Comment by spirogg** [comment]
@MacWarrior any luck on this one 

still as of 6/07/2020 the link is just the url only http://domain.tld/

**Comment by MacWarrior** [comment]
Hi, 

Can you add an updates screenshot ?
In my case (default installation ; PHP 7.3), all URLs (Html, Forum, Email, Direct) are full with direct URL to the image : 
Html : `<a href='https://test.fr/view_item.php?item=2B9BYUO3OYOY&type=photos&collection=1' target='_blank'><img src='https://test.fr/files/photos/2020/06/07/15915487258b1cb6_l.png' title='work' alt='work Clipbucket DEV' /></a>`
Forum : `[URL=https://test.fr/view_item.php?item=2B9BYUO3OYOY&type=photos&collection=1][IMG]https://test.fr/files/photos/2020/06/07/15915487258b1cb6_l.png[/IMG][/URL]`
Email : `https://test.fr/view_item.php?item=2B9BYUO3OYOY&type=photos&collection=1`
Direct : `https://test.fr/files/photos/2020/06/07/15915487258b1cb6_l.png`

**Comment by spirogg** [comment]
hi here it is 

![Capture](https://user-images.githubusercontent.com/17736688/83978696-d7794600-a8ce-11ea-90f8-938bfe90139d.PNG)

**Comment by spirogg** [comment]
> * Question - what are your folder permissions ?
> * im doing fresh install again just uploaded - so i want to know what folders you have 777 or 755 etc please

755 
and SEO ON
I will try and turn off SEO and see if makes a difference

**Comment by spirogg** [comment]
i turned SEO Off same still not showing.. What Chmod do you have ? 755 or 777
i tried php7.2 and 7.3 
I am using cPanel latest version v 88.0.7 
CENTOS 7.8
 MariaDB 10.3.23  
PHP Version 7.3.18

**Comment by spirogg** [comment]
**HTML:** <a href='https://minecraft.com/item/photos/3/D2BK9GN9N334/editorspick1' target='_blank'><img src='https://minecraft.com/' title='editorspick1' alt='editorspick1 Minecraft' /></a>
**EMAIL:** https://minecraft.com/item/photos/3/D2BK9GN9N334/editorspick1
**FORUM:** [URL=https://minecraft.com/item/photos/3/D2BK9GN9N334/editorspick1][IMG]https://minecraft.com/[/IMG][/URL]
**DIRECT:** https://minecraft.com/

**Comment by MacWarrior** [comment]
Hi, 

This is ... weird !

- To simplify your usage and update process, you should really consider using git to copy sources :  
`git checkout https://github.com/MacWarrior/clipbucket-v5.git` will create an updated copy of repo
`git pull` will update an existing copy of repo

- I've tried both SEO URLs and standard URLs with no real difference : everything's fine from my side

- How do you access to the photo's page ? From my side, I use the top menu Photos, then I click to my photo to arrive on a page like this : https://test.fr/item/photos/1/2B9BYUO3OYOY/work

- Your logo and avatar aren't the default ones : did you voluntary modify them ? From back office or directly from files ?

Best regards,
MacWarrior.

**Comment by spirogg** [comment]
I just used the fit process your talking about. Going to reinstall everything and see 
New install
- I use same process to access photos 

- I changed logo and favicon  frombackoffice testing to make sure it works that's why

**Comment by spirogg** [comment]
QUESTION:```
 To simplify your usage and update process, you should really consider using git to copy sources :
git checkout https://github.com/MacWarrior/clipbucket-v5.git will create an updated copy of repo
git pull will update an existing copy of repo
```
- ok so I've managed to get git to work on my cPanel account

- So now do I just copy over all folders and files from upload folder to my public_html folder correct?
- then when I want to update a change how do I go about doing that? just upload the files that changed ? 
- I see you always say to others don;t forget to update sql? 
how do we do that I am not sure how to do that. 

- also one last question - if I upload all folders and files to current install I see offline mode?
how do we turn back to online mode

thanks for all your help

**Comment by spirogg** [comment]
@MacWarrior ok now its got the correct links :) WOW that was really weird if I uploaded yesterday the.zip file and uploaded the files it was not working, Now I did the github pull as you suggested and then copied over the folders > files and reinstall and its working.. picture links seem to be showing properly now
will close after I test a few more times SEO ON / OFF and add favicon and logo from backoffice, plus add more collections etc.. after well tested I will close if this issue is gone thanks so much

Spiro

**Comment by spirogg** [comment]
OK I have found the issue of the link not showing

- when you install CB and clicking on photos you get an error 

**"Kindly install Server Thumb plugin by going to Plugin Manager to make photos show properly"**

When we go to plugins and we install this plugin 
- photos show inline perfectly square..
- other wise it does not align properly on the website.

- "ISSUE if you do not install this plugin"

1) see photo below, the photos are not align properly not square. 

![install-plugin-for-photos-to-align-properly](https://user-images.githubusercontent.com/17736688/83983274-84b18580-a8f2-11ea-9d3b-4f794e72f218.PNG)

- share URL Links work correctly with out plugin installed.
 
if you look at the share links they do work when this plugin is not installed or activated
![plugin-not-installed-or-deactivated-links-show-properly](https://user-images.githubusercontent.com/17736688/83983300-b7f41480-a8f2-11ea-823e-b82304f8a327.PNG)

ok so far just photos need to be aligned

If we install this plugin mentioned above then the links do not show properly as I had installed this plugin always to make the photos square and align properly.
- not thinking to try and deactivate to see if this was the issue and IT IS THE ISSUE...

**_when you activate this plugin you can not get the proper Direct link to show._**

**wow finally found this issue**
- was driving me crazy :)

I hope we can either fix the plugin to show the direct link or even better if we can remove it and align the photos properly so that they are square and even aligned,
Maybe we can incorporate the plugin into CB core files so it will not be needed and be part of CB core functionality :)
your the man so what ever you decide.. 

- possibly if you fix it can it be installed automatically when we install CB so we don't have to go to plugins and we won't see the issue popup when we upload a photo

thanks again for all your replies and hard work as well 👍 😎
your the MAN 🥇

**Comment by MacWarrior** [comment]
Hi,

Thanks for all your investigations !
Will try to make something about it after my work day 😄

Best regards,
MacWarrior.

**Comment by spirogg** [comment]
@MacWarrior 
- do you have a Paypal donations link or a button for donations ? 

I would like to give you a little donation for doing all this work if you would accept..

- I Really appreciate all your hard work, Just wanted to make sure you know your hard work is appreciated. 

Sincerely,
Spiro

**Comment by MacWarrior** [comment]
Hi,

Last commit should finally fix this issue ; thanks again for your investigations !

I do really appreciate all your comments and compliments, it's heart warming to see someone using my work and even more when I get feedbacks !
I wasn't planning on creating a donation link, but as it's not me who is asking for donation, I'll make it 😉

I was already planning to refactor the readme file ; it will just be another link to add 😄 

Best regards,
MacWarrior.

**Comment by spirogg** [comment]
ok fix with last update with Plugin installed and activated thanks so much works
