### ISSUE TITLE
when adding a video to collections it adds but doesnt say anything until refresh

### ISSUE THREAD

**Issue by spirogg** [MacWarrior/clipbucket-v5#92]
hi so i choose a video and click on add to collection, it give some color bar (see photo) with no wording but the number of videos in collection stay the same until you refresh page (see my photos - the first one I added video and stays at 1 video but should show 2 videos, after i refresh the page then it shows 2 videos correctly)  I think it should just add it and say video added to collection and show the number 2 (in my case) and not have to refresh if possible or at least say it added the video in the colored bar above so users know it was added to there collection

- before refresh just a bar shows with no wording to say its been added and number stays at 1 when it suppose to be 2 videos ive added to collection
- ![capture](https://user-images.githubusercontent.com/17736688/50670111-e0a20d00-0f8e-11e9-87ec-7293fbc497e2.PNG)
- after I refresh page then it shows 2 videos properly.
- ![capture](https://user-images.githubusercontent.com/17736688/50670128-fe6f7200-0f8e-11e9-8dfa-092337177a42.PNG)

**Comment by MacWarrior** [comment]
Hi,
When adding a video to a collection, i got a green validation message : 
![capture](https://user-images.githubusercontent.com/200590/50722962-7779e100-10d7-11e9-8e52-3afc5cd482bd.PNG)

Do you get any PHP/JS error ?

For the number increment, it's an enhancement :smile:

**Comment by spirogg** [comment]
- no errors i can see using php7.0 

- i try to use php7.1 - 7.2 not working for me submit button for photo not allow to click on submit so i use php7.0

**Comment by MacWarrior** [comment]
Setting up a VM to check PHP 7.2...

**Comment by MacWarrior** [comment]
I confirm some PHP 7.1+ issues ; will fix asap

**Comment by spirogg** [comment]
collection works with php7.2 now thanks
