### ISSUE TITLE
Problems with Page of Modules and Video Conversion

### ISSUE THREAD

**Issue by raiancollyn** [MacWarrior/clipbucket-v5#96]
Hello good afternoon all right?

I downloaded the most recent version of your project for testing, I noticed 2 problems.
One of them was on the screen of "Tool Box -> Server Modules Info"

![image](https://user-images.githubusercontent.com/20705376/51925962-e690df80-23ce-11e9-9fbf-25b9d3abbe67.png)
All modules are working, except the FFMPEG

I found it strange, therefore, looking at the Console, I found the FFMPEG in my hosting in 2 ways, both are these:

> /usr/local/bin/ffmpeg
> /usr/bin/ffmpeg

And all are set up correctly, see:
![image](https://user-images.githubusercontent.com/20705376/51926162-6ae36280-23cf-11e9-9935-46e53e4c655e.png)

I thought it was strange, so I decided to try sending a video to see the result, at the end of the submission, I got an error in the video, and when I went to look at the log, it was like this:
[log_conversion.txt](https://github.com/MacWarrior/clipbucket-5.0/files/2808774/log_conversion.txt)

I noticed that in some lines it renounces the error that the file does not exist, but if I try to access the directory, the files are in the folder, and if I try to access the file by the HTML address, it downloads the file, it exists, as it is in the case of this example:
![image](https://user-images.githubusercontent.com/20705376/51926426-0bd21d80-23d0-11e9-9917-ac3dd17be0e6.png)
![image](https://user-images.githubusercontent.com/20705376/51926675-8733cf00-23d0-11e9-9eff-4155c0d5a222.png)

Problems with fear permissions other than, as in another reported problem, have suggested setting the permissions for the "files" folder to 777
Am I setting something wrong? Could you help me with this problem?
Thank you in advance for your attention and have a nice day.

**Comment by spirogg** [comment]
Have you tried to check
Command line
 which ffmpeg 
Where is ffmpeg

Also have you type in command line

ffmpeg

If you can please post here those output

**Comment by spirogg** [comment]
Also type which and whereis 

For MP4Box
mediainfo
mplayer
ffprobe

**Comment by spirogg** [comment]
Which version of php do you use ? 5.6 7.0 7.1 7.2 ?

**Comment by raiancollyn** [comment]
Command: ffmpeg
![image](https://user-images.githubusercontent.com/20705376/51983898-ac7c1800-2478-11e9-821c-841083318f30.png)

Command: ffmpeg -version
![image](https://user-images.githubusercontent.com/20705376/51983838-7ccd1000-2478-11e9-8b1b-c153f845f6d7.png)

My Server uses the following features for PHP 7.0.29:
[phpinfo().pdf](https://github.com/MacWarrior/clipbucket-5.0/files/2812793/phpinfo.pdf)

These logs are provided by the SSH command lines
Log of path: /usr/local/bin/ffmpeg
[log_console_ffmpeg.txt](https://github.com/MacWarrior/clipbucket-5.0/files/2812725/log_console_ffmpeg.txt)

Log of path: /usr/local/bin/MP4Box
[log_console_mp4box.txt](https://github.com/MacWarrior/clipbucket-5.0/files/2812771/log_console_mp4box.txt)

Log of path: /usr/bin/mediainfo
[log_console_mediainfo.txt](https://github.com/MacWarrior/clipbucket-5.0/files/2812805/log_console_mediainfo.txt)

Log of path: /usr/local/bin/mplayer
[log_console_mplayer.txt](https://github.com/MacWarrior/clipbucket-5.0/files/2812823/log_console_mplayer.txt)

Log of path: /usr/local/bin/ffprobe
[log_console_ffprobe.txt](https://github.com/MacWarrior/clipbucket-5.0/files/2812836/log_console_ffprobe.txt)

I hope this information helps you

**Comment by spirogg** [comment]
The ffmpeg not showing is a bug, even though it might be working corectly. I think it's because of the newer versions for some 
 reason. 

Are you using cPanel or what type of server

**Comment by spirogg** [comment]
Also try and change to SD/HD and upload a smaller file just to test. 
What is max upload size to the server you have. Do you have root access. Or is it hosting company ? What is max upload limit set too ? Not in script but in php.ini

**Comment by spirogg** [comment]
Also see issue #4 that was closed. 
You need to have Imagick installed (not imagemagick) Imagick needs to be installed for php version you are using.. 
Read that post. I have if cPanel is being used , you can copy and past and install if you have root access. Thanks for not ask your host to install for you for each php version you are using. 



seems your using php5.6.3 based on the first photo you gave us with all module version numbers. Show CLI 5.6.3

**Comment by raiancollyn** [comment]
> Are you using cPanel or what type of server
I'm using cPanel in a Site Hosting

> Also try and change to SD/HD and upload a smaller file just to test.
Okay, I'll test here, anything if you have any news or problem, I inform

> What is max upload size to the server you have
By default for all versions of PHP, the hosting company leaves by default 1024 Mb's (1GB) for file uploads, however, it is allowed to make changes through .htaccess and php.ini files

> Do you have root access.
Only the folders related to my hosting, the others only I can consult the information

> Or is it hosting company ?
Yes

> What is max upload limit set too ? Not in script but in php.ini
As I mentioned above, by default the Hosting comes with 1GB, but I can configure for more, as it is in the case of the PDF File that I had sent with the PHP information, if you notice, this information is present in it:
`post_max_size = 10240M
upload_max_filesize = 10240M
max_execution_time = 999990
max_input_vars = 999990
max_input_time = 999990
memory_limit = 10240M`

> seems your using php5.6.3 based on the first photo you gave us with all module version numbers. Show CLI 5.6.3
About this, I'm afraid that the version in the directory is referring to the default version of Hosting, by default it leaves PHP 5.6 as the default, but they allow us to change the version to whatever we want, besides allowing me to place a different version for each domain, for example:
- domaina.com (Version 5.5)
- domainb.com (Version 7.0)
- subdomain.domainb.com (Version 5.2)
![image](https://user-images.githubusercontent.com/20705376/52022206-900ec880-24d6-11e9-89cb-19223d6d73d7.png)
however, as the PHP directory I am using is global, that may be why version 5.6 is coming, I will try to switch to my version
With regards to imagick, yes, it is installed, I will change the address later

**Comment by raiancollyn** [comment]
I made the following changes:
- I changed the PHP CLI version by changing its path
- I switched the path from ImageMagick to Imagick
- Enabled qualities only for HD and SD

The result looks like this:
![image](https://user-images.githubusercontent.com/20705376/52052343-c418d680-2534-11e9-99e0-fd6fa49dc1a2.png)
![image](https://user-images.githubusercontent.com/20705376/52052376-e3afff00-2534-11e9-9ccc-122ae2b1be28.png)

After these changes, I decided to send a new file for testing, about the size, the file is very small, just for the ones, I looked at the log of sending it, it seems that did not give any problem during the conversion process, but at the end , it still returned an error message, see:
[file_conversion_log.txt](https://github.com/MacWarrior/clipbucket-5.0/files/2817016/file_conversion_log.txt)

So, I decided to do a new test, instead of using the ffmpeg path, I decided to use his command, as I had previously mentioned:
![image](https://user-images.githubusercontent.com/20705376/52052656-d6474480-2535-11e9-9867-e08209bff5d8.png)
But it also gave the same result in Log, the whole process went well, but in the end it returned an error message, see:
[file_conversion_log_ffmpeg_command.txt](https://github.com/MacWarrior/clipbucket-5.0/files/2817063/file_conversion_log_ffmpeg_command.txt)

One thing I noticed in the 2 logs was that whenever it comes to generating the thumbnails, the log never generates information, but when I look at the video in the video manager, it has thumbnails:
![image](https://user-images.githubusercontent.com/20705376/52053166-689c1800-2537-11e9-90a6-73e33d55b34a.png)
![image](https://user-images.githubusercontent.com/20705376/52053206-7ea9d880-2537-11e9-95de-4fd747b57582.png)

Well, anyway, thank you for your patience in helping to solve my problems and doubts, I await your return

**Comment by MacWarrior** [comment]
Hi,
Software path were not saved correctly during installation and were set by default
Now they are saved correctly and so used correctly

Can you try again with latest revision ?

**Comment by raiancollyn** [comment]
Hello, how are you?

Yes, I tested this new version here, apparently it is working, I was able to convert without problems, either using the HD and SD option and the option that I can choose the qualities, I also tested with the most recent version of FFMPEG, 4.1.3, too I was able to convert without problems, here is the conversion log file below:
[All_qualities.log](https://github.com/MacWarrior/clipbucket-5.0/files/3408211/All_qualities.log)
[SD_and_HD.log](https://github.com/MacWarrior/clipbucket-5.0/files/3408212/SD_and_HD.log)

I was able to even create the thumbnails without problems, the only problem I found was that I did not go to the page of the Modules ("Tool Box" -> "Server Modules Info"), when I try to access this page, it loads, you would have some problem what might be causing this infinite charge?

I believe it is not a question of resources, since my VPS has these specifications:
Processor: 5 CPUs Intel (R) Xeon (R) CPU E5-2630 v4
RAM: 8GB
Storage: 240 GB SSD

Apart from this loading problem, everything is ok, if you want to check it out, here is a link of the 2 videos that converted resulting:
https://test.grupodpbr.net/watch_video.php?v=MNA57DOB725G
https://test.grupodpbr.net/watch_video.php?v=S9266B61A8Y8

**Comment by MacWarrior** [comment]
Hi,

Thanks for reply !
There is several possible issues resulting as an infinite loading page...

Did you get any php error ? Something related to memory limit per example ?
Are you in DEV mode ? (File development.dev exists in directory /upload/includes/)

This page only do a few things based on the softwares path collected during the installation process or specified on the page General > Website configurations > Uploading and Conversion Settings

Can you check if the specified path really exists on your system ?

**Comment by MacWarrior** [comment]
Hi,

Any news ?

**Comment by raiancollyn** [comment]
Hello, how are you?

Sorry I did not answer before, I was doing several tests but I had not remembered to send the feedback, but unfortunately I was not successful, I even tried to switch servers, I switched to an octacore with 30 GB of Ram and 800 GB of SSD storage, but, Still it was no use.
One thing I noticed is that in older versions of PHP, like 7.0 or lower, when I try to access the screen, it keeps loading, but if I use a newer version, like PHP 7.2, I'm not having any loading issues, just I get an Internal Error message (Code 500)
I found it strange because I have all modules installed and all permissions active to query and use them.

Another thing I also noticed is that after loading a lot in the case of older versions, at some point it stops loading, I get a Gateway Timeout error (Code 504) and if I try to access any other page, most of the time I get this message below:
![image](https://user-images.githubusercontent.com/20705376/63268498-4e6f2080-c262-11e9-9a71-26b1e6c783ca.png)

I can only solve by restarting my server

Is there any suggestion of what I can do?

**Comment by MacWarrior** [comment]
Hi,

This seems to be a server configuration issue (pretty sure it's about your vhost), nothing related to performance ;)
To dev, I use a 2x2ghz core, 4Go RAM VM, nothing huge ; and I could use far less !

On PHP 7.0, what PHP error do you get ? (You'll have to wait for timeout which will generate a PHP error 500 in the error.log file)
Are you in dev mode ?

If you don't have any php error, this is definitely a network/server configuration issue.

**Comment by raiancollyn** [comment]
Hello, how are you?
The development mode I left enabled, as is the case below:
![image](https://user-images.githubusercontent.com/20705376/63349861-50041b80-c32a-11e9-8bb2-3313686ec64a.png)

As for the PHP 7.0 release, I tested it too, but in your case, the page keeps loading until I get the "Gateway Timeout (Code 504)" error, An error code 500 I never get, as in the image below:
![image](https://user-images.githubusercontent.com/20705376/63349955-7924ac00-c32a-11e9-8118-4ce951940883.png)

Regarding this server and / or network configuration, would you have any suggestions what I can do / request from the company hosting my server?

**Comment by MacWarrior** [comment]
Hi,
Thanks for reply.

Can you try again with latest version and WITHOUT dev mode (Just to check) ?

Do you use apache or ngnix ?
In this case, the php error will only be display in the error log file and not in the browser (which stop loading with the error 504)

There should be an infinite loop somewhere or a memory limit ; in dev mode per example, some missing translation can cause a memory limit because of the too heavy backtrace dump : but this case must be revelated in the error log file (if correctly configured)

Can you also compare your configuration with the one in installation scripts (.sh) ?

**Comment by raiancollyn** [comment]
Hello, good afternoon @MacWarrior, sorry for not having continued the problem, on the day you sent the answer I had seen it, but I had completely forgotten to answer, as time went by, I was only able to remember when I recently accessed Clip Bucket's github 5 to view updates

About the problem in the PHP Modules page, I believe that maybe the problem is in the VPS I was using or in the Control Panel

Before I was using a server with the following specifications:
Processor: 5 Intel (R) Xeon (R) CPU E5-2630 v4 CPUs
RAM: 8GB
Storage: 240 GB SSD
Control Panel: cPanel (Last version)

What I'm using now is from the same company, however, it has a little more resources, but as you said that the amount of resources would not make a difference, the only thing I want to highlight would be to change the control panel, in this I'm using Plesk, these are the specifications:
Processor: 6 CPUs
RAM: 16 GB
Storage: 400GB SSD
Control Panel: Plesk Obsidiam (Last version)

Using this server with Plesk installed I had no problems, even installing the latest version of FFMpeg on my server, I had no problem finding it, nor loading the page of modules, as shown in the images below:

![image](https://user-images.githubusercontent.com/20705376/85626381-f4d24200-b63a-11ea-87b4-0c18dd933f15.png)

So I believe that the problem, or is related to that server, or was to the control panel, I didn't have any problems to access the page, I just have to highlight another problem that I had, but this was in the script installation
In the most recent version I downloaded, in this case today (06/24/2020)

I was facing a problem creating the database tables, here is the error below:

> AH01071: Got error 'PHP message: SQL :
 CREATE TABLE `cb_photos` ( `photo_id` bigint(255) NOT NULL AUTO_INCREMENT, `photo_key` mediumtext NOT NULL, `photo_title` mediumtext NOT NULL, `photo_description` mediumtext NOT NULL, `photo_tags` mediumtext NOT NULL, `userid` int(255) NOT NULL, `collection_id` int(255) NOT NULL, `date_added` datetime NOT NULL, `last_viewed` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE current_timestamp(), `views` bigint(255) NOT NULL DEFAULT '0', `allow_comments` enum('yes','no') NOT NULL DEFAULT 'yes', `allow_embedding` enum('yes','no') NOT NULL DEFAULT 'yes', `allow_tagging` enum('yes','no') NOT NULL DEFAULT 'yes', `featured` enum('yes','no') NOT NULL DEFAULT 'no', `reported` enum('yes','no') NOT NULL DEFAULT 'no', `allow_rating` enum('yes','no') NOT NULL DEFAULT 'yes', `broadcast` enum('public','private') NOT NULL DEFAULT 'public', `active` enum('yes','no') NOT NULL DEFAULT 'yes', `total_comments` int(255) NOT NULL DEFAULT '0...
PHP message: ERROR : The used table type doesn't support FULLTEXT indexes
referer: /cb_install/

I believe it is because of my version, I am currently using MariaDB in version 5.5.65


To solve this problem, I had to edit the files "structure.sql" and "upgrade_4.2.sql" which are inside the folder "/ cb_install / sql /" and in the queries I had to do the following
In structure.sql, queries that had the "FULLTEXT" needed to change the "ENGINE = InnoDB" to "ENGINE = MyISAM"
In "upgrade_4.2.sql" I believe it is not mandatory, however, I added "ENGINE = MyISAM" in front of the queries, thus making the changes:
![image](https://user-images.githubusercontent.com/20705376/85627765-10d6e300-b63d-11ea-9734-91b6b6558637.png)
![image](https://user-images.githubusercontent.com/20705376/85627838-2b10c100-b63d-11ea-95ed-7ebb4f277fe5.png)

Making these adjustments I was able to install without problems

As I believe my problem has already been solved, if you want you can consider this topic as closed

Sorry again for my lack of return

**Comment by raiancollyn** [comment]
Hello again, sorry to be running away from the topic with the one mentioned above regarding the installation, but I also found another problem, this one now refers to the video upload page
I'm trying to access it, but I only get an error 500:

![image](https://user-images.githubusercontent.com/20705376/85643264-9e2c2e80-b661-11ea-8cbd-fb733e88a2e3.png)

This does not occur overload problems, it only appears when I try to access the page
I took a look at the logs, but did not say anything in specific what could be the cause, below is an image of the logs:
![image](https://user-images.githubusercontent.com/20705376/85643331-cae04600-b661-11ea-8607-58cf2431eaf9.png)

For now this was the only problem I found that I could not solve, only this page is being affected, the others are working without any problem

**Comment by MacWarrior** [comment]
Hi,

I hope I'll be giving here a full answer to your long reply ! 😄 

- The error 500 specified has been fixed in another issue (#142)
- The SQL error specified is linked to your MariaDB version : Can you check install_centos7.sh file to upgrade your MariaDB version to 10.3+ ?
- You should also fix the missing softwares reported in server modules info (Also check install_centos7.sh)

I'm closing the issue but don't hesitate to open a new one if you find any new error with latest commit ! 😉 

Best regards,
MacWarrior.
